WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
DECLARE
  h NUMBER;
  state VARCHAR2(30);
BEGIN
  h := DBMS_DATAPUMP.OPEN('EXPORT', 'SCHEMA', job_name => 'HR_SYN200_BACKUP_20260928');
  DBMS_DATAPUMP.ADD_FILE(h, 'HR_before_synthetic200_20260928.dmp', 'DATA_PUMP_DIR');
  DBMS_DATAPUMP.ADD_FILE(h, 'HR_before_synthetic200_20260928.log', 'DATA_PUMP_DIR', filetype => DBMS_DATAPUMP.KU$_FILE_TYPE_LOG_FILE);
  DBMS_DATAPUMP.METADATA_FILTER(h, 'SCHEMA_EXPR', '= ''HR''');
  DBMS_DATAPUMP.SET_PARAMETER(h, 'FLASHBACK_SCN', DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER);
  DBMS_DATAPUMP.START_JOB(h);
  DBMS_DATAPUMP.WAIT_FOR_JOB(h, state);
  DBMS_OUTPUT.PUT_LINE('BACKUP_STATE=' || state);
  IF state <> 'COMPLETED' THEN RAISE_APPLICATION_ERROR(-20001, 'Backup incomplete'); END IF;
END;
/
EXIT