whenever sqlerror exit failure rollback
set serveroutput on
BEGIN
 FOR o IN (SELECT 'HR' owner FROM DUAL UNION ALL SELECT 'HR_UAT_200' FROM DUAL) LOOP
  EXECUTE IMMEDIATE 'INSERT INTO '||o.owner||'.TB_NHANVIEN_THOIVIEC(SOQDTV,MANV,NGAYNOPDON,NGAYNGHIVIEC,LYDOTV,GHICHUTV,CREATED_BY,CREATED_DATE)
   SELECT ''UAT-TV-''||MANV,MANV,DATE ''2026-09-01'',DATE ''2026-09-16'',''Synthetic contract end'',''Last working date 2026-09-15'',1,DATE ''2026-09-01''
   FROM '||o.owner||'.TB_NHANVIEN n WHERE n.MANV BETWEEN 190 AND 194 AND n.DATHOIVIEC=1
   AND NOT EXISTS (SELECT 1 FROM '||o.owner||'.TB_NHANVIEN_THOIVIEC t WHERE t.MANV=n.MANV)';
  DBMS_OUTPUT.PUT_LINE(o.owner||' exit records added='||SQL%ROWCOUNT);
 END LOOP;
 COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;
END;
/
exit
