-- One-time, authorized replacement of HR business data with verified synthetic data.
-- Run using local SYSDBA. Full original HR is retained in HR_RESTORE_200 and Data Pump.
whenever sqlerror exit failure rollback
set serveroutput on size unlimited
set timing on
alter session set current_schema=HR;
DECLARE
 tables SYS.ODCIVARCHAR2LIST:=SYS.ODCIVARCHAR2LIST('TB_BANGCONG_CHITIET',
'TB_KYCONGCHITIET',
'TB_KYCONG',
'TB_HESO_TANGCA',
'TB_PHUCAP',
'TB_LOAIHOPDONG',
'TB_QUYDINH_CHAMCONG',
'TB_LOAICA',
'TB_LOAICONG',
'TB_NGAYLE',
'TB_CONGTY',
'TB_PHONGBAN',
'TB_BOPHAN',
'TB_CHUCVU',
'TB_CHINH_SACH_BHXH',
'TB_CHINH_SACH_LUONG',
'TB_CHINH_SACH_CONG_DOAN',
'TB_THUE_TNCN_CHINH_SACH',
'TB_PAYROLL_CALCULATION_RUN',
'TB_CHAMCONG_LANTINH',
'TB_CA_PHIENBAN',
'TB_NHANVIEN',
'TB_CHINH_SACH_BHXH_VUNG',
'TB_THUE_TNCN_BAC',
'TB_CHAMCONG_KQ_NGAY',
'TB_BANGCONG',
'TB_YEUCAU_NGHIPHEP',
'TB_YEUCAU_TANGCA',
'TB_NHANVIEN_PHUCAP',
'TB_NGUOI_PHU_THUOC',
'TB_NHANVIEN_THUE',
'TB_NHANVIEN_CONG_DOAN_THAM_GIA',
'TB_NHANVIEN_BAOHIEM_THAM_GIA',
'TB_BAOHIEM',
'TB_KHENTHUONG_KYLUAT',
'TB_UNGLUONG',
'TB_NHANVIEN_THOIVIEC',
'TB_DIEUCHUYEN_NHANVIEN',
'TB_NANGLUONG_NHANVIEN',
'TB_HOPDONG',
'TB_LICH_LAMVIEC',
'TB_CA_KHUNGGIO',
'TB_UAT_SCENARIO',
'TB_LUONG_HIEULUC',
'TB_BAOHIEM_BIENDONG',
'TB_USER_EMPLOYEE_MAPPING',
'TB_BANGLUONG',
'TB_QUYET_TOAN_THUE_NAM',
'TB_YEUCAU_DIEUCHINHCONG',
'TB_TANGCA',
'TB_PHEP_SOPHATSINH',
'TB_CHAMCONG_SUKIEN',
'TB_BANGLUONG_CT',
'TB_BANGLUONG_BAOHIEM',
'TB_BANGLUONG_CONG_DOAN',
'TB_BANGLUONG_THUE_CT',
'TB_BANGLUONG_OT_COMPLIANCE',
'TB_QUYET_TOAN_THUE_NAM_CT',
'TB_CHAMCONG_BATTHUONG',
'TB_CONG_PHANDOAN',
'TB_BANGLUONG_CT_SOURCE',
'TB_CHAMCONG_BT_LICHSU',
'TB_CONG_PD_NGUON');
 n NUMBER; m NUMBER; original_users NUMBER; original_rights NUMBER;
 cols VARCHAR2(32767); source_cols VARCHAR2(32767); disabled_auto BOOLEAN:=FALSE;
 PROCEDURE require_count(q VARCHAR2, expected NUMBER, label VARCHAR2) IS v NUMBER;
 BEGIN EXECUTE IMMEDIATE q INTO v; IF v<>expected THEN RAISE_APPLICATION_ERROR(-20190,label||' actual='||v||' expected='||expected); END IF; END;
BEGIN
 require_count('SELECT COUNT(*) FROM HR.TB_NHANVIEN',976,'Original employee baseline');
 require_count('SELECT COUNT(*) FROM HR_RESTORE_200.TB_NHANVIEN',976,'Verified rollback schema');
 require_count('SELECT COUNT(*) FROM HR_UAT_200.TB_NHANVIEN',200,'Synthetic employee count');
 require_count('SELECT COUNT(*) FROM HR_UAT_200.TB_UAT_SCENARIO WHERE KET_QUA=''PASS''',23,'UAT scenarios');
 require_count('SELECT COUNT(*) FROM HR_UAT_200.TB_BANGLUONG',581,'UAT payroll count');
 require_count('SELECT COUNT(*) FROM HR.TB_KYCONG WHERE MAKYCONG=202609 AND CONG_INPUT_REV=21 AND CONG_PUBLISH_REV=11',1,'Unchanged live revision');
 require_count('SELECT COUNT(*) FROM DBA_ERRORS WHERE OWNER=''HR_UAT_200''',0,'UAT compilation');
 require_count('SELECT COUNT(*) FROM HR.TB_SYS_USER WHERE IDUSER=1',0,'Reserved synthetic audit identity');
 SELECT COUNT(*) INTO original_users FROM HR.TB_SYS_USER;
 SELECT COUNT(*) INTO original_rights FROM HR.TB_SYS_RIGHT;
 EXECUTE IMMEDIATE 'ALTER TRIGGER HR.TRG_AUTO_BAOHIEM DISABLE'; disabled_auto:=TRUE;
 EXECUTE IMMEDIATE 'LOCK TABLE HR.TB_SYS_USER IN EXCLUSIVE MODE NOWAIT';
 EXECUTE IMMEDIATE 'LOCK TABLE HR.TB_SYS_RIGHT IN EXCLUSIVE MODE NOWAIT';
 FOR i IN 1..tables.COUNT LOOP
  EXECUTE IMMEDIATE 'LOCK TABLE HR.'||tables(i)||' IN EXCLUSIVE MODE NOWAIT';
  EXECUTE IMMEDIATE 'LOCK TABLE HR_UAT_200.'||tables(i)||' IN EXCLUSIVE MODE NOWAIT';
 END LOOP;
 -- Reject source drift since the independently restored backup, before any DELETE.
 FOR i IN 1..tables.COUNT LOOP
  SELECT COUNT(*) INTO n FROM DBA_TABLES WHERE OWNER='HR_RESTORE_200' AND TABLE_NAME=tables(i);
  IF n=1 THEN
   EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM HR.'||tables(i) INTO n;
   EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM HR_RESTORE_200.'||tables(i) INTO m;
   IF n<>m THEN RAISE_APPLICATION_ERROR(-20191,'Baseline changed: '||tables(i)); END IF;
  END IF;
 END LOOP;
 -- Synthetic audit actor has no password, is disabled, and receives only deny permissions.
 INSERT INTO HR.TB_SYS_USER(IDUSER,USERNAME,FULLNAME,PASSWORD,DISABLED,ISGROUP,CLIENT_TYPE)
 VALUES(1,N'UAT_GENERATOR',N'Synthetic dataset audit actor',NULL,1,0,N'ALL');
 -- Preserve user accounts and rights, but never relink old accounts to synthetic identities by accident.
 UPDATE HR.TB_SYS_USER SET MANV=NULL WHERE MANV IS NOT NULL;
 UPDATE HR.TB_BANGCONG_CHITIET SET LANTINH_ID_HIENHANH=NULL WHERE LANTINH_ID_HIENHANH IS NOT NULL;
 FOR i IN REVERSE 1..tables.COUNT LOOP
  EXECUTE IMMEDIATE 'DELETE FROM HR.'||tables(i);
 END LOOP;
 FOR i IN 1..tables.COUNT LOOP
  SELECT LISTAGG('"'||COLUMN_NAME||'"',',') WITHIN GROUP(ORDER BY COLUMN_ID),
    LISTAGG(CASE WHEN TABLE_NAME='TB_BANGCONG_CHITIET' AND COLUMN_NAME='LANTINH_ID_HIENHANH' THEN 'NULL'
      ELSE '"'||COLUMN_NAME||'"' END,',') WITHIN GROUP(ORDER BY COLUMN_ID)
  INTO cols,source_cols FROM DBA_TAB_COLUMNS WHERE OWNER='HR' AND TABLE_NAME=tables(i);
  EXECUTE IMMEDIATE 'INSERT INTO HR.'||tables(i)||' ('||cols||') SELECT '||source_cols||' FROM HR_UAT_200.'||tables(i);
  DBMS_OUTPUT.PUT_LINE('COPIED '||tables(i)||' '||SQL%ROWCOUNT);
 END LOOP;
 MERGE INTO HR.TB_BANGCONG_CHITIET t USING HR_UAT_200.TB_BANGCONG_CHITIET s ON(t.IDBANGCONGCT=s.IDBANGCONGCT)
 WHEN MATCHED THEN UPDATE SET t.LANTINH_ID_HIENHANH=s.LANTINH_ID_HIENHANH;
 FOR i IN 1..tables.COUNT LOOP
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM HR.'||tables(i) INTO n;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM HR_UAT_200.'||tables(i) INTO m;
  IF n<>m THEN RAISE_APPLICATION_ERROR(-20192,'Copy count mismatch: '||tables(i)); END IF;
 END LOOP;
 require_count('SELECT COUNT(*) FROM HR.TB_SYS_USER',original_users+1,'Preserved accounts');
 require_count('SELECT COUNT(*) FROM (SELECT FUNCTION_CODE,IDUSER,USER_RIGHT,CAN_VIEW,CAN_ADD,CAN_EDIT,CAN_DELETE,CAN_PRINT FROM HR_RESTORE_200.TB_SYS_RIGHT MINUS SELECT FUNCTION_CODE,IDUSER,USER_RIGHT,CAN_VIEW,CAN_ADD,CAN_EDIT,CAN_DELETE,CAN_PRINT FROM HR.TB_SYS_RIGHT)',0,'Every original permission preserved');
 require_count('SELECT COUNT(*) FROM HR.TB_BANGLUONG_CT_SOURCE WHERE SOURCE_TYPE=''BANGCONG'' AND SOURCE_CONG_LANTINH_ID IS NULL',0,'Payroll day-version trace');
 require_count('SELECT COUNT(*) FROM HR.TB_BANGCONG_CHITIET WHERE LANTINH_ID_HIENHANH IS NULL',0,'Current day anchors');
 COMMIT;
 EXECUTE IMMEDIATE 'ALTER TRIGGER HR.TRG_AUTO_BAOHIEM ENABLE'; disabled_auto:=FALSE;
 DBMS_OUTPUT.PUT_LINE('CUTOVER_COMMITTED employees=200 payroll=581');
EXCEPTION WHEN OTHERS THEN
 ROLLBACK;
 IF disabled_auto THEN EXECUTE IMMEDIATE 'ALTER TRIGGER HR.TRG_AUTO_BAOHIEM ENABLE'; END IF;
 RAISE;
END;
/
exit
