whenever sqlerror exit failure rollback
set serveroutput on size unlimited
alter session set current_schema=HR;
-- Repair imported explicit keys without resetting sequences backwards.
DECLARE
 n NUMBER; mx NUMBER;
 PROCEDURE align_seq(s VARCHAR2,t VARCHAR2,c VARCHAR2) IS
 BEGIN
  EXECUTE IMMEDIATE 'SELECT NVL(MAX('||c||'),0) FROM HR.'||t INTO mx;
  EXECUTE IMMEDIATE 'SELECT HR.'||s||'.NEXTVAL FROM DUAL' INTO n;
  IF n<=mx THEN
   EXECUTE IMMEDIATE 'ALTER SEQUENCE HR.'||s||' INCREMENT BY '||TO_CHAR(mx+1-n,'FM9999999999999999990');
   EXECUTE IMMEDIATE 'SELECT HR.'||s||'.NEXTVAL FROM DUAL' INTO n;
   EXECUTE IMMEDIATE 'ALTER SEQUENCE HR.'||s||' INCREMENT BY 1';
  END IF;
  DBMS_OUTPUT.PUT_LINE('SEQUENCE_OK '||s);
 END;
BEGIN
 align_seq('SEQ_BANGLUONG_BAOHIEM','TB_BANGLUONG_BAOHIEM','ID');
 align_seq('SEQ_BANGLUONG_CONG_DOAN','TB_BANGLUONG_CONG_DOAN','ID');
 align_seq('SEQ_BANGLUONG_CT','TB_BANGLUONG_CT','IDBLCT');
 align_seq('SEQ_BANGLUONG_CT_SOURCE','TB_BANGLUONG_CT_SOURCE','ID');
 align_seq('SEQ_BANGLUONG_OT_COMPLIANCE','TB_BANGLUONG_OT_COMPLIANCE','ID');
 align_seq('SEQ_BANGLUONG_THUE_CT','TB_BANGLUONG_THUE_CT','ID');
 align_seq('SEQ_CHINH_SACH_BHXH','TB_CHINH_SACH_BHXH','ID');
 align_seq('SEQ_CHINH_SACH_BHXH_VUNG','TB_CHINH_SACH_BHXH_VUNG','ID');
 align_seq('SEQ_CHINH_SACH_CONG_DOAN','TB_CHINH_SACH_CONG_DOAN','ID');
 align_seq('SEQ_CHINH_SACH_LUONG','TB_CHINH_SACH_LUONG','ID');
 align_seq('SEQ_NGUOI_PHU_THUOC','TB_NGUOI_PHU_THUOC','ID');
 align_seq('SEQ_QUYET_TOAN_THUE_NAM','TB_QUYET_TOAN_THUE_NAM','ID');
 align_seq('SEQ_QUYET_TOAN_THUE_NAM_CT','TB_QUYET_TOAN_THUE_NAM_CT','ID');
 align_seq('SEQ_THUE_TNCN_BAC','TB_THUE_TNCN_BAC','ID');
 align_seq('SEQ_THUE_TNCN_CHINH_SACH','TB_THUE_TNCN_CHINH_SACH','ID');
 align_seq('SEQ_NV_BAOHIEM_TG','TB_NHANVIEN_BAOHIEM_THAM_GIA','ID');
 align_seq('SEQ_NV_CONGDOAN_TG','TB_NHANVIEN_CONG_DOAN_THAM_GIA','ID');
 align_seq('SEQ_NV_THUE','TB_NHANVIEN_THUE','ID');
 align_seq('SEQ_PAYROLL_CALC_RUN','TB_PAYROLL_CALCULATION_RUN','RUN_ID');
 FOR r IN (SELECT i.table_name,i.column_name,i.generation_type,c.default_on_null
 FROM DBA_TAB_IDENTITY_COLS i JOIN DBA_TAB_COLUMNS c
 ON c.owner=i.owner AND c.table_name=i.table_name AND c.column_name=i.column_name
 WHERE i.owner='HR' AND i.table_name IN ('TB_BANGLUONG_CT_SOURCE','TB_BANGLUONG_CT','TB_BANGLUONG_BAOHIEM','TB_BANGLUONG_CONG_DOAN','TB_BANGLUONG_THUE_CT','TB_BANGLUONG_OT_COMPLIANCE','TB_BANGLUONG','TB_QUYET_TOAN_THUE_NAM_CT','TB_QUYET_TOAN_THUE_NAM','TB_PAYROLL_CALCULATION_RUN','TB_CHAMCONG_BT_LICHSU','TB_CHAMCONG_BATTHUONG','TB_CONG_PD_NGUON','TB_CONG_PHANDOAN','TB_CHAMCONG_KQ_NGAY','TB_CHAMCONG_LANTINH','TB_BANGCONG_CHITIET','TB_KYCONGCHITIET','TB_BANGCONG','TB_KYCONG','TB_YEUCAU_DIEUCHINHCONG','TB_YEUCAU_NGHIPHEP','TB_YEUCAU_TANGCA','TB_TANGCA','TB_HESO_TANGCA','TB_NHANVIEN_PHUCAP','TB_PHUCAP','TB_NGUOI_PHU_THUOC','TB_NHANVIEN_THUE','TB_NHANVIEN_CONG_DOAN_THAM_GIA','TB_NHANVIEN_BAOHIEM_THAM_GIA','TB_BAOHIEM','TB_KHENTHUONG_KYLUAT','TB_UNGLUONG','TB_NHANVIEN_THOIVIEC','TB_DIEUCHUYEN_NHANVIEN','TB_NANGLUONG_NHANVIEN','TB_HOPDONG','TB_LOAIHOPDONG','TB_LICH_LAMVIEC','TB_CA_KHUNGGIO','TB_CA_PHIENBAN','TB_QUYDINH_CHAMCONG','TB_LOAICA','TB_LOAICONG','TB_NGAYLE','TB_NHANVIEN','TB_CONGTY','TB_PHONGBAN','TB_BOPHAN','TB_CHUCVU','TB_CHINH_SACH_BHXH_VUNG','TB_CHINH_SACH_BHXH','TB_CHINH_SACH_LUONG','TB_CHINH_SACH_CONG_DOAN','TB_THUE_TNCN_BAC','TB_THUE_TNCN_CHINH_SACH','TB_UAT_SCENARIO','TB_LUONG_HIEULUC','TB_BAOHIEM_BIENDONG','TB_PHEP_SOPHATSINH','TB_CHAMCONG_SUKIEN','TB_USER_EMPLOYEE_MAPPING')) LOOP
  EXECUTE IMMEDIATE 'ALTER TABLE HR.'||r.table_name||' MODIFY ('||r.column_name||
    ' GENERATED '||r.generation_type||CASE WHEN r.default_on_null='YES' THEN ' ON NULL' ELSE '' END||
    ' AS IDENTITY (START WITH LIMIT VALUE))';
  DBMS_OUTPUT.PUT_LINE('IDENTITY_OK '||r.table_name);
 END LOOP;
END;
/
ALTER TRIGGER HR.TRG_AUTO_BAOHIEM DISABLE;
@database/synthetic200/hr_input_revisions.sql
DECLARE n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM DBA_ERRORS WHERE OWNER='HR';
 IF n<>0 THEN RAISE_APPLICATION_ERROR(-20194,'HR has invalid compiled objects'); END IF;
 SELECT COUNT(*) INTO n FROM HR.SCHEMA_VERSION WHERE VERSION='1.19' AND SUCCESS=1;
 IF n=0 THEN
  INSERT INTO HR.SCHEMA_VERSION(INSTALLED_RANK,VERSION,DESCRIPTION,TYPE,SCRIPT,INSTALLED_BY,INSTALLED_ON,SUCCESS)
  SELECT NVL(MAX(INSTALLED_RANK),0)+1,'1.19','Attendance and payroll integrity; synthetic 200 fixture','SQL',
   'V1_19__attendance_payroll_data_integrity.sql','HR',SYSTIMESTAMP,1 FROM HR.SCHEMA_VERSION;
 END IF;
 COMMIT;
END;
/
exit
