BEGIN
 IF USER<>'HR_UAT_200' THEN RAISE_APPLICATION_ERROR(-20000,'UAT owner required'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE UAT_TOUCH_PERIOD(a DATE,b DATE) AS
BEGIN
 UPDATE TB_KYCONG SET CONG_INPUT_REV=NVL(CONG_INPUT_REV,0)+1
 WHERE MAKYCONG BETWEEN TO_NUMBER(TO_CHAR(a,'YYYYMM')) AND TO_NUMBER(TO_CHAR(b,'YYYYMM'));
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_LICH AFTER INSERT OR UPDATE OR DELETE ON TB_LICH_LAMVIEC FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(:OLD.NGAY,:OLD.NGAY); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(:NEW.NGAY,:NEW.NGAY); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_RAW AFTER INSERT OR UPDATE OR DELETE ON TB_BANGCONG FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(ADD_MONTHS(DATE '2000-01-01',(:OLD.NAM-2000)*12+:OLD.THANG-1),ADD_MONTHS(DATE '2000-01-01',(:OLD.NAM-2000)*12+:OLD.THANG-1)); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(ADD_MONTHS(DATE '2000-01-01',(:NEW.NAM-2000)*12+:NEW.THANG-1),ADD_MONTHS(DATE '2000-01-01',(:NEW.NAM-2000)*12+:NEW.THANG-1)); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_OT AFTER INSERT OR UPDATE OR DELETE ON TB_YEUCAU_TANGCA FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(NVL(:OLD.BATDAU_DUYET,:OLD.NGAY),NVL(:OLD.KETTHUC_DUYET,:OLD.NGAY)); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(NVL(:NEW.BATDAU_DUYET,:NEW.NGAY),NVL(:NEW.KETTHUC_DUYET,:NEW.NGAY)); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_LEAVE AFTER INSERT OR UPDATE OR DELETE ON TB_YEUCAU_NGHIPHEP FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(:OLD.TUNGAY,:OLD.DENNGAY); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(:NEW.TUNGAY,:NEW.DENNGAY); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_ADJUST AFTER INSERT OR UPDATE OR DELETE ON TB_YEUCAU_DIEUCHINHCONG FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(:OLD.NGAY,:OLD.NGAY); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(:NEW.NGAY,:NEW.NGAY); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_POLICY AFTER INSERT OR UPDATE OR DELETE ON TB_QUYDINH_CHAMCONG FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(:OLD.TU_NGAY,NVL(:OLD.DEN_NGAY,DATE '9999-12-31')); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(:NEW.TU_NGAY,NVL(:NEW.DEN_NGAY,DATE '9999-12-31')); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_SHIFT AFTER INSERT OR UPDATE OR DELETE ON TB_CA_PHIENBAN FOR EACH ROW
BEGIN
 IF UPDATING OR DELETING THEN UAT_TOUCH_PERIOD(:OLD.TU_NGAY,NVL(:OLD.DEN_NGAY,DATE '9999-12-31')); END IF;
 IF INSERTING OR UPDATING THEN UAT_TOUCH_PERIOD(:NEW.TU_NGAY,NVL(:NEW.DEN_NGAY,DATE '9999-12-31')); END IF;
END;
/
CREATE OR REPLACE TRIGGER UAT_REV_FRAME AFTER INSERT OR UPDATE OR DELETE ON TB_CA_KHUNGGIO FOR EACH ROW
BEGIN
 UPDATE TB_KYCONG SET CONG_INPUT_REV=NVL(CONG_INPUT_REV,0)+1
 WHERE EXISTS(SELECT 1 FROM TB_LICH_LAMVIEC l WHERE TO_NUMBER(TO_CHAR(l.NGAY,'YYYYMM'))=TB_KYCONG.MAKYCONG
 AND l.IDCAPHIENBAN IN (:OLD.IDCAPHIENBAN,:NEW.IDCAPHIENBAN));
END;
/
