BEGIN
 IF USER<>'HR_UAT_200' THEN RAISE_APPLICATION_ERROR(-20000,'UAT owner required'); END IF;
END;
/
ALTER TABLE TB_HESO_TANGCA ADD (LA_BAN_DEM NUMBER(1), CO_OT_BAN_NGAY_TRUOC NUMBER(1))
/
ALTER TABLE TB_HESO_TANGCA ADD CONSTRAINT CK19_OT_FLAGS CHECK (LA_BAN_DEM IN (0,1) AND (CO_OT_BAN_NGAY_TRUOC IS NULL OR CO_OT_BAN_NGAY_TRUOC IN (0,1)))
/
ALTER TABLE TB_BANGLUONG_CT_SOURCE ADD (POLICY_OT_ID NUMBER)
/
ALTER TABLE TB_BANGLUONG_CT_SOURCE ADD CONSTRAINT FK19_UAT_OT_RULE FOREIGN KEY(POLICY_OT_ID) REFERENCES TB_HESO_TANGCA(ID)
/
DECLARE
 PROCEDURE rule(id NUMBER, kind VARCHAR2, night NUMBER, prior_flag NUMBER, factor NUMBER) IS BEGIN
  INSERT INTO TB_HESO_TANGCA(ID,TEN_QUYDINH,LOAICONG,GIO_BATDAU,GIO_KETTHUC,HESO_CHINHTHUC,HESO_THUVIEC,
    TU_NGAY,SO_PHIENBAN,TRANG_THAI,LA_BAN_DEM,CO_OT_BAN_NGAY_TRUOC,GHICHU)
  VALUES(id,'UAT rule '||id,kind,'00:00','24:00',factor,factor,DATE '2026-01-01',1,'PUBLISHED',night,prior_flag,'Synthetic fixture rates; not certified for production payroll');
 END;
BEGIN
 rule(1,'THUONG',0,NULL,1.5);
 rule(2,'THUONG',1,0,2);
 rule(3,'THUONG',1,1,2.1);
 rule(4,'NGHI_TUAN',0,NULL,2);
 rule(5,'NGHI_TUAN',1,NULL,2.7);
 rule(6,'LE',0,NULL,3);
 rule(7,'LE',1,NULL,3.9);
 COMMIT;
END;
/
