whenever sqlerror exit failure rollback
set serveroutput on size unlimited
set linesize 180 pagesize 100
alter session set current_schema=HR;
DECLARE
 n NUMBER; old_rev NUMBER; new_rev NUMBER; rejected BOOLEAN:=FALSE;
 PROCEDURE check_count(q VARCHAR2,e NUMBER,label VARCHAR2) IS v NUMBER;
 BEGIN EXECUTE IMMEDIATE q INTO v; IF v<>e THEN RAISE_APPLICATION_ERROR(-20200,label||' actual='||v||' expected='||e); END IF;
 DBMS_OUTPUT.PUT_LINE('PASS '||label||' = '||v); END;
BEGIN
 check_count('SELECT COUNT(*) FROM HR.TB_NHANVIEN',200,'Employees');
 check_count('SELECT COUNT(*) FROM HR.TB_CONGTY',1,'Single company');
 check_count('SELECT COUNT(*) FROM HR.TB_HOPDONG',200,'Contracts');
 check_count('SELECT COUNT(*) FROM HR.TB_BAOHIEM',200,'Insurance master');
 check_count('SELECT COUNT(*) FROM HR.TB_NHANVIEN_BAOHIEM_THAM_GIA',200,'Insurance profiles');
 check_count('SELECT COUNT(*) FROM HR.TB_NHANVIEN_THUE',200,'Tax profiles');
 check_count('SELECT COUNT(*) FROM HR.TB_NHANVIEN_CONG_DOAN_THAM_GIA',200,'Union profiles');
 check_count('SELECT COUNT(*) FROM HR.TB_UAT_SCENARIO WHERE KET_QUA=''PASS''',23,'Attendance scenarios');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGLUONG WHERE MAKYCONG=202607',194,'July payroll');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGLUONG WHERE MAKYCONG=202608',194,'August payroll');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGLUONG WHERE MAKYCONG=202609',193,'September payroll');
 check_count('SELECT COUNT(DISTINCT MANV) FROM HR.TB_BANGCONG_CHITIET WHERE MAKYCONG=202609 AND DU_DIEUKIEN_CHOT=0',7,'Intentionally pending employees');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGCONG_CHITIET WHERE LANTINH_ID_HIENHANH IS NULL',0,'Missing current anchors');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGCONG_CHITIET b LEFT JOIN HR.TB_NHANVIEN n ON n.MANV=b.MANV WHERE n.MANV IS NULL',0,'Logical employee references');
 check_count('SELECT COUNT(*) FROM HR.TB_CHAMCONG_KQ_NGAY d JOIN HR.TB_CHAMCONG_LANTINH r ON r.IDLANTINH=d.IDLANTINH WHERE d.NGAY<r.TU_NGAY OR d.NGAY>=r.DEN_NGAY',0,'Run range violations');
 check_count('SELECT COUNT(*) FROM HR.TB_CONG_PHANDOAN WHERE KETTHUC_LUC>TRUNC(BATDAU_LUC)+1 OR KETTHUC_LUC<=BATDAU_LUC',0,'Segment time violations');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGLUONG_CT_SOURCE WHERE SOURCE_TYPE=''BANGCONG'' AND SOURCE_CONG_LANTINH_ID IS NULL',0,'Missing payroll source version');
 check_count('SELECT COUNT(*) FROM HR.TB_BANGLUONG_CT c WHERE c.MA_KHOAN_MUC IN (''LUONG_CONG_THUCTE'',''TIEN_TANG_CA'') AND ABS(c.THANH_TIEN-NVL((SELECT SUM(s.AMOUNT_CONTRIBUTED) FROM HR.TB_BANGLUONG_CT_SOURCE s WHERE s.IDBLCT=c.IDBLCT),0))>0.01',0,'Wage and OT source amounts reconcile');
 check_count('SELECT COUNT(*) FROM DBA_ERRORS WHERE OWNER=''HR''',0,'Compilation errors');
 check_count('SELECT COUNT(*) FROM DBA_CONSTRAINTS WHERE OWNER=''HR'' AND TABLE_NAME NOT LIKE ''BIN$%'' AND STATUS<>''ENABLED''',0,'Disabled constraints');
 check_count('SELECT COUNT(*) FROM HR.TB_SYS_USER WHERE IDUSER<>1',18,'Original accounts preserved');
 check_count('SELECT COUNT(*) FROM HR.TB_SYS_USER WHERE IDUSER=1 AND DISABLED=1 AND PASSWORD IS NULL',1,'Disabled synthetic audit actor');
 check_count('SELECT COUNT(*) FROM (SELECT FUNCTION_CODE,IDUSER,USER_RIGHT,CAN_VIEW,CAN_ADD,CAN_EDIT,CAN_DELETE,CAN_PRINT FROM HR_RESTORE_200.TB_SYS_RIGHT MINUS SELECT FUNCTION_CODE,IDUSER,USER_RIGHT,CAN_VIEW,CAN_ADD,CAN_EDIT,CAN_DELETE,CAN_PRINT FROM HR.TB_SYS_RIGHT)',0,'Original permissions preserved');
 check_count('SELECT COUNT(*) FROM HR.TB_SYS_USER WHERE MANV IS NOT NULL',0,'No accidental old account mapping');
 check_count('SELECT COUNT(*) FROM DBA_TRIGGERS WHERE OWNER=''HR'' AND TRIGGER_NAME=''TRG_AUTO_BAOHIEM'' AND STATUS=''DISABLED''',1,'No fabricated insurance on employee insert');
 SELECT CONG_INPUT_REV INTO old_rev FROM HR.TB_KYCONG WHERE MAKYCONG=202607;
 SAVEPOINT revision_probe;
 UPDATE HR.TB_LICH_LAMVIEC SET NGAY=NGAY WHERE IDLICH=(SELECT MIN(IDLICH) FROM HR.TB_LICH_LAMVIEC WHERE NGAY=DATE '2026-07-01');
 SELECT CONG_INPUT_REV INTO new_rev FROM HR.TB_KYCONG WHERE MAKYCONG=202607;
 IF new_rev<=old_rev THEN RAISE_APPLICATION_ERROR(-20201,'Revision was not invalidated'); END IF;
 ROLLBACK TO revision_probe;
 DBMS_OUTPUT.PUT_LINE('PASS Input change invalidates revision; rolled back');
 UPDATE HR.TB_KYCONG SET KHOA=1 WHERE MAKYCONG=202607;
 BEGIN
  UPDATE HR.TB_LICH_LAMVIEC SET NGAY=NGAY WHERE IDLICH=(SELECT MIN(IDLICH) FROM HR.TB_LICH_LAMVIEC WHERE NGAY=DATE '2026-07-01');
 EXCEPTION WHEN OTHERS THEN IF SQLCODE=-20193 THEN rejected:=TRUE; ELSE RAISE; END IF; END;
 IF NOT rejected THEN RAISE_APPLICATION_ERROR(-20202,'Locked-period input accepted'); END IF;
 ROLLBACK;
 DBMS_OUTPUT.PUT_LINE('PASS Locked-period input rejected; rolled back');
 DBMS_OUTPUT.PUT_LINE('POSTFLIGHT_ALL_PASSED');
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;
END;
/
SELECT MAKYCONG,COUNT(*) PAYROLL_ROWS,SUM(THUC_LINH) NET_PAY FROM HR.TB_BANGLUONG GROUP BY MAKYCONG ORDER BY MAKYCONG;
SELECT MAKYCONG,CONG_INPUT_REV,CONG_PUBLISH_REV,KHOA FROM HR.TB_KYCONG ORDER BY MAKYCONG;
exit
