BEGIN
 IF USER<>'HR_UAT_200' THEN RAISE_APPLICATION_ERROR(-20000,'UAT owner required'); END IF;
END;
/
ALTER TABLE TB_BANGLUONG MODIFY (VUNG_LUONG NUMBER(4,0))
/
ALTER TABLE TB_BANGLUONG_BAOHIEM MODIFY (VUNG_LUONG NUMBER(4,0))
/
ALTER TABLE TB_CHINH_SACH_BHXH_VUNG MODIFY (VUNG_LUONG NUMBER(4,0))
/
ALTER TABLE TB_NHANVIEN_BAOHIEM_THAM_GIA MODIFY (VUNG_LUONG NUMBER(4,0))
/
