-- Fully synthetic, deterministic fixture. Requires an empty HR_UAT_200 schema.
DECLARE
 n NUMBER; d DATE; mk NUMBER; sid NUMBER; mins NUMBER; endmins NUMBER;
 punchid NUMBER := 0; dayid NUMBER := 0; reqid NUMBER := 1000; lid NUMBER := 0;
 starts DATE; ends DATE; dtin DATE; dtout DATE; salary NUMBER; isrest BOOLEAN; restflag NUMBER;
 PROCEDURE frame(c NUMBER, ord NUMBER, a NUMBER, b NUMBER, kind VARCHAR2) IS BEGIN
  INSERT INTO TB_CA_KHUNGGIO(IDCAPHIENBAN,STT,BATDAU_PHUT,KETTHUC_PHUT,LOAI_KHUNGGIO,BAT_BUOC_QUET_THE)
  VALUES(c,ord,a,b,kind,CASE WHEN kind='LAM_VIEC' THEN 1 ELSE 0 END);
 END;
 PROCEDURE punch(emp NUMBER, daydate DATE, tin DATE, tout DATE) IS BEGIN
  punchid:=punchid+1;
  INSERT INTO TB_BANGCONG(MABC,MANV,NAM,THANG,NGAY,GIOVAO,PHUTVAO,GIORA,PHUTRA,THOIDIEM_VAO,THOIDIEM_RA,NGUON_CHAM,MA_SU_KIEN_NGUON,MA_THIET_BI,TIEPNHAN_LUC,NGUON_REV)
  VALUES(punchid,emp,2026,EXTRACT(MONTH FROM daydate),EXTRACT(DAY FROM daydate),TO_NUMBER(TO_CHAR(tin,'HH24')),TO_NUMBER(TO_CHAR(tin,'MI')),
   TO_NUMBER(TO_CHAR(tout,'HH24')),TO_NUMBER(TO_CHAR(tout,'MI')),CASE WHEN tout<=tin THEN NULL ELSE tin END,CASE WHEN tout<=tin THEN NULL ELSE tout END,'SIMULATION','PAIR_'||punchid,'UAT_DEVICE',SYSTIMESTAMP,1);
  IF tin IS NOT NULL THEN INSERT INTO TB_CHAMCONG_SUKIEN(MANV,THOIDIEM,LOAI,NGUON,MA_SU_KIEN,THIET_BI,MABC) VALUES(emp,tin,'IN','UAT','IN_'||punchid,'UAT_DEVICE',punchid); END IF;
  IF tout IS NOT NULL THEN INSERT INTO TB_CHAMCONG_SUKIEN(MANV,THOIDIEM,LOAI,NGUON,MA_SU_KIEN,THIET_BI,MABC) VALUES(emp,tout,'OUT','UAT','OUT_'||punchid,'UAT_DEVICE',punchid); END IF;
 END;
 PROCEDURE leave_req(emp NUMBER, a DATE, b DATE, kind VARCHAR2, payer VARCHAR2, seconds NUMBER) IS BEGIN
  reqid:=reqid+1;
  INSERT INTO TB_YEUCAU_NGHIPHEP(ID,MANV,LOAIPHEP,TUNGAY,DENNGAY,SONGAY,LYDO,TRANGTHAI,NGUOIDUYET,NGAYDUYET,BATDAU_NGHI,KETTHUC_NGHI,GIAY_NGHI,NGUON_CHI_TRA,LOAI_HUONG_CONG)
  VALUES(reqid,emp,kind,TRUNC(a),TRUNC(b),seconds/28800,'UAT synthetic absence','APPROVED',1,a-1,a,b,seconds,payer,kind);
  IF kind='PHEP_NAM' THEN INSERT INTO TB_PHEP_SOPHATSINH(MANV,NGAY,LOAI,GIAY_PHEP,IDDON,LY_DO) VALUES(emp,TRUNC(a),'SU_DUNG',-seconds,reqid,'UAT approved leave'); END IF;
 END;
 PROCEDURE ot_req(emp NUMBER, a DATE, b DATE, seconds NUMBER, status VARCHAR2) IS BEGIN
  reqid:=reqid+1;
  INSERT INTO TB_YEUCAU_TANGCA(ID,MANV,NGAY,GIOTANGCA,IDCA,LYDO,TRANGTHAI,NGUOIDUYET,NGAYDUYET,BATDAU_DANGKY,KETTHUC_DANGKY,BATDAU_DUYET,KETTHUC_DUYET,GIAY_OT_DUYET)
  VALUES(reqid,emp,TRUNC(a),seconds/3600,1,'UAT synthetic OT',status,CASE WHEN status='APPROVED' THEN 1 END,
   CASE WHEN status='APPROVED' THEN a-1 END,a,b,CASE WHEN status='APPROVED' THEN a END,CASE WHEN status='APPROVED' THEN b END,CASE WHEN status='APPROVED' THEN seconds END);
 END;
 PROCEDURE scenario(code VARCHAR2, emp NUMBER, daydate DATE, description NVARCHAR2, cong NUMBER, ot NUMBER, ready NUMBER, err VARCHAR2 DEFAULT NULL) IS BEGIN
  INSERT INTO TB_UAT_SCENARIO(MA,MANV,NGAY,MO_TA,EXPECT_CONG,EXPECT_OT_GIAY,EXPECT_READY,EXPECT_ERROR)
  VALUES(code,emp,daydate,description,cong,ot,ready,err);
 END;
BEGIN
 IF USER<>'HR_UAT_200' THEN RAISE_APPLICATION_ERROR(-20000,'UAT owner required'); END IF;
 SELECT COUNT(*) INTO n FROM TB_NHANVIEN;
 IF n<>0 THEN RAISE_APPLICATION_ERROR(-20001,'Fixture requires empty employee data; no automatic deletion'); END IF;
 INSERT INTO TB_CONGTY(IDCTY,TENCTY,EMAILCTY,DIACHICTY) VALUES(1,'UAT - Cong ty gia lap','hr@example.invalid','DU LIEU GIA LAP - KHONG CHI TRA');
 INSERT INTO TB_SYS_USER(IDUSER,USERNAME,FULLNAME,DISABLED,ISGROUP,TOKEN_VERSION) VALUES(1,'uat_operator','UAT operator - disabled login',1,0,0);
 FOR i IN 1..8 LOOP
  INSERT INTO TB_PHONGBAN(IDPB,TENPB) VALUES(i,'UAT Phong '||i);
 END LOOP;
 INSERT INTO TB_BOPHAN(IDBP,TENBP) VALUES(1,'UAT Van phong');
 INSERT INTO TB_BOPHAN(IDBP,TENBP) VALUES(2,'UAT Van hanh');
 INSERT INTO TB_CHUCVU(IDCV,TENCV) VALUES(1,'UAT Nhan vien');
 INSERT INTO TB_CHUCVU(IDCV,TENCV) VALUES(2,'UAT Quan ly');
 INSERT INTO TB_GIOITINH(IDGT,TENGT) VALUES(1,'Nam');
 INSERT INTO TB_GIOITINH(IDGT,TENGT) VALUES(2,'Nu');
 INSERT INTO TB_LOAIHOPDONG(LOAIHD,TENLOAIHD) VALUES(1,'UAT Thu viec');
 INSERT INTO TB_LOAIHOPDONG(LOAIHD,TENLOAIHD) VALUES(2,'UAT Xac dinh thoi han');
 INSERT INTO TB_LOAIHOPDONG(LOAIHD,TENLOAIHD) VALUES(3,'UAT Khong xac dinh thoi han');
 INSERT INTO TB_LOAICONG(IDLOAICONG,TENLC,HESOLOAICONG) VALUES(1,'Ngay thuong',1);
 INSERT INTO TB_LOAICONG(IDLOAICONG,TENLC,HESOLOAICONG) VALUES(2,'Nghi tuan',1);
 INSERT INTO TB_LOAICONG(IDLOAICONG,TENLC,HESOLOAICONG) VALUES(3,'Ngay le',1);
 INSERT INTO TB_LOAICA(IDLOAICA,TENLOAICA,HESOLOAICA) VALUES(1,'Ca ngay',1);
 INSERT INTO TB_LOAICA(IDLOAICA,TENLOAICA,HESOLOAICA) VALUES(2,'Ca chieu',1);
 FOR c IN 3..6 LOOP INSERT INTO TB_LOAICA(IDLOAICA,TENLOAICA,HESOLOAICA) VALUES(c,'UAT ca '||c,1); END LOOP;
 INSERT INTO TB_PHUCAP(IDPC,TENPC) VALUES(1,'UAT Trach nhiem');
 INSERT INTO TB_PHUCAP(IDPC,TENPC) VALUES(2,'UAT Ho tro co dinh');
 INSERT INTO TB_CHINH_SACH_LUONG(ID,MA_CHINH_SACH,TEN_CHINH_SACH,NGAY_HIEU_LUC,SO_CONG_CHUAN_THANG,SO_GIO_CHUAN_NGAY,HE_SO_LAM_DEM,TRANG_THAI)
 VALUES(1,'UAT_LUONG','Fixture only - not a certified legal policy',DATE '2026-01-01',26,8,0.3,'ACTIVE');
 INSERT INTO TB_CHINH_SACH_BHXH(ID,MA_CHINH_SACH,TEN_CHINH_SACH,NGAY_HIEU_LUC,MUC_THAM_CHIEU,TY_LE_BHXH_NLD,TY_LE_BHYT_NLD,TY_LE_BHTN_NLD,TY_LE_BHXH_NSDLD,TY_LE_BHYT_NSDLD,TY_LE_BHTN_NSDLD,TY_LE_TNLD_BNN_NSDLD,TY_LE_TNLD_BNN_UU_DAI,AP_DUNG_TRAN_BHXH_BHYT,AP_DUNG_TRAN_BHTN,TRANG_THAI)
 VALUES(1,'UAT_BH','Synthetic fixture policy',DATE '2026-01-01',2340000,0.08,0.015,0.01,0.17,0.03,0.01,0.005,0.003,1,1,'ACTIVE');
 FOR i IN 1..4 LOOP
  INSERT INTO TB_CHINH_SACH_BHXH_VUNG(ID,POLICY_BHXH_ID,VUNG_LUONG,LUONG_TOI_THIEU_THANG,LUONG_TOI_THIEU_GIO,HE_SO_SAN_DOANH_NGHIEP)
  VALUES(i,1,i,6000000-i*400000,30000-i*2000,1);
 END LOOP;
 INSERT INTO TB_CHINH_SACH_CONG_DOAN(ID,MA_CHINH_SACH,TEN_CHINH_SACH,NGAY_HIEU_LUC) VALUES(1,'UAT_CD','Synthetic fixture policy',DATE '2026-01-01');
 INSERT INTO TB_THUE_TNCN_CHINH_SACH(ID,MA_CHINH_SACH,TEN_CHINH_SACH,TAX_YEAR,NGAY_HIEU_LUC) VALUES(1,'UAT_THUE','Synthetic fixture policy',2026,DATE '2026-01-01');
 -- Deliberately illustrative brackets: test data, not a legal-rate declaration.
 FOR i IN 1..5 LOOP
  INSERT INTO TB_THUE_TNCN_BAC(ID,POLICY_THUE_ID,TAX_YEAR,PERIOD_TYPE,BAC_THUE,CAN_DUOI,CAN_TREN,THUE_SUAT)
  VALUES(i,1,2026,'MONTH',i,(i-1)*10000000,CASE WHEN i<5 THEN i*10000000 END,i*0.05);
  INSERT INTO TB_THUE_TNCN_BAC(ID,POLICY_THUE_ID,TAX_YEAR,PERIOD_TYPE,BAC_THUE,CAN_DUOI,CAN_TREN,THUE_SUAT)
  VALUES(10+i,1,2026,'YEAR',i,(i-1)*120000000,CASE WHEN i<5 THEN i*120000000 END,i*0.05);
 END LOOP;
 FOR i IN 1..6 LOOP
  INSERT INTO TB_CA_PHIENBAN(IDCAPHIENBAN,IDLOAICA,SO_PHIENBAN,TEN_PHIENBAN,TU_NGAY,TONG_GIAY_CHUAN,CONG_QUY_DOI,TRANG_THAI,TAO_BOI)
  VALUES(i,i,1,'UAT ca '||i,DATE '2026-01-01',CASE WHEN i=5 THEN 14400 ELSE 28800 END,CASE WHEN i=5 THEN 0.5 ELSE 1 END,'PUBLISHED',1);
 END LOOP;
 frame(1,1,480,720,'LAM_VIEC');frame(1,2,720,780,'NGHI_KHONG_LUONG');frame(1,3,780,1020,'LAM_VIEC');
 frame(2,1,840,1080,'LAM_VIEC');frame(2,2,1080,1140,'NGHI_KHONG_LUONG');frame(2,3,1140,1380,'LAM_VIEC');
 frame(3,1,1320,1800,'LAM_VIEC');
 frame(4,1,480,720,'LAM_VIEC');frame(4,2,720,960,'NGHI_KHONG_LUONG');frame(4,3,960,1200,'LAM_VIEC');
 frame(5,1,480,720,'LAM_VIEC');
 frame(6,1,480,720,'LAM_VIEC');frame(6,2,720,780,'NGHI_KHONG_LUONG');frame(6,3,780,1020,'LAM_VIEC');
 INSERT INTO TB_QUYDINH_CHAMCONG(IDQUYDINH,MA_QUYDINH,SO_PHIENBAN,TEN_QUYDINH,TU_NGAY,GIAY_MIEN_VIPHAM_MUON,GIAY_MIEN_VIPHAM_SOM,GIAY_DUNG_SAI_HUONG_CONG,CACH_HUONG_DUNG_SAI,CACH_DEM_MUON,GIOI_HAN_GHEP_GIAY,TRANG_THAI,TAO_BOI)
 VALUES(1,'UAT_QD',1,'UAT 5 minute grace',DATE '2026-01-01',300,300,300,'DU_CONG_NEU_TRONG_NGUONG','PHAN_VUOT_NGUONG',57600,'PUBLISHED',1);
 INSERT INTO TB_NGAYLE(IDLE,TENLE,NGAY,NAM,HESO) VALUES(1,'UAT ngay nghi huong luong',DATE '2026-09-02',2026,1);
 FOR m IN 7..9 LOOP
  INSERT INTO TB_KYCONG(MAKYCONG,THANG,NAM,KHOA,TRANGTHAI,IDCTY,NGAYCONGTRONGTHANG,CONG_INPUT_REV,CONG_PUBLISH_REV) VALUES(202600+m,m,2026,0,1,1,26,1,0);
 END LOOP;
 FOR i IN 1..200 LOOP
  starts:=CASE WHEN i>=195 THEN DATE '2026-09-15' ELSE DATE '2026-01-01' END;
  ends:=CASE WHEN i BETWEEN 190 AND 194 THEN DATE '2026-09-15' ELSE DATE '2027-12-31' END;
  salary:=8000000+MOD(i,15)*1500000;
  INSERT INTO TB_NHANVIEN(MANV,HOTEN,EMPLOYEE_CODE,IDGT,NGAYSINH,DIACHI,IDPB,IDBP,IDCV,IDCTY,DATHOIVIEC,CREATED_BY,CREATED_DATE)
  VALUES(i,'Nhan vien gia lap '||LPAD(i,3,'0'),'UAT'||LPAD(i,4,'0'),MOD(i,2)+1,ADD_MONTHS(DATE '1990-01-01',MOD(i,120)),'UAT synthetic profile',MOD(i-1,8)+1,CASE WHEN i<=100 THEN 1 ELSE 2 END,CASE WHEN MOD(i,25)=0 THEN 2 ELSE 1 END,1,CASE WHEN i BETWEEN 190 AND 194 THEN 1 ELSE 0 END,1,starts);
  INSERT INTO TB_HOPDONG(SOHD,MANV,IDCTY,LOAIHD,NGAYBATDAU,NGAYKETTHUC,NGAYKY,HESOLUONG,LUONG_THOA_THUAN)
  VALUES('UAT-HD-'||LPAD(i,4,'0'),i,1,CASE WHEN i>=195 THEN 1 ELSE 2 END,starts,ends,starts,1,salary);
  INSERT INTO TB_LUONG_HIEULUC(MANV,SOHD,TU_NGAY,DEN_NGAY,LUONG_THANG,CAN_CU) VALUES(i,'UAT-HD-'||LPAD(i,4,'0'),starts,ends+1,salary,'UAT initial salary');
  INSERT INTO TB_BAOHIEM(IDBH,MANV,SOBH,NGAYCAP,NOICAP,NOIKHAMBENH,LUONG_BHXH) VALUES(i,i,'UAT-BH-'||LPAD(i,4,'0'),starts,'UAT','UAT clinic',salary);
  INSERT INTO TB_NHANVIEN_BAOHIEM_THAM_GIA(ID,MANV,VUNG_LUONG,THAM_GIA_BHXH,THAM_GIA_BHYT,THAM_GIA_BHTN,THAM_GIA_TNLD_BNN,HUONG_TY_LE_TNLD_UU_DAI,LUONG_DONG_BHXH_RIENG,NGAY_BAT_DAU,NGAY_KET_THUC,TRANG_THAI)
  VALUES(i,i,1,CASE WHEN i>=195 THEN 0 ELSE 1 END,CASE WHEN i>=195 THEN 0 ELSE 1 END,CASE WHEN i>=195 THEN 0 ELSE 1 END,CASE WHEN i>=195 THEN 0 ELSE 1 END,0,salary,starts,ends,'ACTIVE');
  INSERT INTO TB_NHANVIEN_CONG_DOAN_THAM_GIA(ID,MANV,LA_DOAN_VIEN,NGAY_GIA_NHAP,NGAY_KET_THUC,TRANG_THAI) VALUES(i,i,CASE WHEN MOD(i,4)=0 THEN 0 ELSE 1 END,starts,ends,'ACTIVE');
  INSERT INTO TB_NHANVIEN_THUE(ID,MANV,MA_SO_THUE,IS_CU_TRU,CO_UY_QUYEN_QUYET_TOAN,NGAY_HIEU_LUC,NGAY_HET_HIEU_LUC,TRANG_THAI)
  VALUES(i,i,'UAT-TAX-'||LPAD(i,4,'0'),1,1,starts,ends,'ACTIVE');
  IF MOD(i,3)=0 THEN INSERT INTO TB_NGUOI_PHU_THUOC(ID,MANV,HO_TEN,MOI_QUAN_HE,NGAY_SINH,THANG_BAT_DAU_GIAM_TRU,TRANG_THAI)
   VALUES(i,i,'Nguoi phu thuoc gia lap '||i,'CON',DATE '2018-01-01',202607,'ACTIVE'); END IF;
  IF i BETWEEN 190 AND 194 THEN
   INSERT INTO TB_NHANVIEN_THOIVIEC(SOQDTV,MANV,NGAYNOPDON,NGAYNGHIVIEC,LYDOTV,GHICHUTV,CREATED_BY,CREATED_DATE)
   VALUES('UAT-TV-'||i,i,DATE '2026-09-01',DATE '2026-09-16','Synthetic contract end','Last working date 2026-09-15',1,DATE '2026-09-01');
  END IF;
  INSERT INTO TB_NHANVIEN_PHUCAP(MANV,IDPC,SOTIEN,TU_NGAY,DEN_NGAY,CACH_TINH) VALUES(i,1,CASE WHEN MOD(i,25)=0 THEN 1500000 ELSE 300000 END,starts,ends+1,'CO_DINH_THANG');
  INSERT INTO TB_PHEP_SOPHATSINH(MANV,NGAY,LOAI,GIAY_PHEP,LY_DO) VALUES(i,starts,'CAP',12*28800,'UAT opening allocation');
  IF MOD(i,20)=0 THEN INSERT INTO TB_UNGLUONG(IDUL,MANV,NAM,THANG,NGAY,SOTIENUNG,GHICHU) VALUES(i,i,2026,9,15,1000000,'UAT advance'); END IF;
  IF MOD(i,25)=0 THEN INSERT INTO TB_KHENTHUONG_KYLUAT(SOQUYETDINH,MANV,LOAI,SOTIEN,NGAY,THANG_APDUNG,NAM_APDUNG,LYDO)
   VALUES('UAT-KT-'||i,i,1,500000,DATE '2026-09-20',9,2026,'UAT reward'); END IF;
  IF i>=190 THEN INSERT INTO TB_BAOHIEM_BIENDONG(MANV,MAKYCONG,LOAI,NGAY_HIEULUC,LY_DO,TRANG_THAI,NGUOI_DUYET)
   VALUES(i,202609,CASE WHEN i>=195 THEN 'TANG' ELSE 'GIAM' END,DATE '2026-09-15','UAT employment event','DRAFT',NULL); END IF;
  FOR m IN 7..9 LOOP
   mk:=202600+m;
   INSERT INTO TB_KYCONGCHITIET(MAKYCONG,MANV,HOTEN,IDCTY,TONGNGAYCONG) VALUES(mk,i,'Nhan vien gia lap '||LPAD(i,3,'0'),1,NULL);
   d:=ADD_MONTHS(DATE '2026-01-01',m-1);
   WHILE d<ADD_MONTHS(ADD_MONTHS(DATE '2026-01-01',m-1),1) LOOP
    dayid:=dayid+1;
    INSERT INTO TB_BANGCONG_CHITIET(IDBANGCONGCT,MAKYCONG,MANV,NGAY,THU,KYHIEU,NGAYCONG,CREATED_BY) VALUES(dayid,mk,i,d,TO_CHAR(d,'DY','NLS_DATE_LANGUAGE=ENGLISH'),'?',NULL,1);
    sid:=CASE WHEN i<=100 THEN 1 WHEN i<=140 THEN CASE WHEN MOD(TRUNC(d,'IW')-DATE '2026-01-05',14)=0 THEN 1 ELSE 2 END WHEN i<=160 THEN 3 WHEN i<=180 THEN 4 WHEN i<=190 THEN 5 ELSE 6 END;
    mins:=CASE sid WHEN 2 THEN 840 WHEN 3 THEN 1320 ELSE 480 END;
    endmins:=CASE sid WHEN 2 THEN 1380 WHEN 3 THEN 1800 WHEN 4 THEN 1200 WHEN 5 THEN 720 ELSE 1020 END;
    isrest:=(d-TRUNC(d,'IW')=6 OR d<starts OR d>ends);
    IF isrest THEN restflag:=1; ELSE restflag:=0; END IF;
    IF NOT(i=9 AND d=DATE '2026-09-21') THEN
     lid:=lid+1;
     INSERT INTO TB_LICH_LAMVIEC(IDLICH,MANV,NGAY,MA_PHANCONG,SO_PHIENBAN,IDCAPHIENBAN,IDQUYDINH,BATDAU_KEHOACH,KETTHUC_KEHOACH,TRANG_THAI_PHAN_CONG,LOAI_NGAY,TRANG_THAI,NGUON_PHAN_CONG,TAO_BOI)
     VALUES(lid,i,d,'UAT-'||i||'-'||TO_CHAR(d,'YYYYMMDD'),1,CASE WHEN restflag=0 THEN sid END,1,CASE WHEN restflag=0 THEN d+mins/1440 END,CASE WHEN restflag=0 THEN d+endmins/1440 END,CASE WHEN restflag=1 THEN 'NGHI' ELSE 'LAM_VIEC' END,CASE WHEN d=DATE '2026-09-02' THEN 'LE' WHEN restflag=1 THEN 'NGHI_TUAN' ELSE 'THUONG' END,'PUBLISHED','UAT',1);
    END IF;
    IF NOT isrest THEN
     dtin:=d+mins/1440;dtout:=d+endmins/1440;
     IF d=DATE '2026-09-02' THEN
      leave_req(i,dtin,dtout,'NGHI_HUONG_LUONG','CONG_TY',CASE WHEN sid=5 THEN 14400 ELSE 28800 END);
     ELSIF i=11 AND d BETWEEN DATE '2026-09-21' AND DATE '2026-09-23' THEN
      IF d=DATE '2026-09-21' THEN leave_req(i,d+8/24,d+2+17/24,'PHEP_NAM','CONG_TY',86400); END IF;
     ELSIF d=DATE '2026-09-21' AND i IN(2,12,13,17) THEN
      IF i=2 THEN leave_req(i,dtin,dtout,'PHEP_NAM','CONG_TY',28800);
      ELSIF i=12 THEN leave_req(i,dtin,dtout,'NGHI_BHXH','BHXH',28800);
      ELSIF i=13 THEN leave_req(i,dtin,dtout,'KHONG_LUONG','KHONG_CHI_TRA',28800);
      ELSE leave_req(i,dtin,dtin+1/24,'PHEP_NAM','CONG_TY',3600); END IF;
     ELSE
      IF d=DATE '2026-09-21' THEN
       IF i=3 THEN leave_req(i,d+8/24,d+12/24,'PHEP_NAM','CONG_TY',14400);dtin:=d+13/24; END IF;
       IF i=4 THEN dtin:=d+8/24+20/1440; END IF;
       IF i=5 THEN dtout:=NULL; END IF;
       IF i IN(6,7) THEN dtout:=d+21/24; END IF;
       IF i=7 THEN ot_req(i,d+17.5/24,d+20/24,9000,'APPROVED'); END IF;
       IF i=8 THEN dtout:=d+19/24;ot_req(i,d+17/24,d+19/24,3600,'APPROVED'); END IF;
       IF i=10 THEN dtout:=d+19/24;ot_req(i,d+17/24,d+19/24,7200,'APPROVED'); END IF;
       IF i=18 THEN dtin:=d+17/24;dtout:=d+8/24; END IF;
       IF i=19 THEN dtin:=d+7.5/24; END IF;
       IF i=20 THEN dtin:=d+8/24+4/1440; END IF;
      END IF;
      IF sid=4 THEN punch(i,d,d+8/24,d+12/24);punch(i,d,d+16/24,d+20/24);
      ELSE punch(i,d,dtin,dtout); END IF;
     END IF;
    END IF;
    d:=d+1;
   END LOOP;
  END LOOP;
 END LOOP;
 ot_req(21,DATE '2026-09-21'+17/24,DATE '2026-09-21'+19/24,7200,'PENDING');
 ot_req(22,DATE '2026-09-21'+17/24,DATE '2026-09-21'+19/24,7200,'REJECTED');
 INSERT INTO TB_YEUCAU_DIEUCHINHCONG(ID,MANV,NGAY,LOAIDIEUCHINH,LYDO,TRANGTHAI,THOIDIEM_VAO_MOI,THOIDIEM_RA_MOI)
 VALUES(1,5,DATE '2026-09-21','BO_SUNG_GIO_RA','UAT missing out punch','PENDING',DATE '2026-09-21'+8/24,DATE '2026-09-21'+17/24);
 scenario('STANDARD',1,DATE '2026-09-21','Standard eight hours',1,0,1);
 scenario('PAID_LEAVE',2,DATE '2026-09-21','Full paid leave',1,0,1);
 scenario('MORNING_LEAVE',3,DATE '2026-09-21','Morning leave afternoon work',1,0,1);
 scenario('LATE_20',4,DATE '2026-09-21','Late 20m grace 5m excess-only',0.9583,0,1);
 scenario('MISSING_OUT',5,DATE '2026-09-21','Missing out must block',0,0,0,'THIEU_GIO_RA');
 scenario('OUT_21_NO_OT',6,DATE '2026-09-21','After shift without approved OT',1,0,0,'OT_CHUA_DUYET');
 scenario('PART_APPROVED_OT',7,DATE '2026-09-21','2.5h approved plus pending excess',1,9000,0,'OT_CHUA_DUYET');
 scenario('OT_CAP',8,DATE '2026-09-21','Two hours present one hour approved',1,3600,0,'OT_VUOT_GIAY_DUYET');
 scenario('NO_SCHEDULE',9,DATE '2026-09-21','Punch without schedule',0,0,0,'THIEU_CAU_HINH');
 scenario('APPROVED_OT',10,DATE '2026-09-21','Two approved hours',1,7200,1);
 scenario('MULTIDAY_LEAVE',11,DATE '2026-09-22','Second day of three-day leave',1,0,1);
 scenario('BHXH_LEAVE',12,DATE '2026-09-21','Social insurance payer not employer wage',0,0,1);
 scenario('UNPAID_LEAVE',13,DATE '2026-09-21','Approved unpaid leave',0,0,1);
 scenario('PARTIAL_ABSENCE',17,DATE '2026-09-21','One hour leave seven hours unresolved',0.125,0,0);
 scenario('REVERSED_PUNCH',18,DATE '2026-09-21','Invalid punch pair preserved',0,0,0,'GIO_DAO_NGUOC');
 scenario('EARLY_NOT_PAID',19,DATE '2026-09-21','Early presence not extra credit',1,0,1);
 scenario('GRACE_4',20,DATE '2026-09-21','Four minutes within credit grace',1,0,1);
 scenario('NIGHT',141,DATE '2026-09-21','Night crossing midnight',1,0,1);
 scenario('SPLIT',161,DATE '2026-09-21','Two separated work blocks',1,0,1);
 scenario('SHORT',181,DATE '2026-09-21','Four-hour half day',0.5,0,1);
 scenario('PAID_HOLIDAY',1,DATE '2026-09-02','Explicit paid company leave on holiday',1,0,1);
 scenario('BEFORE_JOIN',195,DATE '2026-09-14','No entitlement before contract begins',0,0,1);
 scenario('AFTER_EXIT',190,DATE '2026-09-16','No work after contract ends',0,0,1);
 COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
