BEGIN
 IF USER<>'HR_UAT_200' THEN RAISE_APPLICATION_ERROR(-20000,'UAT owner required'); END IF;
 MERGE INTO TB_UAT_SCENARIO t USING (
  SELECT s.MA,b.NGAYCONG,b.GIAY_OT_XAC_NHAN,b.DU_DIEUKIEN_CHOT,b.IDBANGCONGCT
  FROM TB_UAT_SCENARIO s JOIN TB_BANGCONG_CHITIET b ON b.MANV=s.MANV AND b.NGAY=s.NGAY
 ) x ON (t.MA=x.MA)
 WHEN MATCHED THEN UPDATE SET t.ACTUAL_CONG=x.NGAYCONG,t.ACTUAL_OT_GIAY=x.GIAY_OT_XAC_NHAN,
  t.ACTUAL_READY=x.DU_DIEUKIEN_CHOT,
  t.KET_QUA=CASE WHEN ABS(t.EXPECT_CONG-x.NGAYCONG)<0.00001
    AND t.EXPECT_OT_GIAY=x.GIAY_OT_XAC_NHAN AND t.EXPECT_READY=x.DU_DIEUKIEN_CHOT
    THEN 'PASS' ELSE 'FAIL' END;
 UPDATE TB_UAT_SCENARIO s SET KET_QUA='FAIL'
 WHERE EXPECT_ERROR IS NOT NULL AND NOT EXISTS (
  SELECT 1 FROM TB_CHAMCONG_BATTHUONG b WHERE b.MANV=s.MANV AND b.NGAY=s.NGAY AND b.MA_LOI=s.EXPECT_ERROR);
 COMMIT;
END;
/
