WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON ECHO OFF
DECLARE
 h NUMBER; n NUMBER; state VARCHAR2(30);
BEGIN
 SELECT COUNT(*) INTO n FROM DBA_USERS WHERE USERNAME='HR_RESTORE_200';
 IF n<>0 THEN RAISE_APPLICATION_ERROR(-20000,'Restore verification schema already exists'); END IF;
 EXECUTE IMMEDIATE 'CREATE USER HR_RESTORE_200 NO AUTHENTICATION DEFAULT TABLESPACE USERS QUOTA 2G ON USERS ACCOUNT LOCK';
 h:=DBMS_DATAPUMP.OPEN('IMPORT','SCHEMA',job_name=>'HR_200_RESTORE_VERIFY');
 DBMS_DATAPUMP.ADD_FILE(h,'HR_before_synthetic200_20260928.dmp','DATA_PUMP_DIR');
 DBMS_DATAPUMP.ADD_FILE(h,'HR_200_restore_verify.log','DATA_PUMP_DIR',filetype=>DBMS_DATAPUMP.KU$_FILE_TYPE_LOG_FILE);
 DBMS_DATAPUMP.METADATA_FILTER(h,'SCHEMA_EXPR','= ''HR''');
 DBMS_DATAPUMP.METADATA_REMAP(h,'REMAP_SCHEMA','HR','HR_RESTORE_200');
 DBMS_DATAPUMP.METADATA_FILTER(h,'EXCLUDE_PATH_EXPR','IN (''USER'',''GRANT'',''PROCEDURE'',''TRIGGER'',''STATISTICS'')');
 DBMS_DATAPUMP.START_JOB(h);
 DBMS_DATAPUMP.WAIT_FOR_JOB(h,state);
 DBMS_OUTPUT.PUT_LINE('RESTORE_STATE='||state);
 IF state<>'COMPLETED' THEN RAISE_APPLICATION_ERROR(-20001,'Restore verification incomplete'); END IF;
END;
/
SELECT COUNT(*) ORIGINAL_EMPLOYEES FROM HR_RESTORE_200.TB_NHANVIEN;
EXIT
