using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Bu.Services.AI_Services;
using QLyNSu.Functions;

namespace QLyNSu.FORM_SYSTEM
{
    public partial class FrmAI_Chat : DevExpress.XtraEditors.XtraForm
    {
        private readonly ChatboxManager _manager;

        public FrmAI_Chat()
        {
            InitializeComponent();
            _manager = new ChatboxManager();
        }

        private void FrmAI_Chat_Load(object sender, EventArgs e)
        {
            // Format data grid
            FormManager_Functions.CustomView_Colums(gvData);
            
            // Clear SQL view initially
            memSqlView.Text = "-- SQL generated by AI will be displayed here --";
            
            // Initial greeting
            ResetChatUI();
        }

        private void ResetChatUI()
        {
            flpChat.Controls.Clear();
            _manager.Reset();
            memSqlView.Text = "-- SQL generated by AI will be displayed here --";
            gcData.DataSource = null;

            AddMessageBubble("AI", "Xin chào! Tôi là Trợ lý AI Quản trị Nhân sự. Tôi có thể giúp gì cho bạn hôm nay?\n\nBạn có thể hỏi bất kỳ câu hỏi nghiệp vụ nào bằng tiếng Việt tự nhiên (ví dụ: 'Danh sách nhân viên sinh nhật tháng này', 'Ai chuẩn bị lên lương', 'Thống kê nhân sự theo phòng ban').");
        }

        private async void btnChatSend_Click(object sender, EventArgs e)
        {
            string query = txtChatInput.Text.Trim();
            if (string.IsNullOrEmpty(query)) return;

            // Display user message bubble
            AddMessageBubble("You", query);
            txtChatInput.Text = string.Empty;

            // Lock UI during AI execution
            txtChatInput.Enabled = false;
            btnChatSend.Enabled = false;
            btnClearChat.Enabled = false;
            
            // Temporary AI thinking bubble
            var thinkingBubble = AddThinkingBubble();

            try
            {
                // Process query via business logic layer
                var result = await _manager.ProcessQuery(query);

                // Remove thinking indicator
                flpChat.Controls.Remove(thinkingBubble);

                // Display AI response
                AddMessageBubble("AI", result.Answer);

                // Update database insight panel
                if (!string.IsNullOrEmpty(result.SqlQuery) && result.SqlQuery != "NOT_SQL")
                {
                    memSqlView.Text = FormatSql(result.SqlQuery);
                    if (result.Data != null)
                    {
                        gcData.DataSource = result.Data;
                        gvData.BestFitColumns();
                    }
                    else
                    {
                        gcData.DataSource = null;
                    }
                }
                else
                {
                    memSqlView.Text = "-- No database query executed --";
                    gcData.DataSource = null;
                }
            }
            catch (Exception ex)
            {
                // Remove thinking indicator in case of error
                if (flpChat.Controls.Contains(thinkingBubble))
                {
                    flpChat.Controls.Remove(thinkingBubble);
                }
                AddMessageBubble("AI", "Rất tiếc! Đã xảy ra lỗi khi kết nối và xử lý yêu cầu của bạn: " + ex.Message);
            }
            finally
            {
                txtChatInput.Enabled = true;
                btnChatSend.Enabled = true;
                btnClearChat.Enabled = true;
                txtChatInput.Focus();
            }
        }

        private void txtChatInput_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Enter)
            {
                btnChatSend_Click(sender, EventArgs.Empty);
            }
        }

        private void btnClearChat_Click(object sender, EventArgs e)
        {
            ResetChatUI();
        }

        private async void btnOpenDashboard_Click(object sender, EventArgs e)
        {
            var formManager = new FormManager_Functions(this.MdiParent ?? this);
            await formManager.OpenFormWithSplashScreen(typeof(FrmAI));
        }

        private void QuickAction_Click(object sender, EventArgs e)
        {
            if (sender is SimpleButton btn)
            {
                string prompt = "";
                switch (btn.Name)
                {
                    case "btnActionBirthday":
                        prompt = "Ai sinh nhật trong tháng này?";
                        break;
                    case "btnActionSalary":
                        prompt = "Danh sách nhân viên chuẩn bị tăng lương?";
                        break;
                    case "btnActionEmployee":
                        prompt = "Danh sách tất cả nhân viên trong công ty?";
                        break;
                    case "btnActionDepartment":
                        prompt = "Thống kê số lượng nhân viên theo từng phòng ban?";
                        break;
                }

                if (!string.IsNullOrEmpty(prompt))
                {
                    txtChatInput.Text = prompt;
                    btnChatSend_Click(sender, EventArgs.Empty);
                }
            }
        }

        private void flpChat_SizeChanged(object sender, EventArgs e)
        {
            flpChat.SuspendLayout();
            foreach (Control ctrl in flpChat.Controls)
            {
                if (ctrl is Panel container)
                {
                    container.Width = flpChat.ClientSize.Width - 30;
                }
            }
            flpChat.ResumeLayout();
        }

        // ================= HELPER METHODS FOR CHAT BUBBLES =================

        private void AddMessageBubble(string sender, string message)
        {
            bool isUser = sender.Equals("You", StringComparison.OrdinalIgnoreCase);

            var container = new Panel
            {
                Width = flpChat.ClientSize.Width - 30,
                Height = 50,
                Padding = new Padding(5)
            };

            // Format message content
            string htmlContent = $"<b>{(isUser ? "BẠN" : "TRỢ LÝ AI")}</b> <font color='gray' size='-1'>{DateTime.Now.ToString("HH:mm")}</font><br/>{message.Replace("\n", "<br/>")}";

            var lblMsg = new LabelControl
            {
                Text = htmlContent,
                AllowHtmlString = true,
                AutoSizeMode = LabelAutoSizeMode.Vertical,
                Width = (int)(container.Width * 0.82)
            };

            lblMsg.Appearance.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            lblMsg.Appearance.Font = new Font("Segoe UI", 10F);
            lblMsg.Padding = new Padding(12);

            // Style and align bubble
            if (isUser)
            {
                lblMsg.Appearance.BackColor = Color.FromArgb(220, 235, 252); // Soft blue
                lblMsg.Appearance.ForeColor = Color.FromArgb(15, 23, 42);
                lblMsg.Location = new Point(container.Width - lblMsg.Width - 10, 5);
                lblMsg.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            }
            else
            {
                lblMsg.Appearance.BackColor = Color.FromArgb(241, 245, 249); // Soft gray
                lblMsg.Appearance.ForeColor = Color.FromArgb(15, 23, 42);
                lblMsg.Location = new Point(10, 5);
                lblMsg.Anchor = AnchorStyles.Top | AnchorStyles.Left;
            }

            // Adjust height
            int preferredHeight = lblMsg.GetPreferredSize(new Size(lblMsg.Width, 1000)).Height + 24;
            lblMsg.Height = preferredHeight;
            container.Height = lblMsg.Height + 10;

            container.Controls.Add(lblMsg);

            flpChat.Controls.Add(container);
            flpChat.ScrollControlIntoView(container);
        }

        private Panel AddThinkingBubble()
        {
            var container = new Panel
            {
                Width = flpChat.ClientSize.Width - 30,
                Height = 50,
                Padding = new Padding(5)
            };

            var lblMsg = new LabelControl
            {
                Text = "<i>AI đang phân tích và truy vấn dữ liệu...</i>",
                AllowHtmlString = true,
                AutoSizeMode = LabelAutoSizeMode.Vertical,
                Width = 250
            };

            lblMsg.Appearance.TextOptions.WordWrap = DevExpress.Utils.WordWrap.Wrap;
            lblMsg.Appearance.Font = new Font("Segoe UI", 9.5f);
            lblMsg.Padding = new Padding(12);
            lblMsg.Appearance.BackColor = Color.FromArgb(254, 243, 199); // Soft gold/yellow
            lblMsg.Appearance.ForeColor = Color.FromArgb(146, 64, 14);
            lblMsg.Location = new Point(10, 5);

            container.Height = lblMsg.GetPreferredSize(new Size(lblMsg.Width, 1000)).Height + 24 + 10;
            container.Controls.Add(lblMsg);

            flpChat.Controls.Add(container);
            flpChat.ScrollControlIntoView(container);

            return container;
        }

        private string FormatSql(string sql)
        {
            if (string.IsNullOrEmpty(sql)) return "";
            // Clean up basic string formatting
            return sql.Replace("SELECT", "SELECT\n   ")
                      .Replace("FROM", "\nFROM\n   ")
                      .Replace("LEFT JOIN", "\nLEFT JOIN\n   ")
                      .Replace("WHERE", "\nWHERE\n   ")
                      .Replace("AND", "\n   AND")
                      .Replace("ORDER BY", "\nORDER BY\n   ");
        }
    }
}
