export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    CHANGE_PASSWORD: '/auth/change-password',
    LOGOUT: '/auth/logout',
    LOGOUT_ALL: '/auth/logout-all',
  },
  ME: {
    BASE: '/me',
    DASHBOARD: '/me/dashboard',
    PROFILE: '/me/profile',
    ATTENDANCE: '/me/attendance',
    PAYROLL: '/me/payroll',
    CONTRACT: '/me/contract',
    INSURANCE: '/me/insurance',
    NOTIFICATIONS: '/me/notifications',
    NOTIFICATION_DETAIL: (id: string | number) => `/me/notifications/${id}`,
    LEAVE: '/me/leave',
    ATTENDANCE_CORRECTIONS: '/me/attendance-corrections',
    OVERTIME: '/me/overtime',
    OVERTIME_DETAIL: (id: string | number) => `/me/overtime/${id}`,
    OVERTIME_CANCEL: (id: string | number) => `/me/overtime/${id}/cancel`,
    REQUESTS: '/me/requests',
    LEAVE_BALANCE: '/me/leave-balance',
  },
  APPROVALS: {
    SUMMARY: '/approvals/summary',
    LEAVE: '/approvals/leave',
    LEAVE_APPROVE: (id: string | number) => `/approvals/leave/${id}/approve`,
    LEAVE_REJECT: (id: string | number) => `/approvals/leave/${id}/reject`,
    CORRECTIONS: '/approvals/attendance-corrections',
    CORRECTIONS_APPROVE: (id: string | number) => `/approvals/attendance-corrections/${id}/approve`,
    CORRECTIONS_REJECT: (id: string | number) => `/approvals/attendance-corrections/${id}/reject`,
    OVERTIME: '/approvals/overtime',
    OVERTIME_APPROVE: (id: string | number) => `/approvals/overtime/${id}/approve`,
    OVERTIME_REJECT: (id: string | number) => `/approvals/overtime/${id}/reject`,
    INSURANCE_MOVEMENTS: '/approvals/insurance-movements',
    INSURANCE_MOVE_APPROVE: (id: string | number) => `/approvals/insurance-movements/${id}/approve`,
    INSURANCE_MOVE_REJECT: (id: string | number) => `/approvals/insurance-movements/${id}/reject`,
  },
};
