export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    CHANGE_PASSWORD: '/auth/change-password',
    LOGOUT: '/auth/logout',
    LOGOUT_ALL: '/auth/logout-all',
  },
  ME: {
    BASE: '/me',
    DASHBOARD: '/me/dashboard',
    PROFILE: '/me/profile',
    ATTENDANCE: '/me/attendance',
    PAYROLL: '/me/payroll',
    CONTRACT: '/me/contract',
    INSURANCE: '/me/insurance',
    NOTIFICATIONS: '/me/notifications',
    NOTIFICATION_DETAIL: (id: string | number) => `/me/notifications/${id}`,
    LEAVE: '/me/leave',
    ATTENDANCE_CORRECTIONS: '/me/attendance-corrections',
    OVERTIME: '/me/overtime',
    OVERTIME_DETAIL: (id: string | number) => `/me/overtime/${id}`,
    OVERTIME_CANCEL: (id: string | number) => `/me/overtime/${id}/cancel`,
    REQUESTS: '/me/requests',
  },
};
