-- ==============================================================================
-- SCRIPT KHOI TAO VA DONG BO USER AI_READONLY CHO ORACLE 21C XE (XEPDB1)
-- ==============================================================================
ALTER SESSION SET CONTAINER = XEPDB1;

-- 1. Tao user AI_READONLY neu chua co
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER AI_READONLY IDENTIFIED BY AI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1920, -955) THEN
            EXECUTE IMMEDIATE 'ALTER USER AI_READONLY IDENTIFIED BY AI ACCOUNT UNLOCK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
        ELSE
            RAISE;
        END IF;
END;
/

-- 2. Cap quyen co ban
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SESSION TO AI_READONLY;

-- 3. Cap quyen SELECT tren cac bang cua HR cho AI_READONLY
GRANT SELECT ON HR.TB_NHANVIEN TO AI_READONLY;
GRANT SELECT ON HR.TB_PHONGBAN TO AI_READONLY;
GRANT SELECT ON HR.TB_BOPHAN TO AI_READONLY;
GRANT SELECT ON HR.TB_CHUCVU TO AI_READONLY;
GRANT SELECT ON HR.TB_BANGCONG TO AI_READONLY;
GRANT SELECT ON HR.TB_TANGCA TO AI_READONLY;
GRANT SELECT ON HR.TB_BAOHIEM TO AI_READONLY;
GRANT SELECT ON HR.TB_UNGLUONG TO AI_READONLY;
GRANT SELECT ON HR.TB_NHANVIEN_PHUCAP TO AI_READONLY;
GRANT SELECT ON HR.TB_PHUCAP TO AI_READONLY;

-- 4. Tao 6 View toi uu cho AI Assistant
CREATE OR REPLACE VIEW "AI_READONLY"."V_AI_EMPLOYEE" (
    "MANV", "HOTEN", "NGAYSINH", "DIENTHOAI", "DIACHI", "TEN_PHONGBAN", "TEN_BOPHAN", "TEN_CHUCVU"
) AS
SELECT
    nv.MANV,
    nv.HOTEN,
    nv.NGAYSINH,
    nv.DIENTHOAI,
    nv.DIACHI,
    pb.TENPB AS TEN_PHONGBAN,
    bp.TENBP AS TEN_BOPHAN,
    cv.TENCV AS TEN_CHUCVU
FROM HR.TB_NHANVIEN nv
LEFT JOIN HR.TB_PHONGBAN pb ON nv.IDPB = pb.IDPB
LEFT JOIN HR.TB_BOPHAN bp ON nv.IDBP = bp.IDBP
LEFT JOIN HR.TB_CHUCVU cv ON nv.IDCV = cv.IDCV;

CREATE OR REPLACE VIEW "AI_READONLY"."V_AI_ATTENDANCE" (
    "MANV", "HOTEN", "TEN_PHONGBAN", "NGAY", "THANG", "NAM", "GIOVAO", "PHUTVAO", "GIORA", "PHUTRA", "TIME_IN", "TIME_OUT"
) AS
SELECT
    nv.MANV,
    nv.HOTEN,
    pb.TENPB AS TEN_PHONGBAN,
    bc.NGAY,
    bc.THANG,
    bc.NAM,
    bc.GIOVAO,
    bc.PHUTVAO,
    bc.GIORA,
    bc.PHUTRA,
    (bc.GIOVAO || ':' || bc.PHUTVAO) AS TIME_IN,
    (bc.GIORA || ':' || bc.PHUTRA) AS TIME_OUT
FROM HR.TB_BANGCONG bc
JOIN HR.TB_NHANVIEN nv ON bc.MANV = nv.MANV
LEFT JOIN HR.TB_PHONGBAN pb ON nv.IDPB = pb.IDPB;

CREATE OR REPLACE VIEW "AI_READONLY"."V_AI_OVERTIME" (
    "MANV", "HOTEN", "TEN_PHONGBAN", "NGAY", "THANG", "NAM", "SOGIO"
) AS
SELECT
    nv.MANV,
    nv.HOTEN,
    pb.TENPB AS TEN_PHONGBAN,
    tc.NGAY,
    tc.THANG,
    tc.NAM,
    tc.SOGIO
FROM HR.TB_TANGCA tc
JOIN HR.TB_NHANVIEN nv ON tc.MANV = nv.MANV
LEFT JOIN HR.TB_PHONGBAN pb ON nv.IDPB = pb.IDPB;

CREATE OR REPLACE VIEW "AI_READONLY"."V_AI_INSURANCE" (
    "MANV", "HOTEN", "SOBH", "NGAYCAP", "NOICAP", "NOIKHAMBENH"
) AS
SELECT
    nv.MANV,
    nv.HOTEN,
    bh.SOBH,
    bh.NGAYCAP,
    bh.NOICAP,
    bh.NOIKHAMBENH
FROM HR.TB_BAOHIEM bh
JOIN HR.TB_NHANVIEN nv ON bh.MANV = nv.MANV;

CREATE OR REPLACE VIEW "AI_READONLY"."V_AI_ADVANCE" (
    "MANV", "HOTEN", "NGAY", "THANG", "NAM", "SOTIEN"
) AS
SELECT
    nv.MANV,
    nv.HOTEN,
    ul.NGAY,
    ul.THANG,
    ul.NAM,
    ul.SOTIENUNG AS SOTIEN
FROM HR.TB_UNGLUONG ul
JOIN HR.TB_NHANVIEN nv ON ul.MANV = nv.MANV;

CREATE OR REPLACE VIEW "AI_READONLY"."V_AI_ALLOWANCE" (
    "MANV", "HOTEN", "TENPC", "SOTIEN", "KYCONG"
) AS
SELECT
    nv.MANV,
    nv.HOTEN,
    pc.TENPC,
    npc.SOTIEN,
    CAST(NVL(TO_NUMBER(TO_CHAR(npc.TU_NGAY, 'YYYYMM')), 0) AS NUMBER(38)) AS KYCONG
FROM HR.TB_NHANVIEN_PHUCAP npc
JOIN HR.TB_NHANVIEN nv ON npc.MANV = nv.MANV
LEFT JOIN HR.TB_PHUCAP pc ON npc.IDPC = pc.IDPC;

-- 5. Compile va kiem tra
EXEC DBMS_UTILITY.COMPILE_SCHEMA('AI_READONLY', COMPILE_ALL => FALSE);

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM ALL_OBJECTS WHERE OWNER = 'AI_READONLY';
EXIT;
