SET LINESIZE 200;
SELECT IDUSER, USERNAME, FULLNAME, DISABLED, ISGROUP FROM HR.TB_SYS_USER;
SELECT u.IDUSER, u.USERNAME, a.FUNCTION_CODE, a.CAN_VIEW, a.USER_RIGHT 
FROM HR.TB_SYS_USER u
JOIN HR.V_AI_SRC_AUTH a ON a.IDUSER = u.IDUSER
WHERE a.FUNCTION_CODE = 'F_SYSTEM_AI';
EXIT;
