SET LINESIZE 200;
SET PAGESIZE 50;
SELECT IDUSER, USERNAME, FULLNAME, FUNCTION_CODE, CAN_VIEW, USER_RIGHT, DISABLED, ISGROUP FROM HR.V_AI_SRC_AUTH WHERE IDUSER = 1;
SELECT DISTINCT FUNCTION_CODE FROM HR.V_AI_SRC_AUTH;
SELECT IDUSER, USERNAME FROM HR.TB_USER WHERE ROWNUM <= 10;
EXIT;
