SET LINESIZE 200;
SELECT * FROM HR.TB_SYS_USER WHERE USERNAME = 'ADMIN';
SELECT * FROM HR.TB_SYS_RIGHT WHERE IDUSER = 80 AND FUNCTION_CODE LIKE '%AI%';
SELECT * FROM HR.TB_SYS_GROUP WHERE MEMBER = 80;
EXIT;
