-- ============================================================================
-- [DEPRECATED - CANH BAO KHONG SU DUNG TRUC TIEP]
-- Script nay chua cac ID co dinh 80 (ADMIN) va 89 (Nhom ADMIN) chi ap dung cho dev cu.
-- KHONG chay script nay tren cac moi truong khac vi IDUSER/ID_GROUP cua ADMIN co the khac.
-- Vui long su dung migration dong: V1_33__seed_admin_scope_dynamic.sql
-- ============================================================================

-- Seed Scope Grants for IDUSER = 80 (ADMIN)
MERGE INTO AI_OWNER.TB_AI_SCOPE_GRANT t USING (
    SELECT 80 AS usr_id, 'USER' AS stype, 'EMPLOYEE_LOOKUP' AS cap, 'ALL' AS scope FROM DUAL UNION ALL
    SELECT 80, 'USER', 'EMPLOYEE_PROFILE', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'EMPLOYEE_COUNT', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'ATTENDANCE_SUMMARY', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'OVERTIME_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'OVERTIME_SUM', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'ALLOWANCE_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'INSURANCE_SELF', 'SELF' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'ADVANCE_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'CONTRACT_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'SALARY_CHANGE_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'PAYROLL_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 80, 'USER', 'PAYROLL_SUMMARY', 'ALL' FROM DUAL
) s ON (t.SUBJECT_ID = s.usr_id AND t.SUBJECT_TYPE = s.stype AND t.CAPABILITY_CODE = s.cap)
WHEN NOT MATCHED THEN INSERT (SUBJECT_TYPE, SUBJECT_ID, CAPABILITY_CODE, SCOPE_TYPE, EFFECT, IS_ENABLED)
VALUES (s.stype, s.usr_id, s.cap, s.scope, 'ALLOW', 1);

-- Also for Group 89 (ADMIN group)
MERGE INTO AI_OWNER.TB_AI_SCOPE_GRANT t USING (
    SELECT 89 AS grp_id, 'GROUP' AS stype, 'EMPLOYEE_LOOKUP' AS cap, 'ALL' AS scope FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'EMPLOYEE_PROFILE', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'EMPLOYEE_COUNT', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'ATTENDANCE_SUMMARY', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'OVERTIME_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'OVERTIME_SUM', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'ALLOWANCE_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'INSURANCE_SELF', 'SELF' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'ADVANCE_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'CONTRACT_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'SALARY_CHANGE_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'PAYROLL_VIEW', 'ALL' FROM DUAL UNION ALL
    SELECT 89, 'GROUP', 'PAYROLL_SUMMARY', 'ALL' FROM DUAL
) s ON (t.SUBJECT_ID = s.grp_id AND t.SUBJECT_TYPE = s.stype AND t.CAPABILITY_CODE = s.cap)
WHEN NOT MATCHED THEN INSERT (SUBJECT_TYPE, SUBJECT_ID, CAPABILITY_CODE, SCOPE_TYPE, EFFECT, IS_ENABLED)
VALUES (s.stype, s.grp_id, s.cap, s.scope, 'ALLOW', 1);

COMMIT;
EXIT;
