-- ==============================================================================
-- Rollback Migration V1_13: Revert User-Employee Mapping, Requests & Employee Code
-- ==============================================================================

SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

-- 1. Xóa các bảng yêu cầu
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_YEUCAU_TANGCA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_YEUCAU_DIEUCHINHCONG CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_YEUCAU_NGHIPHEP CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. Xóa bảng Mapping
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_USER_EMPLOYEE_MAPPING CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 3. Xóa Index và Cột EMPLOYEE_CODE khỏi TB_NHANVIEN
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX UQ_NHANVIEN_EMPCODE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TB_NHANVIEN DROP COLUMN EMPLOYEE_CODE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;
