-- V1_18 DRAFT / REVIEW ONLY -- 2026-09-26
-- Oracle 19c, owner HR. NOT EXECUTED. No SCHEMA_VERSION registration.
-- Outside active migrations. Read V1_18__review_notes.md before use.
-- Seven business tables + three supporting tables; additive schema only.
-- No historical business backfill, DELETE, DROP, trigger or engine deployment.
-- SQL*Plus/SQLcl/SQL Developer Run Script. Run Statement ignores script guards.
-- Oracle DDL commits implicitly; error rollback CANNOT undo preceding DDL.
SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- Deliberate stop block removed for active execution.

-- Read-only prerequisites. Fail on drift rather than silently skip errors.
DECLARE
    n PLS_INTEGER;
    PROCEDURE need_key(t VARCHAR2, cols VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO n FROM (
            SELECT c.constraint_name,
                LISTAGG(cc.column_name, ',') WITHIN GROUP (ORDER BY cc.position) key_cols
            FROM user_constraints c JOIN user_cons_columns cc
              ON cc.constraint_name = c.constraint_name
            WHERE c.table_name = t AND c.constraint_type IN ('P','U')
              AND c.status = 'ENABLED' AND c.validated = 'VALIDATED'
            GROUP BY c.constraint_name
        ) WHERE key_cols = cols;
        IF n = 0 THEN
            RAISE_APPLICATION_ERROR(-20181, 'Missing validated key ' || t || '(' || cols || ')');
        END IF;
    END;
BEGIN
    IF USER <> 'HR' THEN RAISE_APPLICATION_ERROR(-20182, 'Expected HR schema.'); END IF;
    need_key('TB_NHANVIEN', 'MANV');
    need_key('TB_SYS_USER', 'IDUSER');
    need_key('TB_LOAICA', 'IDLOAICA');
    need_key('TB_KYCONG', 'MAKYCONG');
    need_key('TB_BANGCONG', 'MABC');
    need_key('TB_BANGCONG_CHITIET', 'IDBANGCONGCT');
    need_key('TB_BANGCONG_CHITIET', 'IDBANGCONGCT,MANV');
    need_key('TB_YEUCAU_TANGCA', 'ID');
    need_key('TB_YEUCAU_NGHIPHEP', 'ID');
    need_key('TB_YEUCAU_DIEUCHINHCONG', 'ID');
    SELECT COUNT(*) INTO n FROM user_tab_columns
      WHERE table_name = 'TB_KYCONG' AND column_name = 'KHOA' AND data_type = 'NUMBER';
    IF n <> 1 THEN RAISE_APPLICATION_ERROR(-20183, 'Expected numeric TB_KYCONG.KHOA.'); END IF;
    SELECT COUNT(*) INTO n FROM user_tab_columns
      WHERE table_name = 'TB_BANGLUONG_CT_SOURCE' AND column_name = 'SOURCE_BCCT_ID';
    IF n <> 1 THEN RAISE_APPLICATION_ERROR(-20184, 'Missing payroll source table/column.'); END IF;
    SELECT COUNT(*) INTO n FROM user_tables WHERE table_name IN
      ('TB_CA_PHIENBAN','TB_CA_KHUNGGIO','TB_QUYDINH_CHAMCONG','TB_LICH_LAMVIEC',
       'TB_CHAMCONG_LANTINH','TB_CHAMCONG_KQ_NGAY','TB_CONG_PHANDOAN',
       'TB_CONG_PD_NGUON','TB_CHAMCONG_BATTHUONG','TB_CHAMCONG_BT_LICHSU');
    IF n > 0 THEN RAISE_APPLICATION_ERROR(-20185, 'Draft tables already exist; inspect partial execution.'); END IF;
    SELECT COUNT(*) INTO n FROM user_tab_columns WHERE
      (table_name = 'TB_BANGCONG' AND column_name = 'THOIDIEM_VAO') OR
      (table_name = 'TB_BANGCONG_CHITIET' AND column_name = 'LANTINH_ID_HIENHANH') OR
      (table_name = 'TB_KYCONG' AND column_name = 'CONG_INPUT_REV');
    IF n > 0 THEN RAISE_APPLICATION_ERROR(-20186, 'Draft columns already exist; do not blindly rerun.'); END IF;
END;
/

-- A. Existing rows retain NULL for unknown business facts.
-- DATE stores complete date/time to seconds, business TZ Asia/Ho_Chi_Minh.
-- Do not infer next-day checkout solely from checkout clock < checkin clock.

ALTER TABLE HR.TB_BANGCONG ADD (
    THOIDIEM_VAO DATE,
    THOIDIEM_RA DATE,
    NGUON_CHAM VARCHAR2(30),
    MA_SU_KIEN_NGUON VARCHAR2(100),
    MA_THIET_BI VARCHAR2(50),
    TIEPNHAN_LUC TIMESTAMP(6),
    NGUON_REV NUMBER(18),
    CONSTRAINT CK18_BC_TIME CHECK (THOIDIEM_VAO IS NULL OR THOIDIEM_RA IS NULL OR THOIDIEM_RA > THOIDIEM_VAO),
    CONSTRAINT CK18_BC_SOURCE CHECK (NGUON_CHAM IN ('LEGACY_UNKNOWN','SIMULATION','IMPORT','DEVICE','APP','MANUAL_APPROVED')),
    CONSTRAINT CK18_BC_REV CHECK (NGUON_REV >= 0)
);

ALTER TABLE HR.TB_BANGCONG ADD CONSTRAINT UQ18_BC_ID_NV UNIQUE (MABC, MANV);

CREATE INDEX HR.IX18_BC_TIME ON HR.TB_BANGCONG (MANV, THOIDIEM_VAO, THOIDIEM_RA);

ALTER TABLE HR.TB_BANGCONG_CHITIET ADD (
    TRANGTHAI_CONG VARCHAR2(30),
    DU_DIEUKIEN_CHOT NUMBER(1),
    LANTINH_ID_HIENHANH NUMBER(18),
    GIAY_THUC_TE NUMBER(12),
    GIAY_HUONG_CONG_THUONG NUMBER(12),
    GIAY_OT_XAC_NHAN NUMBER(12),
    GIAY_DEM_TRONG_GIO_THUONG NUMBER(12),
    GIAY_DEM_OT NUMBER(12),
    GIAY_DI_MUON_THUC_TE NUMBER(12),
    GIAY_VE_SOM_THUC_TE NUMBER(12),
    GIAY_DI_MUON_VIPHAM NUMBER(12),
    GIAY_VE_SOM_VIPHAM NUMBER(12),
    CONSTRAINT CK18_BCCT_STATUS CHECK (TRANGTHAI_CONG IN ('CHO_XAC_MINH','DA_XAC_NHAN','KHOA','LEGACY_UNCLASSIFIED','LEGACY_FINALIZED')),
    CONSTRAINT CK18_BCCT_READY CHECK (DU_DIEUKIEN_CHOT IN (0,1))
);

-- No blanket LEGACY_FINALIZED, NGAYCONG * 28800, or fabricated zero backfill.

ALTER TABLE HR.TB_KYCONG ADD (
    CONG_INPUT_REV NUMBER(18) DEFAULT 0 NOT NULL,
    CONG_PUBLISH_REV NUMBER(18) DEFAULT 0 NOT NULL,
    CONSTRAINT CK18_KC_REV CHECK (CONG_INPUT_REV >= 0 AND CONG_PUBLISH_REV >= 0)
);

-- Revisions are technical counters, not historical payroll classifications.

ALTER TABLE HR.TB_YEUCAU_TANGCA ADD (
    BATDAU_DANGKY DATE,
    KETTHUC_DANGKY DATE,
    BATDAU_DUYET DATE,
    KETTHUC_DUYET DATE,
    GIAY_OT_DUYET NUMBER(12),
    CONSTRAINT CK18_TC_REG CHECK ((BATDAU_DANGKY IS NULL AND KETTHUC_DANGKY IS NULL) OR (BATDAU_DANGKY IS NOT NULL AND KETTHUC_DANGKY IS NOT NULL AND KETTHUC_DANGKY > BATDAU_DANGKY)),
    CONSTRAINT CK18_TC_APPROVED CHECK ((BATDAU_DUYET IS NULL AND KETTHUC_DUYET IS NULL AND GIAY_OT_DUYET IS NULL) OR (BATDAU_DUYET IS NOT NULL AND KETTHUC_DUYET IS NOT NULL AND KETTHUC_DUYET > BATDAU_DUYET AND GIAY_OT_DUYET IS NOT NULL AND GIAY_OT_DUYET >= 0 AND GIAY_OT_DUYET <= ROUND((KETTHUC_DUYET - BATDAU_DUYET) * 86400)))
);

ALTER TABLE HR.TB_YEUCAU_TANGCA ADD CONSTRAINT UQ18_TC_ID_NV UNIQUE (ID, MANV);

CREATE INDEX HR.IX18_TC_RANGE ON HR.TB_YEUCAU_TANGCA (MANV, BATDAU_DUYET, KETTHUC_DUYET);

ALTER TABLE HR.TB_YEUCAU_NGHIPHEP ADD (
    BATDAU_NGHI DATE,
    KETTHUC_NGHI DATE,
    GIAY_NGHI NUMBER(12),
    NGUON_CHI_TRA VARCHAR2(30),
    LOAI_HUONG_CONG VARCHAR2(30),
    CONSTRAINT CK18_NP_TIME CHECK ((BATDAU_NGHI IS NULL AND KETTHUC_NGHI IS NULL) OR (BATDAU_NGHI IS NOT NULL AND KETTHUC_NGHI IS NOT NULL AND KETTHUC_NGHI > BATDAU_NGHI)),
    CONSTRAINT CK18_NP_SECONDS CHECK (GIAY_NGHI >= 0),
    CONSTRAINT CK18_NP_PAYER CHECK (NGUON_CHI_TRA IN ('CONG_TY','BHXH','KHONG_CHI_TRA','CHUA_XAC_DINH')),
    CONSTRAINT CK18_NP_TYPE CHECK (LOAI_HUONG_CONG IN ('PHEP_NAM','NGHI_HUONG_LUONG','NGHI_BHXH','KHONG_LUONG','LEGACY_UNCLASSIFIED'))
);

ALTER TABLE HR.TB_YEUCAU_NGHIPHEP ADD CONSTRAINT UQ18_NP_ID_NV UNIQUE (ID, MANV);

-- Leave duration follows scheduled obligations, not elapsed calendar duration.

ALTER TABLE HR.TB_YEUCAU_DIEUCHINHCONG ADD (
    THOIDIEM_VAO_CU DATE,
    THOIDIEM_RA_CU DATE,
    THOIDIEM_VAO_MOI DATE,
    THOIDIEM_RA_MOI DATE,
    IDBANGCONG_GOC NUMBER,
    NGUON_HASH_CU VARCHAR2(64),
    CONSTRAINT CK18_DC_OLD CHECK (THOIDIEM_VAO_CU IS NULL OR THOIDIEM_RA_CU IS NULL OR THOIDIEM_RA_CU > THOIDIEM_VAO_CU),
    CONSTRAINT CK18_DC_NEW CHECK (THOIDIEM_VAO_MOI IS NULL OR THOIDIEM_RA_MOI IS NULL OR THOIDIEM_RA_MOI > THOIDIEM_VAO_MOI),
    CONSTRAINT FK18_DC_RAW FOREIGN KEY (IDBANGCONG_GOC, MANV) REFERENCES HR.TB_BANGCONG (MABC, MANV)
);

ALTER TABLE HR.TB_YEUCAU_DIEUCHINHCONG ADD CONSTRAINT UQ18_DC_ID_NV UNIQUE (ID, MANV);

-- B. Seven business tables. Published versions are immutable by write protocol.

CREATE TABLE HR.TB_CA_PHIENBAN (
    IDCAPHIENBAN NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    IDLOAICA NUMBER NOT NULL,
    SO_PHIENBAN NUMBER(10) NOT NULL,
    TEN_PHIENBAN NVARCHAR2(100) NOT NULL,
    TU_NGAY DATE NOT NULL,
    DEN_NGAY DATE,
    TONG_GIAY_CHUAN NUMBER(12) NOT NULL,
    CONG_QUY_DOI NUMBER(12,6) NOT NULL,
    TRANG_THAI VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    TAO_LUC TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TAO_BOI NUMBER NOT NULL,
    CONSTRAINT PK18_CAPB PRIMARY KEY (IDCAPHIENBAN),
    CONSTRAINT UQ18_CAPB_VERSION UNIQUE (IDLOAICA, SO_PHIENBAN),
    CONSTRAINT CK18_CAPB_VER CHECK (SO_PHIENBAN > 0),
    CONSTRAINT CK18_CAPB_DATES CHECK (TRUNC(TU_NGAY) = TU_NGAY AND (DEN_NGAY IS NULL OR (TRUNC(DEN_NGAY) = DEN_NGAY AND DEN_NGAY > TU_NGAY))),
    CONSTRAINT CK18_CAPB_TIME CHECK (TONG_GIAY_CHUAN > 0 AND CONG_QUY_DOI > 0),
    CONSTRAINT CK18_CAPB_STATUS CHECK (TRANG_THAI IN ('DRAFT','PUBLISHED','RETIRED')),
    CONSTRAINT FK18_CAPB_CA FOREIGN KEY (IDLOAICA) REFERENCES HR.TB_LOAICA (IDLOAICA),
    CONSTRAINT FK18_CAPB_USER FOREIGN KEY (TAO_BOI) REFERENCES HR.TB_SYS_USER (IDUSER)
);

-- Effective intervals [TU_NGAY, DEN_NGAY). Sum of eligible blocks must reconcile to standard.

CREATE TABLE HR.TB_CA_KHUNGGIO (
    IDKHUNGGIO NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    IDCAPHIENBAN NUMBER(18) NOT NULL,
    STT NUMBER(6) NOT NULL,
    BATDAU_PHUT NUMBER(8) NOT NULL,
    KETTHUC_PHUT NUMBER(8) NOT NULL,
    LOAI_KHUNGGIO VARCHAR2(30) NOT NULL,
    BAT_BUOC_QUET_THE NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK18_KG PRIMARY KEY (IDKHUNGGIO),
    CONSTRAINT UQ18_KG_ORDER UNIQUE (IDCAPHIENBAN, STT),
    CONSTRAINT CK18_KG_TIME CHECK (STT > 0 AND BATDAU_PHUT >= 0 AND KETTHUC_PHUT > BATDAU_PHUT),
    CONSTRAINT CK18_KG_TYPE CHECK (LOAI_KHUNGGIO IN ('LAM_VIEC','NGHI_HUONG_LUONG','NGHI_KHONG_LUONG')),
    CONSTRAINT CK18_KG_PUNCH CHECK (BAT_BUOC_QUET_THE IN (0,1)),
    CONSTRAINT FK18_KG_CA FOREIGN KEY (IDCAPHIENBAN) REFERENCES HR.TB_CA_PHIENBAN (IDCAPHIENBAN)
);

CREATE TABLE HR.TB_QUYDINH_CHAMCONG (
    IDQUYDINH NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    MA_QUYDINH VARCHAR2(50) NOT NULL,
    SO_PHIENBAN NUMBER(10) NOT NULL,
    TEN_QUYDINH NVARCHAR2(150) NOT NULL,
    TU_NGAY DATE NOT NULL,
    DEN_NGAY DATE,
    GIAY_MIEN_VIPHAM_MUON NUMBER(10) DEFAULT 0 NOT NULL,
    GIAY_MIEN_VIPHAM_SOM NUMBER(10) DEFAULT 0 NOT NULL,
    GIAY_DUNG_SAI_HUONG_CONG NUMBER(10) DEFAULT 0 NOT NULL,
    CACH_HUONG_DUNG_SAI VARCHAR2(30) DEFAULT 'KHONG_BU' NOT NULL,
    CACH_DEM_MUON VARCHAR2(30) DEFAULT 'TOAN_BO_NEU_VUOT' NOT NULL,
    CUA_SO_VAO_TRUOC_GIAY NUMBER(10) DEFAULT 3600 NOT NULL,
    CUA_SO_RA_SAU_GIAY NUMBER(10) DEFAULT 7200 NOT NULL,
    GIOI_HAN_GHEP_GIAY NUMBER(10) NOT NULL,
    MUI_GIO VARCHAR2(64) DEFAULT 'Asia/Ho_Chi_Minh' NOT NULL,
    DEM_BATDAU_PHUT NUMBER(4) DEFAULT 1320 NOT NULL,
    DEM_KETTHUC_PHUT NUMBER(4) DEFAULT 360 NOT NULL,
    KIEU_LAM_TRON VARCHAR2(20) DEFAULT 'EXACT' NOT NULL,
    BUOC_LAM_TRON_GIAY NUMBER(10) DEFAULT 1 NOT NULL,
    TRANG_THAI VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    TAO_LUC TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TAO_BOI NUMBER NOT NULL,
    CONSTRAINT PK18_QD PRIMARY KEY (IDQUYDINH),
    CONSTRAINT UQ18_QD_VERSION UNIQUE (MA_QUYDINH, SO_PHIENBAN),
    CONSTRAINT CK18_QD_VER CHECK (SO_PHIENBAN > 0),
    CONSTRAINT CK18_QD_DATES CHECK (TRUNC(TU_NGAY) = TU_NGAY AND (DEN_NGAY IS NULL OR (TRUNC(DEN_NGAY) = DEN_NGAY AND DEN_NGAY > TU_NGAY))),
    CONSTRAINT CK18_QD_SECONDS CHECK (GIAY_MIEN_VIPHAM_MUON >= 0 AND GIAY_MIEN_VIPHAM_SOM >= 0 AND GIAY_DUNG_SAI_HUONG_CONG >= 0 AND CUA_SO_VAO_TRUOC_GIAY >= 0 AND CUA_SO_RA_SAU_GIAY >= 0 AND GIOI_HAN_GHEP_GIAY > 0),
    CONSTRAINT CK18_QD_CREDIT CHECK (CACH_HUONG_DUNG_SAI IN ('KHONG_BU','DU_CONG_NEU_TRONG_NGUONG')),
    CONSTRAINT CK18_QD_LATE CHECK (CACH_DEM_MUON IN ('TOAN_BO_NEU_VUOT','PHAN_VUOT_NGUONG')),
    CONSTRAINT CK18_QD_NIGHT CHECK (DEM_BATDAU_PHUT BETWEEN 0 AND 1439 AND DEM_KETTHUC_PHUT BETWEEN 0 AND 1439 AND DEM_BATDAU_PHUT <> DEM_KETTHUC_PHUT),
    CONSTRAINT CK18_QD_ROUND CHECK ((KIEU_LAM_TRON = 'EXACT' AND BUOC_LAM_TRON_GIAY = 1) OR (KIEU_LAM_TRON IN ('FLOOR','CEILING','NEAREST') AND BUOC_LAM_TRON_GIAY > 0)),
    CONSTRAINT CK18_QD_STATUS CHECK (TRANG_THAI IN ('DRAFT','PUBLISHED','RETIRED')),
    CONSTRAINT FK18_QD_USER FOREIGN KEY (TAO_BOI) REFERENCES HR.TB_SYS_USER (IDUSER)
);

-- Non-EXACT rules need reviewed payment-stage policy. Never round physical intervals.

CREATE TABLE HR.TB_LICH_LAMVIEC (
    IDLICH NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    MANV NUMBER NOT NULL,
    NGAY DATE NOT NULL,
    MA_PHANCONG VARCHAR2(100) NOT NULL,
    SO_PHIENBAN NUMBER(10) NOT NULL,
    THAY_THE_ID NUMBER(18),
    IDCAPHIENBAN NUMBER(18),
    IDQUYDINH NUMBER(18),
    BATDAU_KEHOACH DATE,
    KETTHUC_KEHOACH DATE,
    TRANG_THAI_PHAN_CONG VARCHAR2(20) NOT NULL,
    LOAI_NGAY VARCHAR2(20) NOT NULL,
    TRANG_THAI VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    NGUON_PHAN_CONG VARCHAR2(30) NOT NULL,
    TAO_LUC TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    TAO_BOI NUMBER NOT NULL,
    LY_DO NVARCHAR2(500),
    CONSTRAINT PK18_LICH PRIMARY KEY (IDLICH),
    CONSTRAINT UQ18_LICH_NV UNIQUE (IDLICH, MANV),
    CONSTRAINT UQ18_LICH_VERSION UNIQUE (MA_PHANCONG, SO_PHIENBAN),
    CONSTRAINT CK18_LICH_VER CHECK (SO_PHIENBAN > 0),
    CONSTRAINT CK18_LICH_DATE CHECK (TRUNC(NGAY) = NGAY),
    CONSTRAINT CK18_LICH_SHAPE CHECK ((TRANG_THAI_PHAN_CONG = 'LAM_VIEC' AND IDCAPHIENBAN IS NOT NULL AND IDQUYDINH IS NOT NULL AND BATDAU_KEHOACH IS NOT NULL AND KETTHUC_KEHOACH IS NOT NULL AND TRUNC(BATDAU_KEHOACH) = NGAY AND KETTHUC_KEHOACH > BATDAU_KEHOACH) OR (TRANG_THAI_PHAN_CONG IN ('NGHI','CHUA_XAC_DINH') AND IDCAPHIENBAN IS NULL AND BATDAU_KEHOACH IS NULL AND KETTHUC_KEHOACH IS NULL)),
    CONSTRAINT CK18_LICH_DAY CHECK (LOAI_NGAY IN ('THUONG','NGHI_TUAN','LE','CHUA_XAC_DINH')),
    CONSTRAINT CK18_LICH_STATUS CHECK (TRANG_THAI IN ('DRAFT','PUBLISHED','SUPERSEDED','CANCELLED')),
    CONSTRAINT FK18_LICH_NV FOREIGN KEY (MANV) REFERENCES HR.TB_NHANVIEN (MANV),
    CONSTRAINT FK18_LICH_CA FOREIGN KEY (IDCAPHIENBAN) REFERENCES HR.TB_CA_PHIENBAN (IDCAPHIENBAN),
    CONSTRAINT FK18_LICH_QD FOREIGN KEY (IDQUYDINH) REFERENCES HR.TB_QUYDINH_CHAMCONG (IDQUYDINH),
    CONSTRAINT FK18_LICH_PREV FOREIGN KEY (THAY_THE_ID, MANV) REFERENCES HR.TB_LICH_LAMVIEC (IDLICH, MANV),
    CONSTRAINT FK18_LICH_USER FOREIGN KEY (TAO_BOI) REFERENCES HR.TB_SYS_USER (IDUSER)
);

CREATE INDEX HR.IX18_LICH_DATE ON HR.TB_LICH_LAMVIEC (MANV, NGAY);

CREATE INDEX HR.IX18_LICH_TIME ON HR.TB_LICH_LAMVIEC (MANV, BATDAU_KEHOACH, KETTHUC_KEHOACH);

CREATE UNIQUE INDEX HR.UQ18_LICH_ACTIVE ON HR.TB_LICH_LAMVIEC
    (CASE WHEN TRANG_THAI = 'PUBLISHED' THEN MA_PHANCONG END);
-- Prevents two active revisions of one assignment, NOT arbitrary interval overlap.

CREATE TABLE HR.TB_CHAMCONG_LANTINH (
    IDLANTINH NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    MA_YEU_CAU VARCHAR2(100) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    MAKYCONG NUMBER NOT NULL,
    TU_NGAY DATE NOT NULL,
    DEN_NGAY DATE NOT NULL,
    INPUT_REV NUMBER(18) NOT NULL,
    EXPECTED_PUBLISH_REV NUMBER(18) NOT NULL,
    INPUT_DATA_HASH VARCHAR2(64),
    PHIENBAN_ENGINE VARCHAR2(50) NOT NULL,
    MUI_GIO VARCHAR2(64) DEFAULT 'Asia/Ho_Chi_Minh' NOT NULL,
    TRANG_THAI VARCHAR2(30) DEFAULT 'DANG_CHAY' NOT NULL,
    BATDAU_TINH TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    KETTHUC_TINH TIMESTAMP(6),
    CONGBO_LUC TIMESTAMP(6),
    NGUOI_THUC_HIEN NUMBER NOT NULL,
    GHI_CHU NVARCHAR2(1000),
    CONSTRAINT PK18_RUN PRIMARY KEY (IDLANTINH),
    CONSTRAINT UQ18_RUN_REQUEST UNIQUE (MA_YEU_CAU),
    CONSTRAINT UQ18_RUN_PERIOD UNIQUE (IDLANTINH, MAKYCONG),
    CONSTRAINT CK18_RUN_DATES CHECK (TRUNC(TU_NGAY) = TU_NGAY AND TRUNC(DEN_NGAY) = DEN_NGAY AND DEN_NGAY > TU_NGAY),
    CONSTRAINT CK18_RUN_REV CHECK (INPUT_REV >= 0 AND EXPECTED_PUBLISH_REV >= 0),
    CONSTRAINT CK18_RUN_STATUS CHECK (TRANG_THAI IN ('DANG_CHAY','SAN_SANG','DA_CONG_BO','CAN_TINH_LAI','THAT_BAI','DA_HUY')),
    CONSTRAINT CK18_RUN_PUBLISH CHECK (TRANG_THAI <> 'DA_CONG_BO' OR (CONGBO_LUC IS NOT NULL AND KETTHUC_TINH IS NOT NULL AND INPUT_DATA_HASH IS NOT NULL)),
    CONSTRAINT FK18_RUN_PERIOD FOREIGN KEY (MAKYCONG) REFERENCES HR.TB_KYCONG (MAKYCONG),
    CONSTRAINT FK18_RUN_USER FOREIGN KEY (NGUOI_THUC_HIEN) REFERENCES HR.TB_SYS_USER (IDUSER)
);

-- Supporting table 1: immutable scope/day-result version, including zero-segment days.

CREATE TABLE HR.TB_CHAMCONG_KQ_NGAY (
    IDLANTINH NUMBER(18) NOT NULL,
    IDBANGCONGCT NUMBER NOT NULL,
    MANV NUMBER NOT NULL,
    MAKYCONG NUMBER NOT NULL,
    NGAY DATE NOT NULL,
    INPUT_HASH VARCHAR2(64) NOT NULL,
    INPUT_SNAPSHOT CLOB NOT NULL,
    TRANG_THAI VARCHAR2(30) DEFAULT 'CHO_XAC_MINH' NOT NULL,
    DU_DIEUKIEN_CHOT NUMBER(1) DEFAULT 0 NOT NULL,
    GIAY_THUC_TE NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_HUONG_CONG_THUONG NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_OT_XAC_NHAN NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DEM_TRONG_GIO_THUONG NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DEM_OT NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DI_MUON_THUC_TE NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_VE_SOM_THUC_TE NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DI_MUON_VIPHAM NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_VE_SOM_VIPHAM NUMBER(12) DEFAULT 0 NOT NULL,
    CONG_THUONG_QUYDOI NUMBER(18,8) DEFAULT 0 NOT NULL,
    TAO_LUC TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK18_KQ PRIMARY KEY (IDLANTINH, IDBANGCONGCT),
    CONSTRAINT UQ18_KQ_NV UNIQUE (IDLANTINH, IDBANGCONGCT, MANV),
    CONSTRAINT UQ18_KQ_DAY UNIQUE (IDLANTINH, MANV, NGAY),
    CONSTRAINT CK18_KQ_DATE CHECK (TRUNC(NGAY) = NGAY),
    CONSTRAINT CK18_KQ_JSON CHECK (INPUT_SNAPSHOT IS JSON),
    CONSTRAINT CK18_KQ_STATUS CHECK (TRANG_THAI IN ('CHO_XAC_MINH','DA_XAC_NHAN')),
    CONSTRAINT CK18_KQ_READY CHECK (DU_DIEUKIEN_CHOT IN (0,1) AND (DU_DIEUKIEN_CHOT = 0 OR TRANG_THAI = 'DA_XAC_NHAN')),
    CONSTRAINT CK18_KQ_SECONDS CHECK (GIAY_THUC_TE >= 0 AND GIAY_HUONG_CONG_THUONG >= 0 AND GIAY_OT_XAC_NHAN >= 0 AND GIAY_DEM_TRONG_GIO_THUONG >= 0 AND GIAY_DEM_OT >= 0 AND GIAY_DI_MUON_THUC_TE >= 0 AND GIAY_VE_SOM_THUC_TE >= 0 AND GIAY_DI_MUON_VIPHAM >= 0 AND GIAY_VE_SOM_VIPHAM >= 0 AND GIAY_DEM_OT <= GIAY_OT_XAC_NHAN AND GIAY_DEM_TRONG_GIO_THUONG + GIAY_OT_XAC_NHAN <= GIAY_THUC_TE AND GIAY_DI_MUON_VIPHAM <= GIAY_DI_MUON_THUC_TE AND GIAY_VE_SOM_VIPHAM <= GIAY_VE_SOM_THUC_TE AND CONG_THUONG_QUYDOI >= 0),
    CONSTRAINT FK18_KQ_RUN FOREIGN KEY (IDLANTINH, MAKYCONG) REFERENCES HR.TB_CHAMCONG_LANTINH (IDLANTINH, MAKYCONG),
    CONSTRAINT FK18_KQ_DAY FOREIGN KEY (IDBANGCONGCT, MANV) REFERENCES HR.TB_BANGCONG_CHITIET (IDBANGCONGCT, MANV),
    CONSTRAINT FK18_KQ_NV FOREIGN KEY (MANV) REFERENCES HR.TB_NHANVIEN (MANV)
);

CREATE INDEX HR.IX18_KQ_DAY ON HR.TB_CHAMCONG_KQ_NGAY (IDBANGCONGCT, IDLANTINH, MANV);

-- Snapshot contract: ordered schedule/calendar, policy, employment, source and approved decision versions; not merely IDs/hashes.

CREATE TABLE HR.TB_CONG_PHANDOAN (
    IDPHANDOAN NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    IDLANTINH NUMBER(18) NOT NULL,
    IDBANGCONGCT NUMBER NOT NULL,
    MANV NUMBER NOT NULL,
    IDLICH NUMBER(18),
    IDQUYDINH NUMBER(18) NOT NULL,
    BATDAU_LUC DATE NOT NULL,
    KETTHUC_LUC DATE NOT NULL,
    THOILUONG_GIAY NUMBER(12) NOT NULL,
    LOAI_THOIGIAN VARCHAR2(30) NOT NULL,
    LOAI_NGAY VARCHAR2(20) NOT NULL,
    LA_BAN_DEM NUMBER(1) DEFAULT 0 NOT NULL,
    CO_OT_BAN_NGAY_TRUOC NUMBER(1) DEFAULT 0 NOT NULL,
    TRANGTHAI_XACNHAN VARCHAR2(30) NOT NULL,
    GIAY_THUC_TE NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_HUONG_CONG_THUONG NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_OT_XAC_NHAN NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DEM_TRONG_GIO_THUONG NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DEM_OT NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DI_MUON_THUC_TE NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_VE_SOM_THUC_TE NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_DI_MUON_VIPHAM NUMBER(12) DEFAULT 0 NOT NULL,
    GIAY_VE_SOM_VIPHAM NUMBER(12) DEFAULT 0 NOT NULL,
    IDYEUCAU_TANGCA NUMBER,
    IDYEUCAU_NGHIPHEP NUMBER,
    IDYEUCAU_DIEUCHINH NUMBER,
    CONSTRAINT PK18_PD PRIMARY KEY (IDPHANDOAN),
    CONSTRAINT UQ18_PD_NV UNIQUE (IDPHANDOAN, MANV),
    CONSTRAINT UQ18_PD_INTERVAL UNIQUE (IDLANTINH, IDBANGCONGCT, BATDAU_LUC, KETTHUC_LUC),
    CONSTRAINT CK18_PD_TIME CHECK (KETTHUC_LUC > BATDAU_LUC AND THOILUONG_GIAY > 0 AND THOILUONG_GIAY = ROUND((KETTHUC_LUC - BATDAU_LUC) * 86400) AND KETTHUC_LUC <= TRUNC(BATDAU_LUC) + 1),
    CONSTRAINT CK18_PD_TYPE CHECK (LOAI_THOIGIAN IN ('LAM_VIEC','NGHI_HUONG_LUONG','NGHI_KHONG_LUONG','PHEP_HUONG_LUONG','PHEP_KHONG_LUONG','NGHI_BHXH','NGHI_LE','DI_MUON','VE_SOM','VANG_TRONG_CA','CO_MAT_NGOAI_CA','CHO_XAC_MINH')),
    CONSTRAINT CK18_PD_DAY CHECK (LOAI_NGAY IN ('THUONG','NGHI_TUAN','LE','CHUA_XAC_DINH')),
    CONSTRAINT CK18_PD_STATUS CHECK (TRANGTHAI_XACNHAN IN ('CHO_XAC_MINH','DA_XAC_NHAN','KHONG_TINH')),
    CONSTRAINT CK18_PD_FLAGS CHECK (LA_BAN_DEM IN (0,1) AND CO_OT_BAN_NGAY_TRUOC IN (0,1)),
    CONSTRAINT CK18_PD_SECONDS CHECK (GIAY_THUC_TE >= 0 AND GIAY_HUONG_CONG_THUONG >= 0 AND GIAY_OT_XAC_NHAN >= 0 AND GIAY_DEM_TRONG_GIO_THUONG >= 0 AND GIAY_DEM_OT >= 0 AND GIAY_DI_MUON_THUC_TE >= 0 AND GIAY_VE_SOM_THUC_TE >= 0 AND GIAY_DI_MUON_VIPHAM >= 0 AND GIAY_VE_SOM_VIPHAM >= 0 AND GIAY_DEM_OT <= GIAY_OT_XAC_NHAN AND GIAY_DEM_TRONG_GIO_THUONG + GIAY_OT_XAC_NHAN <= GIAY_THUC_TE AND GIAY_DI_MUON_VIPHAM <= GIAY_DI_MUON_THUC_TE AND GIAY_VE_SOM_VIPHAM <= GIAY_VE_SOM_THUC_TE AND GIAY_THUC_TE <= THOILUONG_GIAY AND GIAY_HUONG_CONG_THUONG <= THOILUONG_GIAY AND GIAY_DI_MUON_THUC_TE <= THOILUONG_GIAY AND GIAY_VE_SOM_THUC_TE <= THOILUONG_GIAY),
    CONSTRAINT CK18_PD_NIGHT CHECK (LA_BAN_DEM = 1 OR (GIAY_DEM_TRONG_GIO_THUONG = 0 AND GIAY_DEM_OT = 0)),
    CONSTRAINT CK18_PD_PENDING CHECK (TRANGTHAI_XACNHAN = 'DA_XAC_NHAN' OR (GIAY_HUONG_CONG_THUONG = 0 AND GIAY_OT_XAC_NHAN = 0 AND GIAY_DEM_TRONG_GIO_THUONG = 0 AND GIAY_DEM_OT = 0)),
    CONSTRAINT FK18_PD_KQ FOREIGN KEY (IDLANTINH, IDBANGCONGCT, MANV) REFERENCES HR.TB_CHAMCONG_KQ_NGAY (IDLANTINH, IDBANGCONGCT, MANV),
    CONSTRAINT FK18_PD_LICH FOREIGN KEY (IDLICH, MANV) REFERENCES HR.TB_LICH_LAMVIEC (IDLICH, MANV),
    CONSTRAINT FK18_PD_QD FOREIGN KEY (IDQUYDINH) REFERENCES HR.TB_QUYDINH_CHAMCONG (IDQUYDINH),
    CONSTRAINT FK18_PD_TC FOREIGN KEY (IDYEUCAU_TANGCA, MANV) REFERENCES HR.TB_YEUCAU_TANGCA (ID, MANV),
    CONSTRAINT FK18_PD_NP FOREIGN KEY (IDYEUCAU_NGHIPHEP, MANV) REFERENCES HR.TB_YEUCAU_NGHIPHEP (ID, MANV),
    CONSTRAINT FK18_PD_DC FOREIGN KEY (IDYEUCAU_DIEUCHINH, MANV) REFERENCES HR.TB_YEUCAU_DIEUCHINHCONG (ID, MANV)
);

CREATE INDEX HR.IX18_PD_DATE ON HR.TB_CONG_PHANDOAN (MANV, BATDAU_LUC, KETTHUC_LUC);

-- Physical classification is exclusive; entitlement quantities are independent.
-- Holiday pay eligibility can coexist with holiday work, but ordinary-day OT
-- must not also receive ordinary time credit. Cut at every classification boundary.

-- Supporting table 2: multiple original pairs and immutable snapshots per segment.

CREATE TABLE HR.TB_CONG_PD_NGUON (
    ID NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    IDPHANDOAN NUMBER(18) NOT NULL,
    MANV NUMBER NOT NULL,
    MABC NUMBER NOT NULL,
    SOURCE_HASH VARCHAR2(64) NOT NULL,
    SOURCE_SNAPSHOT CLOB NOT NULL,
    CONSTRAINT PK18_PD_SRC PRIMARY KEY (ID),
    CONSTRAINT UQ18_PD_SRC UNIQUE (IDPHANDOAN, MABC),
    CONSTRAINT CK18_PD_SRC_JSON CHECK (SOURCE_SNAPSHOT IS JSON),
    CONSTRAINT FK18_PD_SRC_PD FOREIGN KEY (IDPHANDOAN, MANV) REFERENCES HR.TB_CONG_PHANDOAN (IDPHANDOAN, MANV),
    CONSTRAINT FK18_PD_SRC_RAW FOREIGN KEY (MABC, MANV) REFERENCES HR.TB_BANGCONG (MABC, MANV)
);

CREATE INDEX HR.IX18_PD_SRC_RAW ON HR.TB_CONG_PD_NGUON (MABC, MANV);

CREATE TABLE HR.TB_CHAMCONG_BATTHUONG (
    IDBATTHUONG NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    MA_SU_VIEC_HASH VARCHAR2(64) NOT NULL,
    IDLANTINH_PHATHIEN NUMBER(18) NOT NULL,
    IDBANGCONGCT NUMBER NOT NULL,
    MANV NUMBER NOT NULL,
    IDLICH NUMBER(18),
    NGAY DATE NOT NULL,
    MA_LOI VARCHAR2(50) NOT NULL,
    BATDAU_LUC DATE,
    KETTHUC_LUC DATE,
    MUC_DO VARCHAR2(30) NOT NULL,
    CHAN_CHOT NUMBER(1) NOT NULL,
    INPUT_HASH VARCHAR2(64) NOT NULL,
    INPUT_SNAPSHOT CLOB NOT NULL,
    TRANG_THAI VARCHAR2(30) DEFAULT 'CHO_XU_LY' NOT NULL,
    IDYEUCAU_NGHIPHEP NUMBER,
    IDYEUCAU_TANGCA NUMBER,
    IDYEUCAU_DIEUCHINH NUMBER,
    THAY_THE_SU_VIEC_ID NUMBER(18),
    MO_TA NVARCHAR2(1000) NOT NULL,
    TAO_LUC TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK18_BT PRIMARY KEY (IDBATTHUONG),
    CONSTRAINT UQ18_BT_HASH UNIQUE (MA_SU_VIEC_HASH),
    CONSTRAINT UQ18_BT_NV UNIQUE (IDBATTHUONG, MANV),
    CONSTRAINT CK18_BT_DATE CHECK (TRUNC(NGAY) = NGAY),
    CONSTRAINT CK18_BT_TIME CHECK ((BATDAU_LUC IS NULL AND KETTHUC_LUC IS NULL) OR (BATDAU_LUC IS NOT NULL AND KETTHUC_LUC IS NOT NULL AND KETTHUC_LUC > BATDAU_LUC)),
    CONSTRAINT CK18_BT_JSON CHECK (INPUT_SNAPSHOT IS JSON),
    CONSTRAINT CK18_BT_LEVEL CHECK (MUC_DO IN ('THONG_TIN','CAN_RA_SOAT','NGHIEP_VU_TREO')),
    CONSTRAINT CK18_BT_BLOCK CHECK (CHAN_CHOT IN (0,1) AND (MUC_DO <> 'NGHIEP_VU_TREO' OR CHAN_CHOT = 1)),
    CONSTRAINT CK18_BT_STATUS CHECK (TRANG_THAI IN ('CHO_XU_LY','DA_XAC_NHAN','KHONG_TINH','MIEN_TRU','DA_THAY_THE')),
    CONSTRAINT FK18_BT_KQ FOREIGN KEY (IDLANTINH_PHATHIEN, IDBANGCONGCT, MANV) REFERENCES HR.TB_CHAMCONG_KQ_NGAY (IDLANTINH, IDBANGCONGCT, MANV),
    CONSTRAINT FK18_BT_LICH FOREIGN KEY (IDLICH, MANV) REFERENCES HR.TB_LICH_LAMVIEC (IDLICH, MANV),
    CONSTRAINT FK18_BT_PREV FOREIGN KEY (THAY_THE_SU_VIEC_ID, MANV) REFERENCES HR.TB_CHAMCONG_BATTHUONG (IDBATTHUONG, MANV),
    CONSTRAINT FK18_BT_TC FOREIGN KEY (IDYEUCAU_TANGCA, MANV) REFERENCES HR.TB_YEUCAU_TANGCA (ID, MANV),
    CONSTRAINT FK18_BT_NP FOREIGN KEY (IDYEUCAU_NGHIPHEP, MANV) REFERENCES HR.TB_YEUCAU_NGHIPHEP (ID, MANV),
    CONSTRAINT FK18_BT_DC FOREIGN KEY (IDYEUCAU_DIEUCHINH, MANV) REFERENCES HR.TB_YEUCAU_DIEUCHINHCONG (ID, MANV)
);

CREATE INDEX HR.IX18_BT_QUEUE ON HR.TB_CHAMCONG_BATTHUONG (TRANG_THAI, CHAN_CHOT, NGAY);

CREATE INDEX HR.IX18_BT_DAY ON HR.TB_CHAMCONG_BATTHUONG (IDBANGCONGCT, MANV);

-- Identity hash includes typed/canonical evidence version, source identity and
-- interval, not new RUN_ID or mutable status. Link superseding cases explicitly.
-- Do not automatically mark unresolved potentially payable time KHONG_TINH.

-- Supporting table 3: append-only decision history, current status is a cache.

CREATE TABLE HR.TB_CHAMCONG_BT_LICHSU (
    ID NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    IDBATTHUONG NUMBER(18) NOT NULL,
    THUTU NUMBER(10) NOT NULL,
    TU_TRANGTHAI VARCHAR2(30) NOT NULL,
    DEN_TRANGTHAI VARCHAR2(30) NOT NULL,
    INPUT_HASH_DUYET VARCHAR2(64) NOT NULL,
    QUYETDINH_SNAPSHOT CLOB NOT NULL,
    LY_DO NVARCHAR2(1000) NOT NULL,
    NGUOI_XULY NUMBER NOT NULL,
    XULY_LUC TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK18_BT_HIST PRIMARY KEY (ID),
    CONSTRAINT UQ18_BT_HIST UNIQUE (IDBATTHUONG, THUTU),
    CONSTRAINT CK18_BT_HIST_SEQ CHECK (THUTU > 0),
    CONSTRAINT CK18_BT_HIST_JSON CHECK (QUYETDINH_SNAPSHOT IS JSON),
    CONSTRAINT CK18_BT_HIST_FROM CHECK (TU_TRANGTHAI IN ('CHO_XU_LY','DA_XAC_NHAN','KHONG_TINH','MIEN_TRU','DA_THAY_THE')),
    CONSTRAINT CK18_BT_HIST_TO CHECK (DEN_TRANGTHAI IN ('CHO_XU_LY','DA_XAC_NHAN','KHONG_TINH','MIEN_TRU','DA_THAY_THE')),
    CONSTRAINT FK18_BT_HIST_CASE FOREIGN KEY (IDBATTHUONG) REFERENCES HR.TB_CHAMCONG_BATTHUONG (IDBATTHUONG),
    CONSTRAINT FK18_BT_HIST_USER FOREIGN KEY (NGUOI_XULY) REFERENCES HR.TB_SYS_USER (IDUSER)
);

-- C. Active day-version pointer and reuse of existing payroll source table.

ALTER TABLE HR.TB_BANGCONG_CHITIET ADD CONSTRAINT FK18_BCCT_CURRENT FOREIGN KEY (LANTINH_ID_HIENHANH, IDBANGCONGCT, MANV) REFERENCES HR.TB_CHAMCONG_KQ_NGAY (IDLANTINH, IDBANGCONGCT, MANV);

ALTER TABLE HR.TB_BANGCONG_CHITIET ADD CONSTRAINT CK18_BCCT_CURRENT CHECK (LANTINH_ID_HIENHANH IS NULL OR (MANV IS NOT NULL AND MAKYCONG IS NOT NULL AND NGAY IS NOT NULL AND TRANGTHAI_CONG IS NOT NULL AND TRANGTHAI_CONG IN ('CHO_XAC_MINH','DA_XAC_NHAN','KHOA') AND DU_DIEUKIEN_CHOT IS NOT NULL AND (TRANGTHAI_CONG = 'CHO_XAC_MINH' OR DU_DIEUKIEN_CHOT = 1) AND GIAY_THUC_TE IS NOT NULL AND GIAY_HUONG_CONG_THUONG IS NOT NULL AND GIAY_OT_XAC_NHAN IS NOT NULL AND GIAY_DEM_TRONG_GIO_THUONG IS NOT NULL AND GIAY_DEM_OT IS NOT NULL AND GIAY_DI_MUON_THUC_TE IS NOT NULL AND GIAY_VE_SOM_THUC_TE IS NOT NULL AND GIAY_DI_MUON_VIPHAM IS NOT NULL AND GIAY_VE_SOM_VIPHAM IS NOT NULL AND GIAY_THUC_TE >= 0 AND GIAY_HUONG_CONG_THUONG >= 0 AND GIAY_OT_XAC_NHAN >= 0 AND GIAY_DEM_TRONG_GIO_THUONG >= 0 AND GIAY_DEM_OT >= 0 AND GIAY_DI_MUON_THUC_TE >= 0 AND GIAY_VE_SOM_THUC_TE >= 0 AND GIAY_DI_MUON_VIPHAM >= 0 AND GIAY_VE_SOM_VIPHAM >= 0 AND GIAY_DEM_OT <= GIAY_OT_XAC_NHAN AND GIAY_DEM_TRONG_GIO_THUONG + GIAY_OT_XAC_NHAN <= GIAY_THUC_TE AND GIAY_DI_MUON_VIPHAM <= GIAY_DI_MUON_THUC_TE AND GIAY_VE_SOM_VIPHAM <= GIAY_VE_SOM_THUC_TE));

CREATE INDEX HR.IX18_BCCT_CURRENT ON HR.TB_BANGCONG_CHITIET (LANTINH_ID_HIENHANH, IDBANGCONGCT, MANV);

ALTER TABLE HR.TB_BANGLUONG_CT_SOURCE ADD (
    SOURCE_CONG_LANTINH_ID NUMBER(18)
);

ALTER TABLE HR.TB_BANGLUONG_CT_SOURCE ADD CONSTRAINT CK18_BL_CONG_SOURCE CHECK (SOURCE_CONG_LANTINH_ID IS NULL OR (SOURCE_BCCT_ID IS NOT NULL AND SOURCE_TYPE = 'BANGCONG'));

ALTER TABLE HR.TB_BANGLUONG_CT_SOURCE ADD CONSTRAINT FK18_BL_CONG_VERSION FOREIGN KEY (SOURCE_CONG_LANTINH_ID, SOURCE_BCCT_ID, MANV) REFERENCES HR.TB_CHAMCONG_KQ_NGAY (IDLANTINH, IDBANGCONGCT, MANV);

CREATE INDEX HR.IX18_BL_CONG_VERSION ON HR.TB_BANGLUONG_CT_SOURCE (SOURCE_CONG_LANTINH_ID, SOURCE_BCCT_ID, MANV);

-- D. Metadata-only example. Legacy reports need an explicit separate path.
SELECT c.IDBANGCONGCT, c.MANV, c.MAKYCONG, c.NGAY, k.IDLANTINH,
       k.TRANG_THAI, k.DU_DIEUKIEN_CHOT, k.GIAY_HUONG_CONG_THUONG, k.GIAY_OT_XAC_NHAN
FROM HR.TB_BANGCONG_CHITIET c
JOIN HR.TB_CHAMCONG_KQ_NGAY k
  ON k.IDBANGCONGCT = c.IDBANGCONGCT AND k.MANV = c.MANV
 AND k.IDLANTINH = c.LANTINH_ID_HIENHANH
WHERE 1 = 0;

-- E. Cutover contract -- NOT implemented by this schema draft:
-- Keep UQ_YEUCAU_TC_ACTIVE until all writers implement interval validation with
-- coordinated locks. A B-tree index cannot enforce arbitrary non-overlap.
-- Replace raw-month DELETE and detailed-period DELETE before enabling results.
-- Every input writer locks affected period rows in ascending MAKYCONG order,
-- increments CONG_INPUT_REV atomically (including cross-month dependencies).
-- Policy/calendar changes invalidate all affected open-period inputs.
-- Publisher locks period, rechecks numeric KHOA, INPUT_REV, PUBLISH_REV, hashes,
-- scope/day consistency and decisions. Copy all day totals + pointer and roll up
-- monthly totals atomically. Pending days stay pending. Publication != approval.
-- On rollback, update CAN_TINH_LAI/THAT_BAI in a separate short transaction.
-- Same request ID + changed payload hash is a conflict. Running retry returns
-- running state, not cached success. New request may create new version history.
-- Freeze published result/snapshot/history rows with controlled DB write access.
-- Payroll captures exact versioned sources once, including justified zero days;
-- never resolve historic payroll through current-day pointers.
-- Keep legacy IDCTY unchanged; no inferred tenant mapping or company data rewrite.
-- No migration version registration before disposable-database validation.
PROMPT V1_18 draft DDL end. This is not a production-readiness assertion.


-- F. Registration in SCHEMA_VERSION
INSERT INTO HR.SCHEMA_VERSION (VERSION, DESCRIPTION, SCRIPT, SUCCESS)
VALUES ('1.18', 'Attendance scheduling, segmentation, anomaly tracking, and day-result versioning', 'V1_18__attendance_scheduling_and_segmentation.sql', 1);

COMMIT;
PROMPT Migration V1_18 completed and registered in SCHEMA_VERSION successfully.
