-- ====================================================================
-- HRMS Enterprise Database Migration Script
-- Version: V1_10
-- Description: 
--   1. Xoá trường MAKYCONG trong TB_NHANVIEN_PHUCAP, khử trùng lặp dữ liệu, tái tạo PK (MANV, IDPC).
--   2. Chuyển đổi cột NOIDUNG trong TB_HOPDONG từ NCLOB sang VARCHAR2(4000 CHAR).
--   3. Đăng ký bổ sung quyền F_NV_LOAIHOPDONG và F_CC_NGAYLE trong TB_SYS_FUNCTION & TB_SYS_RIGHT.
-- ====================================================================

-- 1. CHUẨN HÓA BẢNG TB_NHANVIEN_PHUCAP
-- Khử trùng lặp bản ghi phụ cấp theo kỳ công cũ, giữ lại 1 bản ghi duy nhất cho mỗi cặp (MANV, IDPC)
DELETE FROM TB_NHANVIEN_PHUCAP 
WHERE ROWID NOT IN (
    SELECT MIN(ROWID) 
    FROM TB_NHANVIEN_PHUCAP 
    GROUP BY MANV, IDPC
);
COMMIT;

-- Xóa ràng buộc khóa chính cũ
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TB_NHANVIEN_PHUCAP DROP CONSTRAINT TB_NHANVIEN_PHUCAP_PK';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- Xóa cột MAKYCONG
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TB_NHANVIEN_PHUCAP DROP COLUMN MAKYCONG';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- Thiết lập lại khóa chính mới trên (MANV, IDPC)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TB_NHANVIEN_PHUCAP ADD CONSTRAINT TB_NHANVIEN_PHUCAP_PK PRIMARY KEY (MANV, IDPC)';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- 2. CHUYỂN ĐỔI TB_HOPDONG.NOIDUNG TỪ NCLOB SANG VARCHAR2(4000 CHAR)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TB_HOPDONG ADD (NOIDUNG_TEMP VARCHAR2(4000 CHAR))';
    EXECUTE IMMEDIATE 'UPDATE TB_HOPDONG SET NOIDUNG_TEMP = SUBSTR(NOIDUNG, 1, 1000) WHERE NOIDUNG IS NOT NULL';
    COMMIT;
    EXECUTE IMMEDIATE 'ALTER TABLE TB_HOPDONG DROP COLUMN NOIDUNG';
    EXECUTE IMMEDIATE 'ALTER TABLE TB_HOPDONG RENAME COLUMN NOIDUNG_TEMP TO NOIDUNG';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- 3. ĐĂNG KÝ PHÂN QUYỀN HỆ THỐNG CHO CÁC FORM MỚI
MERGE INTO TB_SYS_FUNCTION d
USING (
    SELECT 'F_NV_LOAIHOPDONG' AS FUNCTION_CODE, 36 AS SORT, N'Loại Hợp Đồng' AS DESCRIPTION, 0 AS ISGROUP, 1 AS MENU, 'NV' AS PARENT FROM DUAL
    UNION ALL
    SELECT 'F_CC_NGAYLE' AS FUNCTION_CODE, 58 AS SORT, N'Ngày Lễ' AS DESCRIPTION, 0 AS ISGROUP, 1 AS MENU, 'CC' AS PARENT FROM DUAL
) s
ON (d.FUNCTION_CODE = s.FUNCTION_CODE)
WHEN NOT MATCHED THEN
    INSERT (FUNCTION_CODE, SORT, DESCRIPTION, ISGROUP, MENU, PARENT)
    VALUES (s.FUNCTION_CODE, s.SORT, s.DESCRIPTION, s.ISGROUP, s.MENU, s.PARENT);
COMMIT;

-- Cấp quyền admin mặc định
MERGE INTO TB_SYS_RIGHT d
USING (
    SELECT 'F_NV_LOAIHOPDONG' AS FUNCTION_CODE, 1 AS IDUSER, 1 AS USER_RIGHT FROM DUAL
    UNION ALL
    SELECT 'F_CC_NGAYLE' AS FUNCTION_CODE, 1 AS IDUSER, 1 AS USER_RIGHT FROM DUAL
    UNION ALL
    SELECT 'F_CC_TANGCA' AS FUNCTION_CODE, 1 AS IDUSER, 1 AS USER_RIGHT FROM DUAL
) s
ON (d.FUNCTION_CODE = s.FUNCTION_CODE AND d.IDUSER = s.IDUSER)
WHEN MATCHED THEN
    UPDATE SET d.USER_RIGHT = s.USER_RIGHT
WHEN NOT MATCHED THEN
    INSERT (FUNCTION_CODE, IDUSER, USER_RIGHT)
    VALUES (s.FUNCTION_CODE, s.IDUSER, s.USER_RIGHT);
COMMIT;
