-- ==============================================================================
-- Rollback V1_15: Revert Enterprise Authentication, Sessions & Audit
-- ==============================================================================

SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

-- 1. Drop Tables
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_AUTH_SESSION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_AUTH_LOGIN_ATTEMPT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_AUTH_AUDIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TB_AUTH_POLICY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. Drop Columns from TB_SYS_USER
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE TB_SYS_USER DROP (TOKEN_VERSION, FIRST_FAILED_LOGIN_AT, LAST_FAILED_LOGIN_AT, LAST_SUCCESS_LOGIN_AT, LOCK_REASON)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

COMMIT;
