-- ==============================================================================
-- Migration V1_14 Rollback: Revert Overtime Workflow Hardening & Constraints
-- Version: V1_14_rollback
-- Database: Oracle 21c (HR schema)
-- ==============================================================================

SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

-- 1. Xóa ràng buộc và cột liên kết trong TB_TANGCA
ALTER TABLE HR.TB_TANGCA DROP CONSTRAINT FK_TANGCA_OT_REQUEST;
DROP INDEX HR.IX_TANGCA_OT_REQ;
ALTER TABLE HR.TB_TANGCA DROP COLUMN OT_REQUEST_ID;

-- 2. Xóa các ràng buộc và index trong TB_YEUCAU_TANGCA
ALTER TABLE HR.TB_YEUCAU_TANGCA DROP CONSTRAINT CK_YEUCAU_TC_HOURS;
ALTER TABLE HR.TB_YEUCAU_TANGCA DROP CONSTRAINT CK_YEUCAU_TC_STATUS;
ALTER TABLE HR.TB_YEUCAU_TANGCA DROP CONSTRAINT FK_YEUCAU_TC_APPROVER;
ALTER TABLE HR.TB_YEUCAU_TANGCA DROP CONSTRAINT FK_YEUCAU_TC_LOAICA;
DROP INDEX HR.UQ_YEUCAU_TC_ACTIVE;
DROP INDEX HR.IX_YEUCAU_TC_STATUS_DATE;
DROP INDEX HR.IX_YEUCAU_TC_APPROVER;
DROP INDEX HR.IX_YEUCAU_TC_IDCA;

-- 3. Xóa các ràng buộc trong TB_YEUCAU_NGHIPHEP
ALTER TABLE HR.TB_YEUCAU_NGHIPHEP DROP CONSTRAINT CK_YEUCAU_NP_STATUS;
ALTER TABLE HR.TB_YEUCAU_NGHIPHEP DROP CONSTRAINT CK_YEUCAU_NP_DAYS;
ALTER TABLE HR.TB_YEUCAU_NGHIPHEP DROP CONSTRAINT FK_YEUCAU_NP_APPROVER;

-- 4. Xóa các ràng buộc trong TB_YEUCAU_DIEUCHINHCONG
ALTER TABLE HR.TB_YEUCAU_DIEUCHINHCONG DROP CONSTRAINT CK_YEUCAU_DC_STATUS;
ALTER TABLE HR.TB_YEUCAU_DIEUCHINHCONG DROP CONSTRAINT FK_YEUCAU_DC_APPROVER;

COMMIT;
