-- Rollback Migration V1_20: Revert payroll payment status and audit
BEGIN
    IF SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') <> 'HR' THEN
        RAISE_APPLICATION_ERROR(-20000, 'HR schema required');
    END IF;
END;
/

DROP TABLE TB_PAYROLL_PAYMENT_LOG CASCADE CONSTRAINTS
/

ALTER TABLE TB_BANGLUONG DROP (
    TRANGTHAI_CHITRA,
    NGAY_CHITRA,
    SO_LENH_CHI,
    NGUON_CHI_TRA,
    MA_GIAO_DICH_NH,
    GHI_CHU_CHITRA
)
/

ALTER TABLE TB_KYCONG DROP (
    TRANGTHAI_CHITRA,
    NGAY_CHITRA,
    NGUOI_CHITRA,
    GHI_CHU_CHITRA
)
/
