-- Execute as DBA after owner migration; read-only verification. Any bypass stops deployment.
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
DECLARE v_count NUMBER; BEGIN
 SELECT COUNT(*) INTO v_count FROM DBA_TAB_PRIVS p JOIN DBA_TABLES t ON t.OWNER=p.OWNER AND t.TABLE_NAME=p.TABLE_NAME WHERE p.GRANTEE IN ('AI_READONLY','PUBLIC') AND p.OWNER='HR';
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20020,'Reader still has raw HR table grants'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_TAB_PRIVS WHERE TABLE_NAME='PKG_AI_TICKET' AND OWNER='HR' AND GRANTEE IN ('AI_READONLY','PUBLIC');
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20021,'Ticket issuer exposed'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_SYS_PRIVS WHERE GRANTEE='AI_READONLY' AND PRIVILEGE<>'CREATE SESSION';
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20022,'Reader has system privileges beyond CREATE SESSION'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_ROLE_PRIVS WHERE GRANTEE='AI_READONLY';
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20023,'Reader roles require removal after DBA review'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_VIEWS WHERE OWNER='AI_READONLY';
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20024,'Legacy reader-owned views require inventory and removal; runtime uses HR-qualified views'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_TAB_PRIVS WHERE GRANTEE IN ('AI_READONLY','PUBLIC') AND OWNER='HR' AND TABLE_NAME NOT IN
 ('V_AI_EMPLOYEE_LOOKUP','V_AI_EMPLOYEE_COUNT','V_AI_OVERTIME_SUMMARY','V_AI_EMPLOYEE','V_AI_ORG_LOOKUP','V_AI_PERIOD','V_AI_OVERTIME','V_AI_ALLOWANCE','V_AI_INSURANCE','V_AI_ADVANCE','V_AI_ATTENDANCE_SUMMARY','V_AI_PAYROLL','V_AI_PAYROLL_SUMMARY','V_AI_CONTRACT','V_AI_SALARY_CHANGE','PKG_AI_READER');
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20026,'Unapproved HR objects accessible to reader or PUBLIC'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_TAB_PRIVS WHERE GRANTEE='AI_READONLY' AND OWNER<>'SYS' AND OWNER<>'HR';
 IF v_count>0 THEN RAISE_APPLICATION_ERROR(-20027,'Cross-schema reader grants need removal/review'); END IF;
 SELECT COUNT(*) INTO v_count FROM DBA_CONTEXT WHERE NAMESPACE='HRMS_AI_CTX' AND SCHEMA='HR' AND PACKAGE='PKG_AI_READER';
 IF v_count<>1 THEN RAISE_APPLICATION_ERROR(-20025,'Trusted context missing'); END IF;
END;
/
SELECT NAME,TYPE,LINE,POSITION,TEXT FROM DBA_ERRORS WHERE OWNER='HR' AND (NAME LIKE 'PKG_AI_%' OR NAME LIKE 'TR_AI_%' OR NAME LIKE 'V_AI_%') ORDER BY NAME,SEQUENCE;
-- As AI_READONLY without a bound ticket: these must all return zero rows.
-- SELECT COUNT(*) FROM HR.V_AI_EMPLOYEE_LOOKUP;
-- SELECT COUNT(*) FROM HR.V_AI_PAYROLL;
-- SELECT COUNT(*) FROM HR.V_AI_PAYROLL_SUMMARY;
-- SELECT COUNT(*) FROM HR.V_AI_ORG_LOOKUP;
-- SELECT COUNT(*) FROM HR.V_AI_PERIOD;