-- ============================================================================
-- SCRIPT 1: V1_24_ai_owner_dba_setup.sql
-- Thao tác phân quyền mức Quản trị Hệ thống (DBA) cho Kiến trúc AI V2 (Nhánh B2)
-- Người chạy: DBA (SYS AS SYSDBA hoặc User có quyền DBA)
-- Yêu cầu: Không chạy tự động, chỉ chạy khi có phê duyệt của DBA.
-- Không chứa mật khẩu thật (sử dụng placeholder do DBA đặt trong cửa sổ bảo trì).
-- ============================================================================

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON SIZE UNLIMITED;

PROMPT [1/6] Kiem tra phien DBA...
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS CURRENT_DBA_USER FROM DUAL;

-- 1. Tao User AI_OWNER neu chua ton tai
PROMPT [2/6] Khoi tao User AI_OWNER so huu he thong chinh sach va protected views...
DECLARE
    v_user_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_user_count FROM ALL_USERS WHERE USERNAME = 'AI_OWNER';
    IF v_user_count = 0 THEN
        -- DBA thay doi mat khau phu hop voi chinh sach mat khau cua don vi
        EXECUTE IMMEDIATE 'CREATE USER AI_OWNER IDENTIFIED BY "AiOwner#2026_SecureKey" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
        DBMS_OUTPUT.PUT_LINE('-> User AI_OWNER da duoc tao moi.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('-> User AI_OWNER da ton tai, bo qua buoc CREATE.');
    END IF;
END;
/

-- 2. Cap quyen he thong toi thieu cho AI_OWNER (Khong cap DBA, khong cap ANY privilege)
PROMPT [3/6] Cap quyen doi tuong cho AI_OWNER...
GRANT CREATE SESSION TO AI_OWNER;
GRANT CREATE TABLE TO AI_OWNER;
GRANT CREATE VIEW TO AI_OWNER;
GRANT CREATE PROCEDURE TO AI_OWNER;
GRANT CREATE SEQUENCE TO AI_OWNER;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO AI_OWNER;

-- 3. Tao Trusted Context HRMS_AI_CTX tro den package AI_OWNER.PKG_AI_READER
PROMPT [4/6] Tao Trusted Context HRMS_AI_CTX...
CREATE OR REPLACE CONTEXT HRMS_AI_CTX USING AI_OWNER.PKG_AI_READER;

-- 4. Cap quyen WITH GRANT OPTION tu HR cho AI_OWNER tren cac View nguon V_AI_SRC_*
-- Luu y: Theo quy dinh Oracle (ORA-01720), AI_OWNER bat buoc phai co WITH GRANT OPTION
-- tren cac view nguon de co the GRANT SELECT view bao ve cho AI_READONLY.
PROMPT [5/6] Cap WITH GRANT OPTION tren cac View nguon cua HR cho AI_OWNER...
BEGIN
    -- Tao cac View nguon V_AI_SRC_* trong schema HR neu chua co
    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_EMPLOYEE AS
    SELECT nv.MANV, nv.HOTEN, nv.NGAYSINH, nv.DIACHI, nv.DIENTHOAI, nv.IDPB, pb.TENPB AS TEN_PHONGBAN,
           nv.IDCV, cv.TENCV AS TEN_CHUCVU, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY, nv.DATHOIVIEC, nv.DELETED_DATE
    FROM HR.TB_NHANVIEN nv
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB
    LEFT JOIN HR.TB_CHUCVU cv ON cv.IDCV = nv.IDCV';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_PHONGBAN AS
    SELECT IDPB, TENPB FROM HR.TB_PHONGBAN';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_CHUCVU AS
    SELECT IDCV, TENCV FROM HR.TB_CHUCVU';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_TANGCA AS
    SELECT tc.IDTCA, tc.MANV, nv.HOTEN, tc.NGAY, tc.THANG, tc.NAM, tc.SOGIO, tc.IDLOAICA,
           tc.DELETED_DATE, nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY
    FROM HR.TB_TANGCA tc
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = tc.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_PHUCAP AS
    SELECT pc.IDPC, pc.TENPC, npc.MANV, nv.HOTEN, npc.SOTIEN, npc.TU_NGAY, npc.DEN_NGAY,
           npc.DELETED_DATE, nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY
    FROM HR.TB_NHANVIEN_PHUCAP npc
    JOIN HR.TB_PHUCAP pc ON pc.IDPC = npc.IDPC
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = npc.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_UNGLUONG AS
    SELECT ul.IDUL, ul.MANV, nv.HOTEN, ul.NGAY, ul.THANG, ul.NAM, ul.SOTIENUNG,
           ul.DELETED_DATE, nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY
    FROM HR.TB_UNGLUONG ul
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = ul.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_BAOHIEM AS
    SELECT bh.IDBH, bh.MANV, nv.HOTEN, bh.SOBH, bh.NGAYCAP, bh.NOICAP, bh.NOIKHAMBENH,
           nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY, nv.DELETED_DATE
    FROM HR.TB_BAOHIEM bh
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = bh.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_ATTENDANCE AS
    SELECT ct.MAKYCONG, ct.MANV, nv.HOTEN, kc.THANG, kc.NAM, ct.TONGNGAYCONG, ct.NGAYPHEP,
           ct.NGHIKHONGPHEP, ct.CONGNGAYLE, ct.CONGCHUNHAT, kc.CONG_PUBLISH_REV, kc.TRANGTHAI,
           kc.DELETED_DATE, nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY
    FROM HR.TB_KYCONGCHITIET ct
    JOIN HR.TB_KYCONG kc ON kc.MAKYCONG = ct.MAKYCONG
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = ct.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_HOPDONG AS
    SELECT hd.SOHD, hd.MANV, nv.HOTEN, hd.NGAYBATDAU, hd.NGAYKETTHUC, hd.NGAYKY, hd.LANKY,
           hd.HESOLUONG, hd.DEL_DATE, nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY
    FROM HR.TB_HOPDONG hd
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = hd.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_NANGLUONG AS
    SELECT nl.SOQDNL, nl.SOHD, nl.MANV, nv.HOTEN, nl.NGAYKYNL, nl.NGAYLENLUONG, nl.HESOLUONG_NOW,
           nl.HESOLUONG_NEW, nl.DELETED_DATE, nv.IDPB, pb.TENPB AS TEN_PHONGBAN, TO_CHAR(nv.IDCTY, ''TM9'') AS MACTY
    FROM HR.TB_NANGLUONG_NHANVIEN nl
    JOIN HR.TB_NHANVIEN nv ON nv.MANV = nl.MANV
    LEFT JOIN HR.TB_PHONGBAN pb ON pb.IDPB = nv.IDPB';

    EXECUTE IMMEDIATE '
    CREATE OR REPLACE VIEW HR.V_AI_SRC_AUTH AS
    SELECT u.IDUSER, u.USERNAME, u.FULLNAME, u.MANV, u.MACTY, u.DISABLED, u.ISGROUP,
           nv.IDPB,
           g.ID_GROUP, r.FUNCTION_CODE, r.CAN_VIEW, r.USER_RIGHT
    FROM HR.TB_SYS_USER u
    LEFT JOIN HR.TB_NHANVIEN nv ON nv.MANV = u.MANV
    LEFT JOIN HR.TB_SYS_GROUP g ON g.MEMBER = u.IDUSER
    LEFT JOIN HR.TB_SYS_RIGHT r ON r.IDUSER = u.IDUSER OR r.IDUSER = g.ID_GROUP';

    -- Cap quyen WITH GRANT OPTION cho AI_OWNER
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_EMPLOYEE TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_PHONGBAN TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_CHUCVU TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_TANGCA TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_PHUCAP TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_UNGLUONG TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_BAOHIEM TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_ATTENDANCE TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_HOPDONG TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_NANGLUONG TO AI_OWNER WITH GRANT OPTION';
    EXECUTE IMMEDIATE 'GRANT SELECT ON HR.V_AI_SRC_AUTH TO AI_OWNER WITH GRANT OPTION';
    DBMS_OUTPUT.PUT_LINE('-> Da cap WITH GRANT OPTION cac View nguon cho AI_OWNER.');
END;
/

-- 5. Thu hoi quyen rong va bao ve tai khoan AI_READONLY
PROMPT [6/6] Chuan hoa quyen tai khoan AI_READONLY...
BEGIN
    -- Dam bao AI_READONLY co CREATE SESSION
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO AI_READONLY';

    -- Thu hoi cac system privilege qua rong (neu co)
    FOR r IN (SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'AI_READONLY' AND PRIVILEGE IN ('SELECT ANY TABLE', 'CREATE VIEW', 'CREATE ANY TABLE', 'DROP ANY TABLE')) LOOP
        EXECUTE IMMEDIATE 'REVOKE ' || r.PRIVILEGE || ' FROM AI_READONLY';
        DBMS_OUTPUT.PUT_LINE('-> Da thu hoi ' || r.PRIVILEGE || ' tu AI_READONLY.');
    END LOOP;

    -- Thu hoi cac roles (ke ca CONNECT) de chi giu quyen truc tiep CREATE SESSION
    FOR ro IN (SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'AI_READONLY') LOOP
        EXECUTE IMMEDIATE 'REVOKE ' || ro.GRANTED_ROLE || ' FROM AI_READONLY';
        DBMS_OUTPUT.PUT_LINE('-> Da thu hoi role ' || ro.GRANTED_ROLE || ' tu AI_READONLY.');
    END LOOP;

    -- Thu hoi direct table grants tren bang goc HR (neu co)
    FOR t IN (SELECT TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE = 'AI_READONLY' AND OWNER = 'HR' AND TABLE_NAME LIKE 'TB_%') LOOP
        EXECUTE IMMEDIATE 'REVOKE ALL ON HR.' || t.TABLE_NAME || ' FROM AI_READONLY';
        DBMS_OUTPUT.PUT_LINE('-> Da thu hoi quyen truc tiep tren HR.' || t.TABLE_NAME || ' tu AI_READONLY.');
    END LOOP;
END;
/

PROMPT ============================================================================
PROMPT HOAN TAT THIET LAP DBA: AI_OWNER da san sang; Context da lien ket; AI_READONLY da an toan.
PROMPT ============================================================================
