-- ============================================================================
-- SCRIPT: V1_26__ai_rag_v2_index_sync_and_qdrant_foundation.sql
-- Thiet lap nen tang Indexing, Outbox dong bo, Registry va PKG_AI_INDEX cho AI_OWNER
-- Nguoi so huu: AI_OWNER
-- Nguoi thuc thi: DBA hoac sysdba
-- ============================================================================

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET DEFINE OFF;

PROMPT [1/6] Chuyen ve schema AI_OWNER...
ALTER SESSION SET CURRENT_SCHEMA = AI_OWNER;

PROMPT [2/6] Tao 4 bang metadata va dong bo index...

-- 1. TB_AI_INDEX_SOURCE: Allowlist nguon index
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE TB_AI_INDEX_SOURCE (
        SOURCE_CODE         VARCHAR2(50) NOT NULL,
        DOMAIN              VARCHAR2(50) NOT NULL,
        READER_VIEW_OR_API  VARCHAR2(100) NOT NULL,
        KEY_STRATEGY        VARCHAR2(50) NOT NULL,
        VERSION_STRATEGY    VARCHAR2(50) NOT NULL,
        PROJECTION_VERSION  NUMBER DEFAULT 1 NOT NULL,
        VISIBILITY_VERSION  NUMBER DEFAULT 1 NOT NULL,
        IS_ENABLED          NUMBER(1) DEFAULT 1 NOT NULL,
        CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT          DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_AI_INDEX_SOURCE PRIMARY KEY (SOURCE_CODE)
    )';
    DBMS_OUTPUT.PUT_LINE('Da tao bang TB_AI_INDEX_SOURCE.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Bang TB_AI_INDEX_SOURCE da ton tai.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 2. TB_AI_INDEX_REGISTRY: Manifest versioned collection
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE TB_AI_INDEX_REGISTRY (
        INDEX_ID            VARCHAR2(100) NOT NULL,
        PHYSICAL_COLLECTION VARCHAR2(100) NOT NULL,
        ALIAS_NAME          VARCHAR2(100) NOT NULL,
        ENDPOINT_REF        VARCHAR2(200) NOT NULL,
        MODEL_DIGEST        VARCHAR2(100) NOT NULL,
        VECTOR_DIMENSION    NUMBER DEFAULT 1024 NOT NULL,
        DISTANCE_METRIC     VARCHAR2(20) DEFAULT ''Cosine'' NOT NULL,
        SCHEMA_VERSION      NUMBER DEFAULT 1 NOT NULL,
        CHUNK_VERSION       NUMBER DEFAULT 1 NOT NULL,
        EPOCH               NUMBER DEFAULT 1 NOT NULL,
        STATUS              VARCHAR2(20) DEFAULT ''BUILDING'' NOT NULL,
        CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
        ACTIVATED_AT        DATE,
        RETIRED_AT          DATE,
        CONSTRAINT PK_AI_INDEX_REGISTRY PRIMARY KEY (INDEX_ID),
        CONSTRAINT CK_AI_INDEX_STATUS CHECK (STATUS IN (''BUILDING'', ''VALIDATED'', ''ACTIVE'', ''RETIRED''))
    )';
    DBMS_OUTPUT.PUT_LINE('Da tao bang TB_AI_INDEX_REGISTRY.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Bang TB_AI_INDEX_REGISTRY da ton tai.');
        ELSE
            RAISE;
        END IF;
END;
/

-- 3. TB_AI_INDEX_OUTBOX: Queue dong bo ben vung (chi ID va version, khong chua PII)
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE TB_AI_INDEX_OUTBOX (
        EVENT_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        SOURCE_CODE         VARCHAR2(50) NOT NULL,
        ENTITY_KEY          VARCHAR2(100) NOT NULL,
        ACTION              VARCHAR2(20) NOT NULL,
        SOURCE_VERSION      NUMBER DEFAULT 1 NOT NULL,
        STATUS              VARCHAR2(20) DEFAULT ''PENDING'' NOT NULL,
        LEASE_OWNER         VARCHAR2(100),
        LEASE_EXPIRY        DATE,
        ATTEMPTS            NUMBER DEFAULT 0 NOT NULL,
        NEXT_RETRY_AT       DATE DEFAULT SYSDATE NOT NULL,
        ERROR_CODE          VARCHAR2(50),
        ERROR_MESSAGE       VARCHAR2(500),
        CREATED_AT          DATE DEFAULT SYSDATE NOT NULL,
        PROCESSED_AT        DATE,
        CONSTRAINT CK_AI_OUTBOX_STATUS CHECK (STATUS IN (''PENDING'', ''LEASED'', ''PROCESSED'', ''DEAD_LETTER'')),
        CONSTRAINT CK_AI_OUTBOX_ACTION CHECK (ACTION IN (''UPSERT'', ''DELETE''))
    )';
    DBMS_OUTPUT.PUT_LINE('Da tao bang TB_AI_INDEX_OUTBOX.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Bang TB_AI_INDEX_OUTBOX da ton tai.');
        ELSE
            RAISE;
        END IF;
END;
/

-- Index toi uu cho queue polling
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_AI_OUTBOX_STATUS ON TB_AI_INDEX_OUTBOX(STATUS, NEXT_RETRY_AT, EVENT_ID)';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE <> -955 AND SQLCODE <> -1408 THEN RAISE; END IF;
END;
/

-- 4. TB_AI_INDEX_CHECKPOINT: Theo doi tien trinh per-index
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE TB_AI_INDEX_CHECKPOINT (
        INDEX_ID            VARCHAR2(100) NOT NULL,
        SOURCE_CODE         VARCHAR2(50) NOT NULL,
        CURSOR_MARKER       VARCHAR2(200),
        VERIFIED_PROGRESS   NUMBER DEFAULT 0 NOT NULL,
        LEASE_OWNER         VARCHAR2(100),
        LEASE_EXPIRY        DATE,
        STATUS              VARCHAR2(20) DEFAULT ''ACTIVE'' NOT NULL,
        UPDATED_AT          DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_AI_INDEX_CHECKPOINT PRIMARY KEY (INDEX_ID, SOURCE_CODE)
    )';
    DBMS_OUTPUT.PUT_LINE('Da tao bang TB_AI_INDEX_CHECKPOINT.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Bang TB_AI_INDEX_CHECKPOINT da ton tai.');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT [3/6] Khoi tao du lieu seed cho Index Sources va Registry ban dau...

MERGE INTO TB_AI_INDEX_SOURCE t
USING (
    SELECT 'SRC_PHONGBAN' AS sc, 'ORGANIZATION' AS dom, 'V_AI_SRC_PHONGBAN' AS api, 'IDPB' AS ks, 'TB_AI_REVISION' AS vs FROM DUAL UNION ALL
    SELECT 'SRC_CHUCVU', 'ORGANIZATION', 'V_AI_SRC_CHUCVU', 'IDCV', 'TB_AI_REVISION' FROM DUAL UNION ALL
    SELECT 'SRC_EMPLOYEE', 'HUMAN_RESOURCE', 'V_AI_SRC_EMPLOYEE', 'MANV', 'TB_AI_REVISION' FROM DUAL
) s ON (t.SOURCE_CODE = s.sc)
WHEN NOT MATCHED THEN
    INSERT (SOURCE_CODE, DOMAIN, READER_VIEW_OR_API, KEY_STRATEGY, VERSION_STRATEGY, PROJECTION_VERSION, VISIBILITY_VERSION, IS_ENABLED)
    VALUES (s.sc, s.dom, s.api, s.ks, s.vs, 1, 1, 1);

MERGE INTO TB_AI_INDEX_REGISTRY t
USING (
    SELECT 'idx_hrms_mapped_v2_init' AS iid, 'hrms_mapped_v2_init' AS pc, 'hrms_mapped_active' AS an,
           'LOCAL_QDRANT_DEFAULT' AS er, 'bge-m3:latest' AS md, 1024 AS dim, 'Cosine' AS met,
           1 AS sv, 1 AS cv, 1 AS ep, 'BUILDING' AS st FROM DUAL
) s ON (t.INDEX_ID = s.iid)
WHEN NOT MATCHED THEN
    INSERT (INDEX_ID, PHYSICAL_COLLECTION, ALIAS_NAME, ENDPOINT_REF, MODEL_DIGEST, VECTOR_DIMENSION, DISTANCE_METRIC, SCHEMA_VERSION, CHUNK_VERSION, EPOCH, STATUS)
    VALUES (s.iid, s.pc, s.an, s.er, s.md, s.dim, s.met, s.sv, s.cv, s.ep, s.st);

COMMIT;

PROMPT [4/6] Tao Package PKG_AI_INDEX (AUTHID DEFINER)...

CREATE OR REPLACE PACKAGE PKG_AI_INDEX AUTHID DEFINER AS
    -- Enqueue su kien dong bo tu trigger hoac service backend
    PROCEDURE ENQUEUE_EVENT(
        p_source_code    IN VARCHAR2,
        p_entity_key     IN VARCHAR2,
        p_action         IN VARCHAR2,
        p_source_version IN NUMBER DEFAULT 1
    );

    -- Worker lease batch su kien de xu ly
    PROCEDURE CLAIM_EVENTS(
        p_worker_id      IN VARCHAR2,
        p_batch_size     IN NUMBER,
        p_lease_seconds  IN NUMBER,
        p_events_cur     OUT SYS_REFCURSOR
    );

    -- Xac nhan da dong bo thanh cong vao Qdrant
    PROCEDURE ACK_EVENT(
        p_event_id       IN NUMBER,
        p_index_id       IN VARCHAR2,
        p_version        IN NUMBER
    );

    -- Bao loi dong bo co backoff/dead-letter
    PROCEDURE FAIL_EVENT(
        p_event_id       IN NUMBER,
        p_error_code     IN VARCHAR2,
        p_error_msg      IN VARCHAR2,
        p_max_attempts   IN NUMBER DEFAULT 5
    );

    -- Doc manifest dang active (hoac building neu chua co active)
    PROCEDURE READ_ACTIVE_MANIFEST(
        p_alias_name     IN VARCHAR2,
        p_manifest_cur   OUT SYS_REFCURSOR
    );

    -- Dang ky collection version moi
    PROCEDURE REGISTER_INDEX(
        p_index_id            IN VARCHAR2,
        p_physical_collection IN VARCHAR2,
        p_alias_name          IN VARCHAR2,
        p_endpoint_ref        IN VARCHAR2,
        p_model_digest        IN VARCHAR2,
        p_dimension           IN NUMBER,
        p_metric              IN VARCHAR2
    );

    -- Kich hoat collection (cutover sau khi kiem tra pass)
    PROCEDURE ACTIVATE_INDEX(
        p_index_id       IN VARCHAR2
    );

    -- Doc checkpoint dong bo
    PROCEDURE READ_CHECKPOINT(
        p_index_id       IN VARCHAR2,
        p_source_code    IN VARCHAR2,
        p_ckpt_cur       OUT SYS_REFCURSOR
    );

    -- Cap nhat checkpoint dong bo
    PROCEDURE UPDATE_CHECKPOINT(
        p_index_id       IN VARCHAR2,
        p_source_code    IN VARCHAR2,
        p_cursor_marker  IN VARCHAR2,
        p_progress       IN NUMBER
    );

    -- Doc tong quan trang thai outbox & worker
    PROCEDURE READ_SYNC_STATUS(
        p_status_cur     OUT SYS_REFCURSOR
    );

    -- Doc du lieu phan trang cua approved sources phuc vu bootstrap (chi metadata/an toan tu V_AI_SRC_*)
    PROCEDURE READ_INDEX_PAGE(
        p_source_code    IN VARCHAR2,
        p_page_size      IN NUMBER,
        p_offset         IN NUMBER,
        p_data_cur       OUT SYS_REFCURSOR
    );
END PKG_AI_INDEX;
/

CREATE OR REPLACE PACKAGE BODY PKG_AI_INDEX AS

    PROCEDURE ENQUEUE_EVENT(
        p_source_code    IN VARCHAR2,
        p_entity_key     IN VARCHAR2,
        p_action         IN VARCHAR2,
        p_source_version IN NUMBER DEFAULT 1
    ) IS
    BEGIN
        INSERT INTO TB_AI_INDEX_OUTBOX (
            SOURCE_CODE, ENTITY_KEY, ACTION, SOURCE_VERSION, STATUS, CREATED_AT, NEXT_RETRY_AT
        ) VALUES (
            p_source_code, p_entity_key, UPPER(TRIM(p_action)), p_source_version, 'PENDING', SYSDATE, SYSDATE
        );
    END ENQUEUE_EVENT;

    PROCEDURE CLAIM_EVENTS(
        p_worker_id      IN VARCHAR2,
        p_batch_size     IN NUMBER,
        p_lease_seconds  IN NUMBER,
        p_events_cur     OUT SYS_REFCURSOR
    ) IS
        v_now DATE := SYSDATE;
        v_expiry DATE := SYSDATE + (NVL(p_lease_seconds, 60) / 86400);
        v_limit NUMBER := NVL(p_batch_size, 50);
    BEGIN
        -- Coalesce/Update lease atomic
        UPDATE TB_AI_INDEX_OUTBOX
        SET STATUS = 'LEASED',
            LEASE_OWNER = p_worker_id,
            LEASE_EXPIRY = v_expiry,
            ATTEMPTS = ATTEMPTS + 1
        WHERE EVENT_ID IN (
            SELECT EVENT_ID FROM (
                SELECT EVENT_ID
                FROM TB_AI_INDEX_OUTBOX
                WHERE (STATUS = 'PENDING' AND NEXT_RETRY_AT <= v_now)
                   OR (STATUS = 'LEASED' AND LEASE_EXPIRY < v_now)
                ORDER BY EVENT_ID ASC
            )
            WHERE ROWNUM <= v_limit
        );

        -- Tra ve cac ban ghi da duoc lease cho worker nay
        OPEN p_events_cur FOR
            SELECT EVENT_ID, SOURCE_CODE, ENTITY_KEY, ACTION, SOURCE_VERSION, ATTEMPTS
            FROM TB_AI_INDEX_OUTBOX
            WHERE STATUS = 'LEASED' AND LEASE_OWNER = p_worker_id AND LEASE_EXPIRY = v_expiry
            ORDER BY EVENT_ID ASC;
    END CLAIM_EVENTS;

    PROCEDURE ACK_EVENT(
        p_event_id       IN NUMBER,
        p_index_id       IN VARCHAR2,
        p_version        IN NUMBER
    ) IS
    BEGIN
        UPDATE TB_AI_INDEX_OUTBOX
        SET STATUS = 'PROCESSED',
            PROCESSED_AT = SYSDATE,
            LEASE_OWNER = NULL,
            LEASE_EXPIRY = NULL
        WHERE EVENT_ID = p_event_id;
    END ACK_EVENT;

    PROCEDURE FAIL_EVENT(
        p_event_id       IN NUMBER,
        p_error_code     IN VARCHAR2,
        p_error_msg      IN VARCHAR2,
        p_max_attempts   IN NUMBER DEFAULT 5
    ) IS
        v_attempts NUMBER;
        v_delay_sec NUMBER;
    BEGIN
        SELECT ATTEMPTS INTO v_attempts FROM TB_AI_INDEX_OUTBOX WHERE EVENT_ID = p_event_id;

        IF v_attempts >= NVL(p_max_attempts, 5) THEN
            UPDATE TB_AI_INDEX_OUTBOX
            SET STATUS = 'DEAD_LETTER',
                ERROR_CODE = SUBSTR(p_error_code, 1, 50),
                ERROR_MESSAGE = SUBSTR(p_error_msg, 1, 500),
                LEASE_OWNER = NULL,
                LEASE_EXPIRY = NULL
            WHERE EVENT_ID = p_event_id;
        ELSE
            -- Exponential backoff: 30s * 2^(attempts-1)
            v_delay_sec := 30 * POWER(2, LEAST(v_attempts - 1, 6));
            UPDATE TB_AI_INDEX_OUTBOX
            SET STATUS = 'PENDING',
                NEXT_RETRY_AT = SYSDATE + (v_delay_sec / 86400),
                ERROR_CODE = SUBSTR(p_error_code, 1, 50),
                ERROR_MESSAGE = SUBSTR(p_error_msg, 1, 500),
                LEASE_OWNER = NULL,
                LEASE_EXPIRY = NULL
            WHERE EVENT_ID = p_event_id;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN NULL;
    END FAIL_EVENT;

    PROCEDURE READ_ACTIVE_MANIFEST(
        p_alias_name     IN VARCHAR2,
        p_manifest_cur   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_manifest_cur FOR
            SELECT INDEX_ID, PHYSICAL_COLLECTION, ALIAS_NAME, ENDPOINT_REF,
                   MODEL_DIGEST, VECTOR_DIMENSION, DISTANCE_METRIC,
                   SCHEMA_VERSION, CHUNK_VERSION, EPOCH, STATUS
            FROM (
                SELECT * FROM TB_AI_INDEX_REGISTRY
                WHERE ALIAS_NAME = p_alias_name
                ORDER BY CASE STATUS WHEN 'ACTIVE' THEN 1 WHEN 'VALIDATED' THEN 2 WHEN 'BUILDING' THEN 3 ELSE 4 END, CREATED_AT DESC
            )
            WHERE ROWNUM = 1;
    END READ_ACTIVE_MANIFEST;

    PROCEDURE REGISTER_INDEX(
        p_index_id            IN VARCHAR2,
        p_physical_collection IN VARCHAR2,
        p_alias_name          IN VARCHAR2,
        p_endpoint_ref        IN VARCHAR2,
        p_model_digest        IN VARCHAR2,
        p_dimension           IN NUMBER,
        p_metric              IN VARCHAR2
    ) IS
    BEGIN
        MERGE INTO TB_AI_INDEX_REGISTRY t
        USING (SELECT p_index_id iid FROM DUAL) s ON (t.INDEX_ID = s.iid)
        WHEN NOT MATCHED THEN
            INSERT (INDEX_ID, PHYSICAL_COLLECTION, ALIAS_NAME, ENDPOINT_REF, MODEL_DIGEST, VECTOR_DIMENSION, DISTANCE_METRIC, STATUS, CREATED_AT)
            VALUES (p_index_id, p_physical_collection, p_alias_name, p_endpoint_ref, p_model_digest, NVL(p_dimension, 1024), NVL(p_metric, 'Cosine'), 'BUILDING', SYSDATE);
    END REGISTER_INDEX;

    PROCEDURE ACTIVATE_INDEX(
        p_index_id       IN VARCHAR2
    ) IS
        v_alias VARCHAR2(100);
    BEGIN
        SELECT ALIAS_NAME INTO v_alias FROM TB_AI_INDEX_REGISTRY WHERE INDEX_ID = p_index_id;

        -- Retire tat ca index cu cua alias nay
        UPDATE TB_AI_INDEX_REGISTRY
        SET STATUS = 'RETIRED', RETIRED_AT = SYSDATE
        WHERE ALIAS_NAME = v_alias AND INDEX_ID <> p_index_id AND STATUS = 'ACTIVE';

        -- Kich hoat index muc tieu
        UPDATE TB_AI_INDEX_REGISTRY
        SET STATUS = 'ACTIVE', ACTIVATED_AT = SYSDATE
        WHERE INDEX_ID = p_index_id;
    END ACTIVATE_INDEX;

    PROCEDURE READ_CHECKPOINT(
        p_index_id       IN VARCHAR2,
        p_source_code    IN VARCHAR2,
        p_ckpt_cur       OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_ckpt_cur FOR
            SELECT INDEX_ID, SOURCE_CODE, CURSOR_MARKER, VERIFIED_PROGRESS, STATUS, UPDATED_AT
            FROM TB_AI_INDEX_CHECKPOINT
            WHERE INDEX_ID = p_index_id AND SOURCE_CODE = p_source_code;
    END READ_CHECKPOINT;

    PROCEDURE UPDATE_CHECKPOINT(
        p_index_id       IN VARCHAR2,
        p_source_code    IN VARCHAR2,
        p_cursor_marker  IN VARCHAR2,
        p_progress       IN NUMBER
    ) IS
    BEGIN
        MERGE INTO TB_AI_INDEX_CHECKPOINT t
        USING (SELECT p_index_id iid, p_source_code sc FROM DUAL) s
        ON (t.INDEX_ID = s.iid AND t.SOURCE_CODE = s.sc)
        WHEN MATCHED THEN
            UPDATE SET CURSOR_MARKER = p_cursor_marker, VERIFIED_PROGRESS = p_progress, UPDATED_AT = SYSDATE
        WHEN NOT MATCHED THEN
            INSERT (INDEX_ID, SOURCE_CODE, CURSOR_MARKER, VERIFIED_PROGRESS, STATUS, UPDATED_AT)
            VALUES (p_index_id, p_source_code, p_cursor_marker, p_progress, 'ACTIVE', SYSDATE);
    END UPDATE_CHECKPOINT;

    PROCEDURE READ_SYNC_STATUS(
        p_status_cur     OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_status_cur FOR
            SELECT 
                (SELECT COUNT(*) FROM TB_AI_INDEX_OUTBOX WHERE STATUS = 'PENDING') AS PENDING_COUNT,
                (SELECT COUNT(*) FROM TB_AI_INDEX_OUTBOX WHERE STATUS = 'LEASED') AS LEASED_COUNT,
                (SELECT COUNT(*) FROM TB_AI_INDEX_OUTBOX WHERE STATUS = 'PROCESSED') AS PROCESSED_COUNT,
                (SELECT COUNT(*) FROM TB_AI_INDEX_OUTBOX WHERE STATUS = 'DEAD_LETTER') AS DEAD_LETTER_COUNT,
                (SELECT COUNT(*) FROM TB_AI_INDEX_REGISTRY WHERE STATUS = 'ACTIVE') AS ACTIVE_INDEX_COUNT
            FROM DUAL;
    END READ_SYNC_STATUS;

    PROCEDURE READ_INDEX_PAGE(
        p_source_code    IN VARCHAR2,
        p_page_size      IN NUMBER,
        p_offset         IN NUMBER,
        p_data_cur       OUT SYS_REFCURSOR
    ) IS
        v_ps NUMBER := NVL(p_page_size, 100);
        v_off NUMBER := NVL(p_offset, 0);
    BEGIN
        -- TRUY XUAT TU HR.V_AI_SRC_* (Da co grant cho AI_OWNER). KHONG TRUY XUAT BANG GOC HR.TB_*
        IF p_source_code = 'SRC_PHONGBAN' THEN
            OPEN p_data_cur FOR
                SELECT TO_CHAR(pb.IDPB) AS ENTITY_KEY, pb.TENPB AS ENTITY_NAME,
                       'PB' AS ENTITY_TYPE, 'CTY01' AS COMPANY_ID, TO_CHAR(pb.IDPB) AS DEPARTMENT_ID,
                       'PUBLIC_ORG' AS VISIBILITY_PROFILE,
                       ('Phong ban: ' || pb.TENPB) AS PROJECTION_TEXT,
                       1 AS SOURCE_VERSION
                FROM HR.V_AI_SRC_PHONGBAN pb
                ORDER BY pb.IDPB
                OFFSET v_off ROWS FETCH NEXT v_ps ROWS ONLY;

        ELSIF p_source_code = 'SRC_CHUCVU' THEN
            OPEN p_data_cur FOR
                SELECT TO_CHAR(cv.IDCV) AS ENTITY_KEY, cv.TENCV AS ENTITY_NAME,
                       'CV' AS ENTITY_TYPE, 'CTY01' AS COMPANY_ID, 'ALL' AS DEPARTMENT_ID,
                       'PUBLIC_ORG' AS VISIBILITY_PROFILE,
                       ('Chuc vu: ' || cv.TENCV) AS PROJECTION_TEXT,
                       1 AS SOURCE_VERSION
                FROM HR.V_AI_SRC_CHUCVU cv
                ORDER BY cv.IDCV
                OFFSET v_off ROWS FETCH NEXT v_ps ROWS ONLY;

        ELSIF p_source_code = 'SRC_EMPLOYEE' THEN
            -- Chi doc thong tin co ban cong khai (Ten, Phong ban, Chuc vu tu V_AI_SRC_EMPLOYEE).
            -- TUYET DOI KHONG DUA: NGAYSINH, DIENTHOAI, DIACHI, CCCD, LUONG VAO PROJECTION_TEXT!
            OPEN p_data_cur FOR
                SELECT TO_CHAR(nv.MANV) AS ENTITY_KEY, nv.HOTEN AS ENTITY_NAME,
                       'NV' AS ENTITY_TYPE, NVL(nv.MACTY, 'CTY01') AS COMPANY_ID, NVL(TO_CHAR(nv.IDPB), '0') AS DEPARTMENT_ID,
                       'PUBLIC_EMP' AS VISIBILITY_PROFILE,
                       ('Nhan vien: ' || nv.HOTEN || ' - Phong ban: ' || NVL(nv.TEN_PHONGBAN, 'Chua xep') || ' - Chuc vu: ' || NVL(nv.TEN_CHUCVU, 'Nhan vien')) AS PROJECTION_TEXT,
                       1 AS SOURCE_VERSION
                FROM HR.V_AI_SRC_EMPLOYEE nv
                WHERE NVL(nv.DATHOIVIEC, 0) = 0
                ORDER BY nv.MANV
                OFFSET v_off ROWS FETCH NEXT v_ps ROWS ONLY;
        ELSE
            OPEN p_data_cur FOR SELECT NULL AS ENTITY_KEY FROM DUAL WHERE 1=0;
        END IF;
    END READ_INDEX_PAGE;

END PKG_AI_INDEX;
/

PROMPT [5/6] Cap quyen EXECUTE PKG_AI_INDEX cho AI_READONLY...
GRANT EXECUTE ON AI_OWNER.PKG_AI_INDEX TO AI_READONLY;

PROMPT [6/6] Kiem tra loi bien dich...
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS 
FROM ALL_OBJECTS 
WHERE OWNER = 'AI_OWNER' AND OBJECT_NAME IN ('TB_AI_INDEX_SOURCE', 'TB_AI_INDEX_REGISTRY', 'TB_AI_INDEX_OUTBOX', 'TB_AI_INDEX_CHECKPOINT', 'PKG_AI_INDEX')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

COMMIT;
PROMPT Hoan tat Migration V1_26__ai_rag_v2_index_sync_and_qdrant_foundation.sql.
EXIT;
