-- ====================================================================
-- HRMS Enterprise Database Migration Script
-- Version: V1_3
-- Description: Bảng Quản Lý Phiên Bản Schema (Database Versioning)
-- ====================================================================

CREATE TABLE SCHEMA_VERSION (
    INSTALLED_RANK NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    VERSION VARCHAR2(50),
    DESCRIPTION VARCHAR2(200) NOT NULL,
    TYPE VARCHAR2(20) DEFAULT 'SQL',
    SCRIPT VARCHAR2(1000) NOT NULL,
    CHECKSUM VARCHAR2(100),
    INSTALLED_BY VARCHAR2(100) DEFAULT USER,
    INSTALLED_ON TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXECUTION_TIME_MS NUMBER DEFAULT 0,
    SUCCESS NUMBER(1) DEFAULT 1,
    CONSTRAINT PK_SCHEMA_VERSION PRIMARY KEY (INSTALLED_RANK)
);

CREATE INDEX IX_SCHEMA_VERSION ON SCHEMA_VERSION (VERSION);

-- Ghi nhận lịch sử các bản migration cơ sở
INSERT INTO SCHEMA_VERSION (VERSION, DESCRIPTION, SCRIPT, SUCCESS) 
VALUES ('1.0', 'Init Core HRMS Schema', 'V1_0__init_schema.sql', 1);

INSERT INTO SCHEMA_VERSION (VERSION, DESCRIPTION, SCRIPT, SUCCESS) 
VALUES ('1.1', 'Audit Trail Triggers', 'V1_1__audit_triggers.sql', 1);

INSERT INTO SCHEMA_VERSION (VERSION, DESCRIPTION, SCRIPT, SUCCESS) 
VALUES ('1.2', 'AI Safe Whitelisted Views', 'V1_2__ai_views.sql', 1);

INSERT INTO SCHEMA_VERSION (VERSION, DESCRIPTION, SCRIPT, SUCCESS) 
VALUES ('1.3', 'Database Versioning Registry', 'V1_3__schema_versioning.sql', 1);

COMMIT;
