-- ============================================================================
-- SCRIPT: verify_as_readonly.sql
-- Kiem tra truc tiep boi user AI_READONLY
-- ============================================================================

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET DEFINE OFF;

PROMPT [AI_READONLY] Kiem tra session user...
SELECT USER AS CURRENT_ORACLE_USER FROM DUAL;

DECLARE
    v_c NUMBER;
BEGIN
    AI_OWNER.PKG_AI_READER.CLEAR_REQUEST();

    -- Kiem tra Unbound 13 Views: Tat ca phai tra ve 0
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_EMPLOYEE_LOOKUP; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_EMPLOYEE_LOOKUP'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_EMPLOYEE; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_EMPLOYEE'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_EMPLOYEE_COUNT; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_EMPLOYEE_COUNT'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_ORG_LOOKUP; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_ORG_LOOKUP'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_PERIOD; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_PERIOD'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_OVERTIME; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_OVERTIME'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_OVERTIME_SUMMARY; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_OVERTIME_SUMMARY'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_ALLOWANCE; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_ALLOWANCE'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_INSURANCE; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_INSURANCE'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_ADVANCE; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_ADVANCE'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_ATTENDANCE_SUMMARY; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_ATTENDANCE_SUMMARY'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_CONTRACT; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_CONTRACT'); END IF;
    SELECT COUNT(*) INTO v_c FROM AI_OWNER.V_AI_SALARY_CHANGE; IF v_c > 0 THEN RAISE_APPLICATION_ERROR(-20050, 'Leak: V_AI_SALARY_CHANGE'); END IF;

    DBMS_OUTPUT.PUT_LINE('[PASS] AI_READONLY: Toan bo 13 Views tra ve dung 0 dong khi chua bind ticket.');

    -- Kiem tra IS_READY() qua AI_READONLY
    IF AI_OWNER.PKG_AI_READER.IS_READY() <> 1 THEN
        RAISE_APPLICATION_ERROR(-20058, 'Loi: IS_READY qua AI_READONLY tra ve 0!');
    END IF;
    DBMS_OUTPUT.PUT_LINE('[PASS] AI_READONLY: PKG_AI_READER.IS_READY() tra ve 1.');
END;
/

PROMPT [AI_READONLY] Kiem tra tu choi truy cap bang goc HR...
DECLARE
    v_c NUMBER;
    v_caught BOOLEAN := FALSE;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM HR.TB_NHANVIEN' INTO v_c;
    EXCEPTION WHEN OTHERS THEN
        IF SQLCODE = -942 THEN v_caught := TRUE; END IF;
    END;
    IF NOT v_caught THEN RAISE_APPLICATION_ERROR(-20060, 'Loi: AI_READONLY khong bi chan khi doc HR.TB_NHANVIEN!'); END IF;
    DBMS_OUTPUT.PUT_LINE('[PASS] AI_READONLY: Khong co quyen tren bang goc HR (ORA-00942).');
END;
/

PROMPT [AI_READONLY] Kiem tra tu choi truy cap bang quan tri AI_OWNER...
DECLARE
    v_c NUMBER;
    v_caught BOOLEAN := FALSE;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM AI_OWNER.TB_AI_SECRET_VAULT' INTO v_c;
    EXCEPTION WHEN OTHERS THEN
        IF SQLCODE = -942 THEN v_caught := TRUE; END IF;
    END;
    IF NOT v_caught THEN RAISE_APPLICATION_ERROR(-20061, 'Loi: AI_READONLY khong bi chan khi doc AI_OWNER.TB_AI_SECRET_VAULT!'); END IF;
    DBMS_OUTPUT.PUT_LINE('[PASS] AI_READONLY: Khong co quyen doc khoa bi mat AI_OWNER.TB_AI_SECRET_VAULT (ORA-00942).');
END;
/

EXIT;
