//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AiEntities : DbContext
    {
        public AiEntities()
            : base("name=AiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_AI_ADVANCE> V_AI_ADVANCE { get; set; }
        public virtual DbSet<V_AI_ALLOWANCE> V_AI_ALLOWANCE { get; set; }
        public virtual DbSet<V_AI_ATTENDANCE> V_AI_ATTENDANCE { get; set; }
        public virtual DbSet<V_AI_EMPLOYEE> V_AI_EMPLOYEE { get; set; }
        public virtual DbSet<V_AI_INSURANCE> V_AI_INSURANCE { get; set; }
        public virtual DbSet<V_AI_OVERTIME> V_AI_OVERTIME { get; set; }
    }
}
