//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyEntities : DbContext
    {
        public MyEntities()
            : base("name=MyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BANGCONG> TB_BANGCONG { get; set; }
        public virtual DbSet<TB_BANGCONG_CHITIET> TB_BANGCONG_CHITIET { get; set; }
        public virtual DbSet<TB_BAOHIEM> TB_BAOHIEM { get; set; }
        public virtual DbSet<TB_BOPHAN> TB_BOPHAN { get; set; }
        public virtual DbSet<TB_CHUCVU> TB_CHUCVU { get; set; }
        public virtual DbSet<TB_CONFIG> TB_CONFIG { get; set; }
        public virtual DbSet<TB_CONGTY> TB_CONGTY { get; set; }
        public virtual DbSet<TB_DANTOC> TB_DANTOC { get; set; }
        public virtual DbSet<TB_DIEUCHUYEN_NHANVIEN> TB_DIEUCHUYEN_NHANVIEN { get; set; }
        public virtual DbSet<TB_GIOITINH> TB_GIOITINH { get; set; }
        public virtual DbSet<TB_HOPDONG> TB_HOPDONG { get; set; }
        public virtual DbSet<TB_KHENTHUONG_KYLUAT> TB_KHENTHUONG_KYLUAT { get; set; }
        public virtual DbSet<TB_KYCONG> TB_KYCONG { get; set; }
        public virtual DbSet<TB_KYCONGCHITIET> TB_KYCONGCHITIET { get; set; }
        public virtual DbSet<TB_LOAICA> TB_LOAICA { get; set; }
        public virtual DbSet<TB_LOAICONG> TB_LOAICONG { get; set; }
        public virtual DbSet<TB_NANGLUONG_NHANVIEN> TB_NANGLUONG_NHANVIEN { get; set; }
        public virtual DbSet<TB_NHANVIEN> TB_NHANVIEN { get; set; }
        public virtual DbSet<TB_NHANVIEN_PHUCAP> TB_NHANVIEN_PHUCAP { get; set; }
        public virtual DbSet<TB_NHANVIEN_THOIVIEC> TB_NHANVIEN_THOIVIEC { get; set; }
        public virtual DbSet<TB_PHONGBAN> TB_PHONGBAN { get; set; }
        public virtual DbSet<TB_PHUCAP> TB_PHUCAP { get; set; }
        public virtual DbSet<TB_QUOCTICH> TB_QUOCTICH { get; set; }
        public virtual DbSet<TB_SYS_FUNCTION> TB_SYS_FUNCTION { get; set; }
        public virtual DbSet<TB_SYS_GROUP> TB_SYS_GROUP { get; set; }
        public virtual DbSet<TB_SYS_REPORT> TB_SYS_REPORT { get; set; }
        public virtual DbSet<TB_SYS_RIGHT> TB_SYS_RIGHT { get; set; }
        public virtual DbSet<TB_SYS_RIGHT_REPORT> TB_SYS_RIGHT_REPORT { get; set; }
        public virtual DbSet<TB_SYS_USER> TB_SYS_USER { get; set; }
        public virtual DbSet<TB_TANGCA> TB_TANGCA { get; set; }
        public virtual DbSet<TB_TONGIAO> TB_TONGIAO { get; set; }
        public virtual DbSet<TB_TRINHDO> TB_TRINHDO { get; set; }
        public virtual DbSet<TB_UNGLUONG> TB_UNGLUONG { get; set; }
        public virtual DbSet<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        public virtual DbSet<TB_LANGUAGES> TB_LANGUAGES { get; set; }
        public virtual DbSet<TB_THONGBAO> TB_THONGBAO { get; set; }
        public virtual DbSet<TB_TRANSLATIONS> TB_TRANSLATIONS { get; set; }
    
        public virtual int ADD_JOB_HISTORY(Nullable<decimal> p_EMP_ID, Nullable<System.DateTime> p_START_DATE, Nullable<System.DateTime> p_END_DATE, string p_JOB_ID, Nullable<decimal> p_DEPARTMENT_ID)
        {
            var p_EMP_IDParameter = p_EMP_ID.HasValue ?
                new ObjectParameter("P_EMP_ID", p_EMP_ID) :
                new ObjectParameter("P_EMP_ID", typeof(decimal));
    
            var p_START_DATEParameter = p_START_DATE.HasValue ?
                new ObjectParameter("P_START_DATE", p_START_DATE) :
                new ObjectParameter("P_START_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_JOB_IDParameter = p_JOB_ID != null ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(string));
    
            var p_DEPARTMENT_IDParameter = p_DEPARTMENT_ID.HasValue ?
                new ObjectParameter("P_DEPARTMENT_ID", p_DEPARTMENT_ID) :
                new ObjectParameter("P_DEPARTMENT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_JOB_HISTORY", p_EMP_IDParameter, p_START_DATEParameter, p_END_DATEParameter, p_JOB_IDParameter, p_DEPARTMENT_IDParameter);
        }
    
        public virtual int SECURE_DML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SECURE_DML");
        }
    }
}
