//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGLUONG
    {
        public decimal IDBL { get; set; }
        public decimal MANV { get; set; }
        public decimal MAKYCONG { get; set; }
        public byte THANG { get; set; }
        public short NAM { get; set; }
        public Nullable<decimal> CONG_CHUAN { get; set; }
        public Nullable<decimal> CONG_THUCTE { get; set; }
        public Nullable<decimal> CONG_LAMDEM { get; set; }
        public Nullable<decimal> DAILY_RATE { get; set; }
        public Nullable<decimal> DAILY_ALLOWANCE { get; set; }
        public Nullable<decimal> LUONG_CONG_THUCTE { get; set; }
        public Nullable<decimal> PHUCAP_CONG_THUCTE { get; set; }
        public Nullable<decimal> TIEN_TANGCA { get; set; }
        public Nullable<decimal> TIEN_CHUYENCAN { get; set; }
        public Nullable<decimal> TIEN_AN_CA { get; set; }
        public Nullable<decimal> KHOAN_CONG_KHAC { get; set; }
        public Nullable<decimal> TIEN_BHXH_TRICH { get; set; }
        public Nullable<decimal> TIEN_TAMUNG { get; set; }
        public Nullable<decimal> KHOAN_TRU_KHAC { get; set; }
        public Nullable<decimal> THUC_LINH { get; set; }
    
        public virtual TB_KYCONG TB_KYCONG { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
