//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONGTY
    {
        public decimal IDCTY { get; set; }
        public string TENCTY { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
    }
}
