//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HOPDONG
    {
        public decimal SOHD { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<System.DateTime> NGAYKY { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<decimal> LANKY { get; set; }
        public string THOIHAN { get; set; }
        public Nullable<decimal> HESOLUONG { get; set; }
        public Nullable<decimal> MANV { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
