//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN_PHUCAP
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MANV { get; set; }
        public Nullable<decimal> IDPC { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
    
        public virtual TB_PHUCAP TB_PHUCAP { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
