//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_NHANVIEN()
        {
            this.TB_BAOHIEM = new HashSet<TB_BAOHIEM>();
            this.TB_DIEUCHUYEN_NHANVIEN = new HashSet<TB_DIEUCHUYEN_NHANVIEN>();
            this.TB_HOPDONG = new HashSet<TB_HOPDONG>();
            this.TB_KHENTHUONG_KYLUAT = new HashSet<TB_KHENTHUONG_KYLUAT>();
            this.TB_NHANVIEN_PHUCAP = new HashSet<TB_NHANVIEN_PHUCAP>();
            this.TB_NHANVIEN_THOIVIEC = new HashSet<TB_NHANVIEN_THOIVIEC>();
            this.TB_TANGCA = new HashSet<TB_TANGCA>();
            this.TB_UNGLUONG = new HashSet<TB_UNGLUONG>();
        }
    
        public decimal MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<decimal> IDGT { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<decimal> IDPB { get; set; }
        public Nullable<decimal> IDBP { get; set; }
        public Nullable<decimal> IDCV { get; set; }
        public Nullable<decimal> IDTD { get; set; }
        public Nullable<decimal> IDDT { get; set; }
        public Nullable<decimal> IDTG { get; set; }
        public Nullable<decimal> IDCTY { get; set; }
        public Nullable<decimal> IDQT { get; set; }
        public Nullable<decimal> DATHOIVIEC { get; set; }
    
        public virtual TB_BANGCONG TB_BANGCONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BAOHIEM> TB_BAOHIEM { get; set; }
        public virtual TB_BOPHAN TB_BOPHAN { get; set; }
        public virtual TB_CHUCVU TB_CHUCVU { get; set; }
        public virtual TB_CONGTY TB_CONGTY { get; set; }
        public virtual TB_DANTOC TB_DANTOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DIEUCHUYEN_NHANVIEN> TB_DIEUCHUYEN_NHANVIEN { get; set; }
        public virtual TB_GIOITINH TB_GIOITINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_HOPDONG> TB_HOPDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_KHENTHUONG_KYLUAT> TB_KHENTHUONG_KYLUAT { get; set; }
        public virtual TB_PHONGBAN TB_PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANVIEN_PHUCAP> TB_NHANVIEN_PHUCAP { get; set; }
        public virtual TB_QUOCTICH TB_QUOCTICH { get; set; }
        public virtual TB_TRINHDO TB_TRINHDO { get; set; }
        public virtual TB_TONGIAO TB_TONGIAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANVIEN_THOIVIEC> TB_NHANVIEN_THOIVIEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TANGCA> TB_TANGCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_UNGLUONG> TB_UNGLUONG { get; set; }
    }
}
