//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_LOGIN_HISTORY
    {
        public decimal ID_LOGIN { get; set; }
        public Nullable<decimal> ID_USER { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public string IP_ADDRESS { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string TEN_MAY_TINH { get; set; }
        public string TRANGTHAI { get; set; }
    }
}
