//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_RIGHT
    {
        public string FUNCTION_CODE { get; set; }
        public decimal IDUSER { get; set; }
        public Nullable<decimal> USER_RIGHT { get; set; }
    }
}
