//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_LOG
    {
        public decimal ID_LOG { get; set; }
        public Nullable<decimal> MANV_THUCHIEN { get; set; }
        public string TEN_THUCHIEN { get; set; }
        public string HANHDONG { get; set; }
        public string TEN_BANG { get; set; }
        public string ID_BAN_GHI { get; set; }
        public string DU_LIEU_CU { get; set; }
        public string DU_LIEU_MOI { get; set; }
        public string IP_ADDRESS { get; set; }
        public string MAC_ADDRESS { get; set; }
        public string TEN_MAY_TINH { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
    }
}
