//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_USER
    {
        public decimal IDUSER { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FULLNAME { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public Nullable<System.DateTime> LAST_PWD_CHANGED { get; set; }
        public Nullable<decimal> DISABLED { get; set; }
        public Nullable<decimal> ISGROUP { get; set; }
    }
}
