//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_FUNCTION
    {
        public string FUNCTION_CODE { get; set; }
        public decimal SORT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ISGROUP { get; set; }
        public string PARENT { get; set; }
        public Nullable<decimal> MENU { get; set; }
        public string TIPS { get; set; }
    }
}
