//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TANGCA
    {
        public decimal IDTCA { get; set; }
        public Nullable<decimal> NAM { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<decimal> NGAY { get; set; }
        public Nullable<decimal> SOGIO { get; set; }
        public Nullable<decimal> MANV { get; set; }
        public Nullable<decimal> IDLOAICA { get; set; }
    
        public virtual TB_LOAICA TB_LOAICA { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
