//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AI_UNGLUONG
    {
        public decimal IDUL { get; set; }
        public Nullable<decimal> NAM { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<decimal> NGAY { get; set; }
        public Nullable<decimal> SOTIENUNG { get; set; }
        public Nullable<decimal> MANV { get; set; }
    }
}
