//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyEntities : DbContext
    {
        public static string GlobalConnectionString { get; set; } = "name=MyEntities";
    
        public MyEntities()
            : base(GlobalConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BANGCONG> TB_BANGCONG { get; set; }
        public virtual DbSet<TB_BANGCONG_CHITIET> TB_BANGCONG_CHITIET { get; set; }
        public virtual DbSet<TB_BAOHIEM> TB_BAOHIEM { get; set; }
        public virtual DbSet<TB_BOPHAN> TB_BOPHAN { get; set; }
        public virtual DbSet<TB_CHUCVU> TB_CHUCVU { get; set; }
        public virtual DbSet<TB_CONFIG> TB_CONFIG { get; set; }
        public virtual DbSet<TB_CONGTY> TB_CONGTY { get; set; }
        public virtual DbSet<TB_DANTOC> TB_DANTOC { get; set; }
        public virtual DbSet<TB_DIEUCHUYEN_NHANVIEN> TB_DIEUCHUYEN_NHANVIEN { get; set; }
        public virtual DbSet<TB_GIOITINH> TB_GIOITINH { get; set; }
        public virtual DbSet<TB_HOPDONG> TB_HOPDONG { get; set; }
        public virtual DbSet<TB_KHENTHUONG_KYLUAT> TB_KHENTHUONG_KYLUAT { get; set; }
        public virtual DbSet<TB_KYCONG> TB_KYCONG { get; set; }
        public virtual DbSet<TB_KYCONGCHITIET> TB_KYCONGCHITIET { get; set; }
        public virtual DbSet<TB_LOAICA> TB_LOAICA { get; set; }
        public virtual DbSet<TB_LOAICONG> TB_LOAICONG { get; set; }
        public virtual DbSet<TB_NANGLUONG_NHANVIEN> TB_NANGLUONG_NHANVIEN { get; set; }
        public virtual DbSet<TB_NHANVIEN> TB_NHANVIEN { get; set; }
        public virtual DbSet<TB_NHANVIEN_PHUCAP> TB_NHANVIEN_PHUCAP { get; set; }
        public virtual DbSet<TB_NHANVIEN_THOIVIEC> TB_NHANVIEN_THOIVIEC { get; set; }
        public virtual DbSet<TB_PHONGBAN> TB_PHONGBAN { get; set; }
        public virtual DbSet<TB_PHUCAP> TB_PHUCAP { get; set; }
        public virtual DbSet<TB_QUOCTICH> TB_QUOCTICH { get; set; }
        public virtual DbSet<TB_SYS_FUNCTION> TB_SYS_FUNCTION { get; set; }
        public virtual DbSet<TB_SYS_GROUP> TB_SYS_GROUP { get; set; }
        public virtual DbSet<TB_SYS_REPORT> TB_SYS_REPORT { get; set; }
        public virtual DbSet<TB_SYS_RIGHT> TB_SYS_RIGHT { get; set; }
        public virtual DbSet<TB_SYS_RIGHT_REPORT> TB_SYS_RIGHT_REPORT { get; set; }
        public virtual DbSet<TB_SYS_USER> TB_SYS_USER { get; set; }
        public virtual DbSet<TB_TANGCA> TB_TANGCA { get; set; }
        public virtual DbSet<TB_TONGIAO> TB_TONGIAO { get; set; }
        public virtual DbSet<TB_TRINHDO> TB_TRINHDO { get; set; }
        public virtual DbSet<TB_UNGLUONG> TB_UNGLUONG { get; set; }
        public virtual DbSet<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        public virtual DbSet<TB_LANGUAGES> TB_LANGUAGES { get; set; }
        public virtual DbSet<TB_THONGBAO> TB_THONGBAO { get; set; }
        public virtual DbSet<TB_TRANSLATIONS> TB_TRANSLATIONS { get; set; }
        public virtual DbSet<TB_SYS_LOG> TB_SYS_LOG { get; set; }
        public virtual DbSet<TB_SYS_LOGIN_HISTORY> TB_SYS_LOGIN_HISTORY { get; set; }
        public virtual DbSet<TB_LOAIHOPDONG> TB_LOAIHOPDONG { get; set; }
        public virtual DbSet<TB_NGAYLE> TB_NGAYLE { get; set; }
        public virtual DbSet<SCHEMA_VERSION> SCHEMA_VERSION { get; set; }
        public virtual DbSet<TB_AUTH_AUDIT> TB_AUTH_AUDIT { get; set; }
        public virtual DbSet<TB_AUTH_LOGIN_ATTEMPT> TB_AUTH_LOGIN_ATTEMPT { get; set; }
        public virtual DbSet<TB_AUTH_POLICY> TB_AUTH_POLICY { get; set; }
        public virtual DbSet<TB_AUTH_SESSION> TB_AUTH_SESSION { get; set; }
        public virtual DbSet<TB_BANGLUONG_BAOHIEM> TB_BANGLUONG_BAOHIEM { get; set; }
        public virtual DbSet<TB_BANGLUONG_CONG_DOAN> TB_BANGLUONG_CONG_DOAN { get; set; }
        public virtual DbSet<TB_BANGLUONG_CT> TB_BANGLUONG_CT { get; set; }
        public virtual DbSet<TB_BANGLUONG_CT_SOURCE> TB_BANGLUONG_CT_SOURCE { get; set; }
        public virtual DbSet<TB_BANGLUONG_OT_COMPLIANCE> TB_BANGLUONG_OT_COMPLIANCE { get; set; }
        public virtual DbSet<TB_BANGLUONG_THUE_CT> TB_BANGLUONG_THUE_CT { get; set; }
        public virtual DbSet<TB_CA_KHUNGGIO> TB_CA_KHUNGGIO { get; set; }
        public virtual DbSet<TB_CA_PHIENBAN> TB_CA_PHIENBAN { get; set; }
        public virtual DbSet<TB_CHAMCONG_BATTHUONG> TB_CHAMCONG_BATTHUONG { get; set; }
        public virtual DbSet<TB_CHAMCONG_BT_LICHSU> TB_CHAMCONG_BT_LICHSU { get; set; }
        public virtual DbSet<TB_CHAMCONG_KQ_NGAY> TB_CHAMCONG_KQ_NGAY { get; set; }
        public virtual DbSet<TB_CHAMCONG_LANTINH> TB_CHAMCONG_LANTINH { get; set; }
        public virtual DbSet<TB_CHINH_SACH_BHXH> TB_CHINH_SACH_BHXH { get; set; }
        public virtual DbSet<TB_CHINH_SACH_BHXH_VUNG> TB_CHINH_SACH_BHXH_VUNG { get; set; }
        public virtual DbSet<TB_CHINH_SACH_CONG_DOAN> TB_CHINH_SACH_CONG_DOAN { get; set; }
        public virtual DbSet<TB_CHINH_SACH_LUONG> TB_CHINH_SACH_LUONG { get; set; }
        public virtual DbSet<TB_CONG_PD_NGUON> TB_CONG_PD_NGUON { get; set; }
        public virtual DbSet<TB_CONG_PHANDOAN> TB_CONG_PHANDOAN { get; set; }
        public virtual DbSet<TB_HESO_TANGCA> TB_HESO_TANGCA { get; set; }
        public virtual DbSet<TB_LICH_LAMVIEC> TB_LICH_LAMVIEC { get; set; }
        public virtual DbSet<TB_NGUOI_PHU_THUOC> TB_NGUOI_PHU_THUOC { get; set; }
        public virtual DbSet<TB_NHANVIEN_BAOHIEM_THAM_GIA> TB_NHANVIEN_BAOHIEM_THAM_GIA { get; set; }
        public virtual DbSet<TB_NHANVIEN_CONG_DOAN_THAM_GIA> TB_NHANVIEN_CONG_DOAN_THAM_GIA { get; set; }
        public virtual DbSet<TB_NHANVIEN_THUE> TB_NHANVIEN_THUE { get; set; }
        public virtual DbSet<TB_PAYROLL_CALCULATION_RUN> TB_PAYROLL_CALCULATION_RUN { get; set; }
        public virtual DbSet<TB_QUYDINH_CHAMCONG> TB_QUYDINH_CHAMCONG { get; set; }
        public virtual DbSet<TB_QUYET_TOAN_THUE_NAM> TB_QUYET_TOAN_THUE_NAM { get; set; }
        public virtual DbSet<TB_QUYET_TOAN_THUE_NAM_CT> TB_QUYET_TOAN_THUE_NAM_CT { get; set; }
        public virtual DbSet<TB_THUE_TNCN_BAC> TB_THUE_TNCN_BAC { get; set; }
        public virtual DbSet<TB_THUE_TNCN_CHINH_SACH> TB_THUE_TNCN_CHINH_SACH { get; set; }
        public virtual DbSet<TB_USER_EMPLOYEE_MAPPING> TB_USER_EMPLOYEE_MAPPING { get; set; }
        public virtual DbSet<TB_YEUCAU_DIEUCHINHCONG> TB_YEUCAU_DIEUCHINHCONG { get; set; }
        public virtual DbSet<TB_YEUCAU_NGHIPHEP> TB_YEUCAU_NGHIPHEP { get; set; }
        public virtual DbSet<TB_YEUCAU_TANGCA> TB_YEUCAU_TANGCA { get; set; }
        public virtual DbSet<TB_SYS_RIGHT_BACKUP> TB_SYS_RIGHT_BACKUP { get; set; }
    
        public virtual int ADD_JOB_HISTORY(Nullable<decimal> p_EMP_ID, Nullable<System.DateTime> p_START_DATE, Nullable<System.DateTime> p_END_DATE, string p_JOB_ID, Nullable<decimal> p_DEPARTMENT_ID)
        {
            var p_EMP_IDParameter = p_EMP_ID.HasValue ?
                new ObjectParameter("P_EMP_ID", p_EMP_ID) :
                new ObjectParameter("P_EMP_ID", typeof(decimal));
    
            var p_START_DATEParameter = p_START_DATE.HasValue ?
                new ObjectParameter("P_START_DATE", p_START_DATE) :
                new ObjectParameter("P_START_DATE", typeof(System.DateTime));
    
            var p_END_DATEParameter = p_END_DATE.HasValue ?
                new ObjectParameter("P_END_DATE", p_END_DATE) :
                new ObjectParameter("P_END_DATE", typeof(System.DateTime));
    
            var p_JOB_IDParameter = p_JOB_ID != null ?
                new ObjectParameter("P_JOB_ID", p_JOB_ID) :
                new ObjectParameter("P_JOB_ID", typeof(string));
    
            var p_DEPARTMENT_IDParameter = p_DEPARTMENT_ID.HasValue ?
                new ObjectParameter("P_DEPARTMENT_ID", p_DEPARTMENT_ID) :
                new ObjectParameter("P_DEPARTMENT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_JOB_HISTORY", p_EMP_IDParameter, p_START_DATEParameter, p_END_DATEParameter, p_JOB_IDParameter, p_DEPARTMENT_IDParameter);
        }
    
        public virtual int SECURE_DML()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SECURE_DML");
        }
    }
}
