//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEMA_VERSION
    {
        public decimal INSTALLED_RANK { get; set; }
        public string VERSION { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE { get; set; }
        public string SCRIPT { get; set; }
        public string CHECKSUM { get; set; }
        public string INSTALLED_BY { get; set; }
        public Nullable<System.DateTime> INSTALLED_ON { get; set; }
        public Nullable<decimal> EXECUTION_TIME_MS { get; set; }
        public Nullable<bool> SUCCESS { get; set; }
    }
}
