//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUTH_AUDIT
    {
        public decimal AUDIT_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<decimal> ACTOR_USER_ID { get; set; }
        public string SESSION_ID { get; set; }
        public string EVENT_TYPE { get; set; }
        public string RESULT { get; set; }
        public string REASON { get; set; }
        public string CLIENT_TYPE { get; set; }
        public string DEVICE_ID_HASH { get; set; }
        public string IP_ADDRESS { get; set; }
        public string USER_AGENT { get; set; }
        public System.DateTime OCCURRED_AT { get; set; }
        public string CORRELATION_ID { get; set; }
        public string METADATA_JSON { get; set; }
    }
}
