//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUTH_SESSION
    {
        public string SESSION_ID { get; set; }
        public decimal USER_ID { get; set; }
        public string JTI { get; set; }
        public string CLIENT_TYPE { get; set; }
        public string PLATFORM { get; set; }
        public string DEVICE_ID_HASH { get; set; }
        public string DEVICE_NAME { get; set; }
        public string IP_ADDRESS { get; set; }
        public string USER_AGENT { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public System.DateTime LAST_USED_AT { get; set; }
        public System.DateTime EXPIRES_AT { get; set; }
        public Nullable<System.DateTime> REVOKED_AT { get; set; }
        public string REVOKE_REASON { get; set; }
    
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
