//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AUTH_POLICY
    {
        public decimal POLICY_ID { get; set; }
        public string SCOPE_TYPE { get; set; }
        public string SCOPE_ID { get; set; }
        public byte MAX_ACTIVE_SESSIONS { get; set; }
        public string SESSION_LIMIT_STRATEGY { get; set; }
        public int ACCESS_TOKEN_MINUTES { get; set; }
        public int IDLE_TIMEOUT_MINUTES { get; set; }
        public int ABSOLUTE_TIMEOUT_MINUTES { get; set; }
        public byte MAX_FAILED_LOGIN_ATTEMPTS { get; set; }
        public short FAILED_ATTEMPT_WINDOW_MINUTES { get; set; }
        public short LOCKOUT_DURATION_MINUTES { get; set; }
        public bool ENABLED { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public System.DateTime UPDATED_AT { get; set; }
    }
}
