//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGCONG_CHITIET
    {
        public decimal IDBANGCONGCT { get; set; }
        public Nullable<decimal> MAKYCONG { get; set; }
        public Nullable<decimal> IDCTY { get; set; }
        public Nullable<decimal> MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string THU { get; set; }
        public string GIOVAO { get; set; }
        public string GIORA { get; set; }
        public Nullable<decimal> NGAYPHEP { get; set; }
        public Nullable<decimal> CONGNGAYLE { get; set; }
        public Nullable<decimal> CONGCHUNHAT { get; set; }
        public string KYHIEU { get; set; }
        public string GHICHU { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<decimal> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public Nullable<decimal> NGAYCONG { get; set; }
        public string TRANGTHAI_CONG { get; set; }
        public Nullable<bool> DU_DIEUKIEN_CHOT { get; set; }
        public Nullable<long> LANTINH_ID_HIENHANH { get; set; }
        public Nullable<long> GIAY_THUC_TE { get; set; }
        public Nullable<long> GIAY_HUONG_CONG_THUONG { get; set; }
        public Nullable<long> GIAY_OT_XAC_NHAN { get; set; }
        public Nullable<long> GIAY_DEM_TRONG_GIO_THUONG { get; set; }
        public Nullable<long> GIAY_DEM_OT { get; set; }
        public Nullable<long> GIAY_DI_MUON_THUC_TE { get; set; }
        public Nullable<long> GIAY_VE_SOM_THUC_TE { get; set; }
        public Nullable<long> GIAY_DI_MUON_VIPHAM { get; set; }
        public Nullable<long> GIAY_VE_SOM_VIPHAM { get; set; }
    }
}
