//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGLUONG_OT_COMPLIANCE
    {
        public decimal ID { get; set; }
        public decimal IDBL { get; set; }
        public decimal MANV { get; set; }
        public decimal MAKYCONG { get; set; }
        public decimal MONTHLY_STANDARD_LIMIT { get; set; }
        public decimal ANNUAL_STANDARD_LIMIT { get; set; }
        public decimal ANNUAL_EXTENDED_LIMIT { get; set; }
        public decimal ACTUAL_HOURS_MONTH { get; set; }
        public decimal ACTUAL_HOURS_YTD { get; set; }
        public decimal LEGAL_HOURS_MONTH { get; set; }
        public decimal EXCESS_HOURS_MONTH { get; set; }
        public Nullable<bool> EXTENDED_ELIGIBLE { get; set; }
        public Nullable<bool> EMPLOYEE_CONSENT { get; set; }
        public Nullable<bool> NOTIFICATION_FILED { get; set; }
        public string COMPLIANCE_STATUS { get; set; }
        public Nullable<decimal> TOTAL_OT_PAYMENT { get; set; }
        public Nullable<decimal> LEGAL_ALLOWED_PAYMENT { get; set; }
        public Nullable<decimal> EXEMPT_OT_PAYMENT { get; set; }
        public Nullable<decimal> TAXABLE_EXCESS_PAYMENT { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    }
}
