//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGLUONG_CT_SOURCE
    {
        public decimal ID { get; set; }
        public decimal IDBLCT { get; set; }
        public decimal MANV { get; set; }
        public string SOURCE_TYPE { get; set; }
        public Nullable<decimal> SOURCE_BCCT_ID { get; set; }
        public Nullable<decimal> SOURCE_TC_ID { get; set; }
        public Nullable<decimal> SOURCE_NVPC_ID { get; set; }
        public string SOURCE_KTKL_SOQD { get; set; }
        public Nullable<decimal> SOURCE_UL_ID { get; set; }
        public decimal WEIGHT_QUANTITY { get; set; }
        public decimal AMOUNT_CONTRIBUTED { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_NHANVIEN_PHUCAP TB_NHANVIEN_PHUCAP { get; set; }
    }
}
