//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGLUONG_CONG_DOAN
    {
        public decimal ID { get; set; }
        public decimal IDBL { get; set; }
        public decimal MANV { get; set; }
        public decimal MAKYCONG { get; set; }
        public decimal POLICY_CD_ID { get; set; }
        public decimal PROFILE_CD_ID { get; set; }
        public bool LA_DOAN_VIEN { get; set; }
        public decimal LUONG_CAN_CU_DONG { get; set; }
        public decimal TY_LE_DOAN_PHI_NLD { get; set; }
        public decimal MUC_TRAN_DOAN_PHI { get; set; }
        public decimal TIEN_DOAN_PHI_NLD { get; set; }
        public decimal TY_LE_KPCD_NSDLD { get; set; }
        public decimal TIEN_KPCD_NSDLD { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_CHINH_SACH_CONG_DOAN TB_CHINH_SACH_CONG_DOAN { get; set; }
    }
}
