//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGCONG
    {
        public decimal MABC { get; set; }
        public Nullable<decimal> NAM { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<decimal> NGAY { get; set; }
        public Nullable<decimal> GIOVAO { get; set; }
        public Nullable<decimal> PHUTVAO { get; set; }
        public Nullable<decimal> GIORA { get; set; }
        public Nullable<decimal> PHUTRA { get; set; }
        public Nullable<decimal> MANV { get; set; }
        public Nullable<decimal> IDLOAICONG { get; set; }
        public Nullable<System.DateTime> THOIDIEM_VAO { get; set; }
        public Nullable<System.DateTime> THOIDIEM_RA { get; set; }
        public string NGUON_CHAM { get; set; }
        public string MA_SU_KIEN_NGUON { get; set; }
        public string MA_THIET_BI { get; set; }
        public Nullable<System.DateTime> TIEPNHAN_LUC { get; set; }
        public Nullable<long> NGUON_REV { get; set; }
    
        public virtual TB_LOAICONG TB_LOAICONG { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
