//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGLUONG_CT
    {
        public decimal IDBLCT { get; set; }
        public decimal IDBL { get; set; }
        public decimal MANV { get; set; }
        public decimal MAKYCONG { get; set; }
        public string NHOM_KHOAN_MUC { get; set; }
        public string MA_KHOAN_MUC { get; set; }
        public string TEN_KHOAN_MUC { get; set; }
        public decimal SO_LUONG { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal HE_SO { get; set; }
        public decimal THANH_TIEN { get; set; }
        public bool TINH_VAO_DONG_BHXH { get; set; }
        public bool TINH_THUE_TNCN { get; set; }
        public Nullable<decimal> SO_TIEN_MIEN_THUE { get; set; }
        public Nullable<decimal> SO_TIEN_CHIU_THUE { get; set; }
        public string CONG_THUC_DIEN_GIAI { get; set; }
        public bool IS_LEGACY { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    }
}
