//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BANGLUONG_BAOHIEM
    {
        public decimal ID { get; set; }
        public decimal IDBL { get; set; }
        public decimal MANV { get; set; }
        public decimal MAKYCONG { get; set; }
        public decimal POLICY_BHXH_ID { get; set; }
        public decimal PROFILE_BH_ID { get; set; }
        public decimal MUC_THAM_CHIEU { get; set; }
        public short VUNG_LUONG { get; set; }
        public decimal LUONG_TOI_THIEU_VUNG { get; set; }
        public decimal LUONG_DONG_BHXH_GOC { get; set; }
        public decimal LUONG_DONG_BHXH_AP_DUNG { get; set; }
        public decimal LUONG_DONG_BHTN_AP_DUNG { get; set; }
        public decimal TY_LE_BHXH_NLD { get; set; }
        public decimal TIEN_BHXH_NLD { get; set; }
        public decimal TY_LE_BHYT_NLD { get; set; }
        public decimal TIEN_BHYT_NLD { get; set; }
        public decimal TY_LE_BHTN_NLD { get; set; }
        public decimal TIEN_BHTN_NLD { get; set; }
        public decimal TONG_BH_NLD { get; set; }
        public decimal TY_LE_BHXH_NSDLD { get; set; }
        public decimal TIEN_BHXH_NSDLD { get; set; }
        public decimal TY_LE_BHYT_NSDLD { get; set; }
        public decimal TIEN_BHYT_NSDLD { get; set; }
        public decimal TY_LE_BHTN_NSDLD { get; set; }
        public decimal TIEN_BHTN_NSDLD { get; set; }
        public decimal TY_LE_TNLD_BNN_NSDLD { get; set; }
        public decimal TIEN_TNLD_BNN_NSDLD { get; set; }
        public decimal TONG_BH_NSDLD { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_CHINH_SACH_BHXH TB_CHINH_SACH_BHXH { get; set; }
    }
}
