//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONGTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CONGTY()
        {
            this.TB_NHANVIEN = new HashSet<TB_NHANVIEN>();
        }
    
        public decimal IDCTY { get; set; }
        public string TENCTY { get; set; }
        public string DIENTHOAICTY { get; set; }
        public string EMAILCTY { get; set; }
        public string DIACHICTY { get; set; }
        public string MASOTHUECTY { get; set; }
        public string DAIDIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_NHANVIEN> TB_NHANVIEN { get; set; }
    }
}
