//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHAMCONG_KQ_NGAY
    {
        public long IDLANTINH { get; set; }
        public decimal IDBANGCONGCT { get; set; }
        public decimal MANV { get; set; }
        public decimal MAKYCONG { get; set; }
        public System.DateTime NGAY { get; set; }
        public string INPUT_HASH { get; set; }
        public string INPUT_SNAPSHOT { get; set; }
        public string TRANG_THAI { get; set; }
        public bool DU_DIEUKIEN_CHOT { get; set; }
        public long GIAY_THUC_TE { get; set; }
        public long GIAY_HUONG_CONG_THUONG { get; set; }
        public long GIAY_OT_XAC_NHAN { get; set; }
        public long GIAY_DEM_TRONG_GIO_THUONG { get; set; }
        public long GIAY_DEM_OT { get; set; }
        public long GIAY_DI_MUON_THUC_TE { get; set; }
        public long GIAY_VE_SOM_THUC_TE { get; set; }
        public long GIAY_DI_MUON_VIPHAM { get; set; }
        public long GIAY_VE_SOM_VIPHAM { get; set; }
        public decimal CONG_THUONG_QUYDOI { get; set; }
        public System.DateTime TAO_LUC { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
