//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHINH_SACH_LUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CHINH_SACH_LUONG()
        {
            this.TB_BANGLUONG = new HashSet<TB_BANGLUONG>();
        }
    
        public decimal ID { get; set; }
        public string MA_CHINH_SACH { get; set; }
        public string TEN_CHINH_SACH { get; set; }
        public System.DateTime NGAY_HIEU_LUC { get; set; }
        public Nullable<System.DateTime> NGAY_HET_HIEU_LUC { get; set; }
        public decimal SO_CONG_CHUAN_THANG { get; set; }
        public decimal SO_GIO_CHUAN_NGAY { get; set; }
        public decimal HE_SO_LAM_DEM { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG> TB_BANGLUONG { get; set; }
    }
}
