//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHAMCONG_BT_LICHSU
    {
        public long ID { get; set; }
        public long IDBATTHUONG { get; set; }
        public int THUTU { get; set; }
        public string TU_TRANGTHAI { get; set; }
        public string DEN_TRANGTHAI { get; set; }
        public string INPUT_HASH_DUYET { get; set; }
        public string QUYETDINH_SNAPSHOT { get; set; }
        public string LY_DO { get; set; }
        public decimal NGUOI_XULY { get; set; }
        public System.DateTime XULY_LUC { get; set; }
    
        public virtual TB_CHAMCONG_BATTHUONG TB_CHAMCONG_BATTHUONG { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
