//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHAMCONG_BATTHUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CHAMCONG_BATTHUONG()
        {
            this.TB_CHAMCONG_BT_LICHSU = new HashSet<TB_CHAMCONG_BT_LICHSU>();
        }
    
        public long IDBATTHUONG { get; set; }
        public string MA_SU_VIEC_HASH { get; set; }
        public long IDLANTINH_PHATHIEN { get; set; }
        public decimal IDBANGCONGCT { get; set; }
        public decimal MANV { get; set; }
        public Nullable<long> IDLICH { get; set; }
        public System.DateTime NGAY { get; set; }
        public string MA_LOI { get; set; }
        public Nullable<System.DateTime> BATDAU_LUC { get; set; }
        public Nullable<System.DateTime> KETTHUC_LUC { get; set; }
        public string MUC_DO { get; set; }
        public bool CHAN_CHOT { get; set; }
        public string INPUT_HASH { get; set; }
        public string INPUT_SNAPSHOT { get; set; }
        public string TRANG_THAI { get; set; }
        public Nullable<decimal> IDYEUCAU_NGHIPHEP { get; set; }
        public Nullable<decimal> IDYEUCAU_TANGCA { get; set; }
        public Nullable<decimal> IDYEUCAU_DIEUCHINH { get; set; }
        public Nullable<long> THAY_THE_SU_VIEC_ID { get; set; }
        public string MO_TA { get; set; }
        public System.DateTime TAO_LUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CHAMCONG_BT_LICHSU> TB_CHAMCONG_BT_LICHSU { get; set; }
    }
}
