//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONG_PHANDOAN
    {
        public long IDPHANDOAN { get; set; }
        public long IDLANTINH { get; set; }
        public decimal IDBANGCONGCT { get; set; }
        public decimal MANV { get; set; }
        public Nullable<long> IDLICH { get; set; }
        public long IDQUYDINH { get; set; }
        public System.DateTime BATDAU_LUC { get; set; }
        public System.DateTime KETTHUC_LUC { get; set; }
        public long THOILUONG_GIAY { get; set; }
        public string LOAI_THOIGIAN { get; set; }
        public string LOAI_NGAY { get; set; }
        public bool LA_BAN_DEM { get; set; }
        public bool CO_OT_BAN_NGAY_TRUOC { get; set; }
        public string TRANGTHAI_XACNHAN { get; set; }
        public long GIAY_THUC_TE { get; set; }
        public long GIAY_HUONG_CONG_THUONG { get; set; }
        public long GIAY_OT_XAC_NHAN { get; set; }
        public long GIAY_DEM_TRONG_GIO_THUONG { get; set; }
        public long GIAY_DEM_OT { get; set; }
        public long GIAY_DI_MUON_THUC_TE { get; set; }
        public long GIAY_VE_SOM_THUC_TE { get; set; }
        public long GIAY_DI_MUON_VIPHAM { get; set; }
        public long GIAY_VE_SOM_VIPHAM { get; set; }
        public Nullable<decimal> IDYEUCAU_TANGCA { get; set; }
        public Nullable<decimal> IDYEUCAU_NGHIPHEP { get; set; }
        public Nullable<decimal> IDYEUCAU_DIEUCHINH { get; set; }
    
        public virtual TB_QUYDINH_CHAMCONG TB_QUYDINH_CHAMCONG { get; set; }
    }
}
