//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONG_PD_NGUON
    {
        public long ID { get; set; }
        public long IDPHANDOAN { get; set; }
        public decimal MANV { get; set; }
        public decimal MABC { get; set; }
        public string SOURCE_HASH { get; set; }
        public string SOURCE_SNAPSHOT { get; set; }
    }
}
