//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHINH_SACH_BHXH_VUNG
    {
        public decimal ID { get; set; }
        public decimal POLICY_BHXH_ID { get; set; }
        public short VUNG_LUONG { get; set; }
        public decimal LUONG_TOI_THIEU_THANG { get; set; }
        public decimal LUONG_TOI_THIEU_GIO { get; set; }
        public decimal HE_SO_SAN_DOANH_NGHIEP { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_CHINH_SACH_BHXH TB_CHINH_SACH_BHXH { get; set; }
    }
}
