//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHAMCONG_LANTINH
    {
        public long IDLANTINH { get; set; }
        public string MA_YEU_CAU { get; set; }
        public string REQUEST_HASH { get; set; }
        public decimal MAKYCONG { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public long INPUT_REV { get; set; }
        public long EXPECTED_PUBLISH_REV { get; set; }
        public string INPUT_DATA_HASH { get; set; }
        public string PHIENBAN_ENGINE { get; set; }
        public string MUI_GIO { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime BATDAU_TINH { get; set; }
        public Nullable<System.DateTime> KETTHUC_TINH { get; set; }
        public Nullable<System.DateTime> CONGBO_LUC { get; set; }
        public decimal NGUOI_THUC_HIEN { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual TB_KYCONG TB_KYCONG { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
