//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHINH_SACH_BHXH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CHINH_SACH_BHXH()
        {
            this.TB_BANGLUONG = new HashSet<TB_BANGLUONG>();
            this.TB_BANGLUONG_BAOHIEM = new HashSet<TB_BANGLUONG_BAOHIEM>();
            this.TB_CHINH_SACH_BHXH_VUNG = new HashSet<TB_CHINH_SACH_BHXH_VUNG>();
        }
    
        public decimal ID { get; set; }
        public string MA_CHINH_SACH { get; set; }
        public string TEN_CHINH_SACH { get; set; }
        public System.DateTime NGAY_HIEU_LUC { get; set; }
        public Nullable<System.DateTime> NGAY_HET_HIEU_LUC { get; set; }
        public decimal MUC_THAM_CHIEU { get; set; }
        public decimal TY_LE_BHXH_NLD { get; set; }
        public decimal TY_LE_BHYT_NLD { get; set; }
        public decimal TY_LE_BHTN_NLD { get; set; }
        public decimal TY_LE_BHXH_NSDLD { get; set; }
        public decimal TY_LE_BHYT_NSDLD { get; set; }
        public decimal TY_LE_BHTN_NSDLD { get; set; }
        public decimal TY_LE_TNLD_BNN_NSDLD { get; set; }
        public decimal TY_LE_TNLD_BNN_UU_DAI { get; set; }
        public bool AP_DUNG_TRAN_BHXH_BHYT { get; set; }
        public bool AP_DUNG_TRAN_BHTN { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG_BAOHIEM> TB_BANGLUONG_BAOHIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CHINH_SACH_BHXH_VUNG> TB_CHINH_SACH_BHXH_VUNG { get; set; }
    }
}
