//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CA_KHUNGGIO
    {
        public long IDKHUNGGIO { get; set; }
        public long IDCAPHIENBAN { get; set; }
        public int STT { get; set; }
        public int BATDAU_PHUT { get; set; }
        public int KETTHUC_PHUT { get; set; }
        public string LOAI_KHUNGGIO { get; set; }
        public bool BAT_BUOC_QUET_THE { get; set; }
    
        public virtual TB_CA_PHIENBAN TB_CA_PHIENBAN { get; set; }
    }
}
