//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHINH_SACH_CONG_DOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CHINH_SACH_CONG_DOAN()
        {
            this.TB_BANGLUONG = new HashSet<TB_BANGLUONG>();
            this.TB_BANGLUONG_CONG_DOAN = new HashSet<TB_BANGLUONG_CONG_DOAN>();
        }
    
        public decimal ID { get; set; }
        public string MA_CHINH_SACH { get; set; }
        public string TEN_CHINH_SACH { get; set; }
        public System.DateTime NGAY_HIEU_LUC { get; set; }
        public Nullable<System.DateTime> NGAY_HET_HIEU_LUC { get; set; }
        public decimal TY_LE_DOAN_PHI_NLD { get; set; }
        public decimal CAP_PERCENT_STATUTORY_BASE_SALARY { get; set; }
        public decimal KINH_PHI_CONG_DOAN_NSDLD { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG_CONG_DOAN> TB_BANGLUONG_CONG_DOAN { get; set; }
    }
}
