//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CA_PHIENBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CA_PHIENBAN()
        {
            this.TB_CA_KHUNGGIO = new HashSet<TB_CA_KHUNGGIO>();
            this.TB_LICH_LAMVIEC = new HashSet<TB_LICH_LAMVIEC>();
        }
    
        public long IDCAPHIENBAN { get; set; }
        public decimal IDLOAICA { get; set; }
        public int SO_PHIENBAN { get; set; }
        public string TEN_PHIENBAN { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public Nullable<System.DateTime> DEN_NGAY { get; set; }
        public long TONG_GIAY_CHUAN { get; set; }
        public decimal CONG_QUY_DOI { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime TAO_LUC { get; set; }
        public decimal TAO_BOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CA_KHUNGGIO> TB_CA_KHUNGGIO { get; set; }
        public virtual TB_LOAICA TB_LOAICA { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LICH_LAMVIEC> TB_LICH_LAMVIEC { get; set; }
    }
}
