//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HESO_TANGCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_HESO_TANGCA()
        {
            this.TB_TANGCA = new HashSet<TB_TANGCA>();
        }
    
        public decimal ID { get; set; }
        public string TEN_QUYDINH { get; set; }
        public string LOAICONG { get; set; }
        public Nullable<decimal> IDLOAICONG { get; set; }
        public string LOAICA { get; set; }
        public Nullable<decimal> IDLOAICA { get; set; }
        public string GIO_BATDAU { get; set; }
        public string GIO_KETTHUC { get; set; }
        public decimal HESO_CHINHTHUC { get; set; }
        public decimal HESO_THUVIEC { get; set; }
        public Nullable<decimal> THUTU_UT { get; set; }
        public string GHICHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TANGCA> TB_TANGCA { get; set; }
    }
}
