//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KYCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_KYCONG()
        {
            this.TB_BANGLUONG = new HashSet<TB_BANGLUONG>();
            this.TB_CHAMCONG_LANTINH = new HashSet<TB_CHAMCONG_LANTINH>();
            this.TB_PAYROLL_CALCULATION_RUN = new HashSet<TB_PAYROLL_CALCULATION_RUN>();
        }
    
        public decimal MAKYCONG { get; set; }
        public Nullable<decimal> THANG { get; set; }
        public Nullable<decimal> NAM { get; set; }
        public Nullable<decimal> KHOA { get; set; }
        public Nullable<System.DateTime> NGAYTINHCONG { get; set; }
        public Nullable<decimal> NGAYCONGTRONGTHANG { get; set; }
        public Nullable<decimal> IDCTY { get; set; }
        public Nullable<decimal> TRANGTHAI { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<decimal> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public long CONG_INPUT_REV { get; set; }
        public long CONG_PUBLISH_REV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CHAMCONG_LANTINH> TB_CHAMCONG_LANTINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PAYROLL_CALCULATION_RUN> TB_PAYROLL_CALCULATION_RUN { get; set; }
    }
}
