//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LICH_LAMVIEC
    {
        public long IDLICH { get; set; }
        public decimal MANV { get; set; }
        public System.DateTime NGAY { get; set; }
        public string MA_PHANCONG { get; set; }
        public int SO_PHIENBAN { get; set; }
        public Nullable<long> THAY_THE_ID { get; set; }
        public Nullable<long> IDCAPHIENBAN { get; set; }
        public Nullable<long> IDQUYDINH { get; set; }
        public Nullable<System.DateTime> BATDAU_KEHOACH { get; set; }
        public Nullable<System.DateTime> KETTHUC_KEHOACH { get; set; }
        public string TRANG_THAI_PHAN_CONG { get; set; }
        public string LOAI_NGAY { get; set; }
        public string TRANG_THAI { get; set; }
        public string NGUON_PHAN_CONG { get; set; }
        public System.DateTime TAO_LUC { get; set; }
        public decimal TAO_BOI { get; set; }
        public string LY_DO { get; set; }
    
        public virtual TB_CA_PHIENBAN TB_CA_PHIENBAN { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_QUYDINH_CHAMCONG TB_QUYDINH_CHAMCONG { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
