//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NGUOI_PHU_THUOC
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public string HO_TEN { get; set; }
        public string MOI_QUAN_HE { get; set; }
        public string CCCD { get; set; }
        public string MA_SO_THUE_NPT { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public int THANG_BAT_DAU_GIAM_TRU { get; set; }
        public Nullable<int> THANG_KET_THUC_GIAM_TRU { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
