//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN_THUE
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public string MA_SO_THUE { get; set; }
        public bool IS_CU_TRU { get; set; }
        public bool CO_UY_QUYEN_QUYET_TOAN { get; set; }
        public System.DateTime NGAY_HIEU_LUC { get; set; }
        public Nullable<System.DateTime> NGAY_HET_HIEU_LUC { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
