//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN_BAOHIEM_THAM_GIA
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public short VUNG_LUONG { get; set; }
        public bool THAM_GIA_BHXH { get; set; }
        public bool THAM_GIA_BHYT { get; set; }
        public bool THAM_GIA_BHTN { get; set; }
        public bool THAM_GIA_TNLD_BNN { get; set; }
        public bool HUONG_TY_LE_TNLD_UU_DAI { get; set; }
        public Nullable<decimal> LUONG_DONG_BHXH_RIENG { get; set; }
        public System.DateTime NGAY_BAT_DAU { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
