//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN_PHUCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_NHANVIEN_PHUCAP()
        {
            this.TB_BANGLUONG_CT_SOURCE = new HashSet<TB_BANGLUONG_CT_SOURCE>();
        }
    
        public decimal MANV { get; set; }
        public decimal IDPC { get; set; }
        public string GHICHU { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public Nullable<decimal> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_PHUCAP TB_PHUCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG_CT_SOURCE> TB_BANGLUONG_CT_SOURCE { get; set; }
    }
}
