//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN_CONG_DOAN_THAM_GIA
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public bool LA_DOAN_VIEN { get; set; }
        public System.DateTime NGAY_GIA_NHAP { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
    }
}
