//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PAYROLL_CALCULATION_RUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PAYROLL_CALCULATION_RUN()
        {
            this.TB_BANGLUONG = new HashSet<TB_BANGLUONG>();
        }
    
        public decimal RUN_ID { get; set; }
        public decimal MAKYCONG { get; set; }
        public short NAM { get; set; }
        public byte THANG { get; set; }
        public string EXECUTION_TYPE { get; set; }
        public int TOTAL_EMPLOYEES { get; set; }
        public int SUCCESS_COUNT { get; set; }
        public int WARNING_COUNT { get; set; }
        public int ERROR_COUNT { get; set; }
        public string STATUS { get; set; }
        public string ERROR_SUMMARY { get; set; }
        public System.DateTime STARTED_AT { get; set; }
        public Nullable<System.DateTime> FINISHED_AT { get; set; }
        public string EXECUTED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        public virtual TB_KYCONG TB_KYCONG { get; set; }
    }
}
