//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUYET_TOAN_THUE_NAM
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public short TAX_YEAR { get; set; }
        public decimal POLICY_THUE_ID { get; set; }
        public decimal PROFILE_THUE_ID { get; set; }
        public byte SO_THANG_LAM_VIEC { get; set; }
        public decimal TONG_THU_NHAP_CHIU_THUE { get; set; }
        public decimal GIAM_TRU_BAN_THAN { get; set; }
        public decimal GIAM_TRU_PHU_THUOC { get; set; }
        public decimal GIAM_TRU_BAO_HIEM { get; set; }
        public decimal GIAM_TRU_KHAC { get; set; }
        public decimal TONG_GIAM_TRU { get; set; }
        public decimal THU_NHAP_TINH_THUE { get; set; }
        public decimal TONG_THUE_PHAI_NOP { get; set; }
        public decimal THUE_DA_KHAU_TRU { get; set; }
        public decimal THUE_CON_PHAI_NOP { get; set; }
        public decimal THUE_NOP_THUA { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_THUE_TNCN_CHINH_SACH TB_THUE_TNCN_CHINH_SACH { get; set; }
    }
}
