//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUYDINH_CHAMCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_QUYDINH_CHAMCONG()
        {
            this.TB_CONG_PHANDOAN = new HashSet<TB_CONG_PHANDOAN>();
            this.TB_LICH_LAMVIEC = new HashSet<TB_LICH_LAMVIEC>();
        }
    
        public long IDQUYDINH { get; set; }
        public string MA_QUYDINH { get; set; }
        public int SO_PHIENBAN { get; set; }
        public string TEN_QUYDINH { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public Nullable<System.DateTime> DEN_NGAY { get; set; }
        public int GIAY_MIEN_VIPHAM_MUON { get; set; }
        public int GIAY_MIEN_VIPHAM_SOM { get; set; }
        public int GIAY_DUNG_SAI_HUONG_CONG { get; set; }
        public string CACH_HUONG_DUNG_SAI { get; set; }
        public string CACH_DEM_MUON { get; set; }
        public int CUA_SO_VAO_TRUOC_GIAY { get; set; }
        public int CUA_SO_RA_SAU_GIAY { get; set; }
        public int GIOI_HAN_GHEP_GIAY { get; set; }
        public string MUI_GIO { get; set; }
        public short DEM_BATDAU_PHUT { get; set; }
        public short DEM_KETTHUC_PHUT { get; set; }
        public string KIEU_LAM_TRON { get; set; }
        public int BUOC_LAM_TRON_GIAY { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime TAO_LUC { get; set; }
        public decimal TAO_BOI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CONG_PHANDOAN> TB_CONG_PHANDOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LICH_LAMVIEC> TB_LICH_LAMVIEC { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
