//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_QUYET_TOAN_THUE_NAM_CT
    {
        public decimal ID { get; set; }
        public decimal QUYET_TOAN_ID { get; set; }
        public decimal MANV { get; set; }
        public short TAX_YEAR { get; set; }
        public byte BAC_THUE { get; set; }
        public decimal CAN_DUOI { get; set; }
        public Nullable<decimal> CAN_TREN { get; set; }
        public decimal THU_NHAP_CHIU_THUE_BAC { get; set; }
        public decimal THUE_SUAT { get; set; }
        public decimal TIEN_THUE_BAC { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    }
}
