//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SYS_REPORT
    {
        public decimal REP_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string REP_NAME { get; set; }
        public Nullable<decimal> VISIBLED { get; set; }
        public Nullable<decimal> TUNGAY { get; set; }
        public Nullable<decimal> THANG_NAM { get; set; }
        public Nullable<decimal> MACTY { get; set; }
        public Nullable<decimal> MADVI { get; set; }
    }
}
