//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_THUE_TNCN_BAC
    {
        public decimal ID { get; set; }
        public decimal POLICY_THUE_ID { get; set; }
        public short TAX_YEAR { get; set; }
        public string PERIOD_TYPE { get; set; }
        public byte BAC_THUE { get; set; }
        public decimal CAN_DUOI { get; set; }
        public Nullable<decimal> CAN_TREN { get; set; }
        public decimal THUE_SUAT { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        public virtual TB_THUE_TNCN_CHINH_SACH TB_THUE_TNCN_CHINH_SACH { get; set; }
    }
}
