//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRANSLATIONS
    {
        public string TABLE_NAME { get; set; }
        public string RECORD_ID { get; set; }
        public string COLUMN_NAME { get; set; }
        public string LANGUAGE_CODE { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual TB_LANGUAGES TB_LANGUAGES { get; set; }
    }
}
