//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_THONGBAO
    {
        public decimal ID { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string NGUOIDANG { get; set; }
        public System.DateTime NGAYDANG { get; set; }
        public string LOAI_TB { get; set; }
        public Nullable<bool> IS_PINNED { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAY_HETHAN { get; set; }
        public string FILE_DINHKEM { get; set; }
        public string MACTY { get; set; }
        public string MAPB { get; set; }
    }
}
