//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_THUE_TNCN_CHINH_SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_THUE_TNCN_CHINH_SACH()
        {
            this.TB_BANGLUONG = new HashSet<TB_BANGLUONG>();
            this.TB_BANGLUONG_THUE_CT = new HashSet<TB_BANGLUONG_THUE_CT>();
            this.TB_QUYET_TOAN_THUE_NAM = new HashSet<TB_QUYET_TOAN_THUE_NAM>();
            this.TB_THUE_TNCN_BAC = new HashSet<TB_THUE_TNCN_BAC>();
        }
    
        public decimal ID { get; set; }
        public string MA_CHINH_SACH { get; set; }
        public string TEN_CHINH_SACH { get; set; }
        public short TAX_YEAR { get; set; }
        public System.DateTime NGAY_HIEU_LUC { get; set; }
        public Nullable<System.DateTime> NGAY_HET_HIEU_LUC { get; set; }
        public decimal GIAM_TRU_BAN_THAN_THANG { get; set; }
        public decimal GIAM_TRU_PHU_THUOC_THANG { get; set; }
        public decimal GIAM_TRU_BAN_THAN_NAM { get; set; }
        public decimal GIAM_TRU_PHU_THUOC_NAM { get; set; }
        public string TRANG_THAI { get; set; }
        public System.DateTime CREATED_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG> TB_BANGLUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANGLUONG_THUE_CT> TB_BANGLUONG_THUE_CT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_QUYET_TOAN_THUE_NAM> TB_QUYET_TOAN_THUE_NAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_THUE_TNCN_BAC> TB_THUE_TNCN_BAC { get; set; }
    }
}
