//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER_EMPLOYEE_MAPPING
    {
        public decimal ID { get; set; }
        public decimal USER_ID { get; set; }
        public decimal EMPLOYEE_ID { get; set; }
        public bool IS_MOBILE_ENABLED { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
