//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_YEUCAU_NGHIPHEP
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public string LOAIPHEP { get; set; }
        public System.DateTime TUNGAY { get; set; }
        public System.DateTime DENNGAY { get; set; }
        public decimal SONGAY { get; set; }
        public string LYDO { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<decimal> NGUOIDUYET { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public string GHICHUDUYET { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> BATDAU_NGHI { get; set; }
        public Nullable<System.DateTime> KETTHUC_NGHI { get; set; }
        public Nullable<long> GIAY_NGHI { get; set; }
        public string NGUON_CHI_TRA { get; set; }
        public string LOAI_HUONG_CONG { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
