//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_YEUCAU_TANGCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_YEUCAU_TANGCA()
        {
            this.TB_TANGCA = new HashSet<TB_TANGCA>();
        }
    
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public System.DateTime NGAY { get; set; }
        public decimal GIOTANGCA { get; set; }
        public Nullable<decimal> IDCA { get; set; }
        public string LYDO { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<decimal> NGUOIDUYET { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public string GHICHUDUYET { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> BATDAU_DANGKY { get; set; }
        public Nullable<System.DateTime> KETTHUC_DANGKY { get; set; }
        public Nullable<System.DateTime> BATDAU_DUYET { get; set; }
        public Nullable<System.DateTime> KETTHUC_DUYET { get; set; }
        public Nullable<long> GIAY_OT_DUYET { get; set; }
    
        public virtual TB_LOAICA TB_LOAICA { get; set; }
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TANGCA> TB_TANGCA { get; set; }
    }
}
