//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_YEUCAU_DIEUCHINHCONG
    {
        public decimal ID { get; set; }
        public decimal MANV { get; set; }
        public System.DateTime NGAY { get; set; }
        public string LOAIDIEUCHINH { get; set; }
        public string GIO_VAO { get; set; }
        public string GIO_RA { get; set; }
        public string LYDO { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<decimal> NGUOIDUYET { get; set; }
        public Nullable<System.DateTime> NGAYDUYET { get; set; }
        public string GHICHUDUYET { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> THOIDIEM_VAO_CU { get; set; }
        public Nullable<System.DateTime> THOIDIEM_RA_CU { get; set; }
        public Nullable<System.DateTime> THOIDIEM_VAO_MOI { get; set; }
        public Nullable<System.DateTime> THOIDIEM_RA_MOI { get; set; }
        public Nullable<decimal> IDBANGCONG_GOC { get; set; }
        public string NGUON_HASH_CU { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        public virtual TB_SYS_USER TB_SYS_USER { get; set; }
    }
}
