//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AI_EMPLOYEE
    {
        public decimal MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string DIACHI { get; set; }
        public string TEN_PHONGBAN { get; set; }
        public string TEN_BOPHAN { get; set; }
        public string TEN_CHUCVU { get; set; }
    }
}
