//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_AI_ALLOWANCE
    {
        public decimal MANV { get; set; }
        public string HOTEN { get; set; }
        public string TENPC { get; set; }
        public Nullable<decimal> SOTIEN { get; set; }
        public decimal KYCONG { get; set; }
    }
}
